fission/fission

- glide.lock
- glide.yaml
- poolmgr/gp.go
- poolmgr/gpm.go
- poolmgr/poolmgr.go
Client 1.5 is compatible with Kubernetes version 1.3 through 1.5.
> Move client-go dependency to 1.5

- README.md
- fission-cloud.yaml
- fission-nodeport.yaml
- fission.yaml
I tried to update the Readme to make it a little bit easier to start with `fission` on minikube.
> Add minikube example in readme

- README.md
Hey 👋 
I was going through the README to test this out and noticed that if you don't prefix the FISSION_URL with http:// you get the following error:
```
Failed to create environment: Post xxx.xxx.xxx.xxx/v1/environments: unsupported protocol scheme ""
```
I've added a bit on the README to prompt for this.
Hope this is ok.
Thanks,
Ville
ps. Awesome project! I'll definitely be playing around with this more soon! The cold start response time over what the AWS API Gateway latency is makes this very feasible!
> Updated README to include protocol scheme for FISSION_URL prefix

- cache/cache_test.go
cache.Set() returns existing value; update the test accordingly.
> Fix cache test

- fission/function.go
- fission/main.go
This allows users to add --method and --url params to their "fission
fn create" command line.  It sets up the route to call the latest
version of the function; user can edit the route with the "fission
route update" command, if they want to.
> Add HTTP route create params to function create command

- poolmgr/api.go
- router/httpTriggers.go
Addresses issue #51. Makes versioning in poolmgr explicit, so its
cache needs no invalidation on version update.  Functions in poolmgr
are always cached by name and UID.
Router now updates implictly versioned routes with the latest version
of a function.
This means that users will see requests to implicitly-versioned routes
go to the latest version of a function within 3 seconds.  (Those 3 sec
will go away when we use a real watch instead of polling the
controller.)
There's no change in behaviour for routes that explictly specify a
function UID.
> Update router cache on new function version

- poolmgr/cleanup.go
- poolmgr/gp.go
- poolmgr/gpm.go
- poolmgr/poolmgr.go
Addresses (a part of) #21.  Keep an instance id unique to a running poolmgr instance, and label resources with it.  Clean up resources that are orphaned by old poolmgr instances.
> Poolmgr: ensure orphaned resources are cleaned up

- fission-bundle/main.go
Poolmgr allows setting the `namespace`in which to run function containers, but `fission-bundle` does not allow that parameter.
> fission-bundle: allow setting the namespace

- router/httpTriggers.go
Poolmgr removed the default-latest-version semantics to simplify
caching.  But this broke the router's internal function routes, which
are used by kubeWatcher.  The router now exposes a versionless url
and regularly updates that to point to the latest version.
> Bugfix for internal routes

- fission/common.go
I've added a bit of logic to allow users to specify `https` for their FISSION_URL, which is critical when exposing the services via ingress and automatic TLS certificates from vault or LetsEncrypt.
> bugfix (cli) Update the URL check to work with https

- examples/nodejs/kubeEventsSlack.js
This example sends change events from a watch to a Slack webhook.
> kubewatcher example: send watch updates to slack

- fission-bundle/build.sh
This allows it to be executed from alternative shells (fish, for
example) as `./build.sh`.
> Make build an actual sh script

- poolmgr/gp.go
Addresses issue #113.  poolmgr.MakeGenericPool does not need to wait
for a ready pod.  Kubernetes already retries image fetching, so
there's no need to repeat the task in fission.  And if it's a
non-retriable error (like the image URL being wrong), then the
deployment will stay broken, and the user can fix the environment with
'fission env update' (or 'fission env delete' followed by 'fission env
create').
> Don't wait for ready pod in MakeGenericPool

- controller/fileStore.go
This PR fixed the problem that user may encounter when trying to delete a function without function file in filestore. Now, the controller checks the file existence before removing it. (https://github.com/fission/fission/issues/108)
```
$ fission fn list
NAME  UID                                  ENV
hello bdecc45c-a528-4f1f-9fca-728bdc3d86f6 nodejs
$ fission fn delete --name hello
Failed to delete function 'hello': Delete failed: remove /filestore/bdecc45c-a528-4f1f-9fca-728bdc3d86f6: no such file or directory
```
> Fixed failed to delete function when function's file is not exist

- controller/api_test.go
- controller/client/client.go
- controller/resourceStore.go
- error.go
Motivation: Creating duplicate resources currently results in a 500
error being displayed by the client, with no information about the true
nature of the failure.
Modifications:
* ResourceStore now converts any errors from the etcd client into
fission errors, capturing the reason for the error in the case of a
duplicate key (as ErrorNameExists)
* ErrorNameExists errors are signaled to the client with a
422 (Unprocessable Entity) HTTP status
* MakeErrorFromHTTP() now reads the body of the error response to
retrieve the actual error message instead of using the HTTP status
message
* the controller client now uses MakeErrorFromHTTP() to centralize
status code -> error code mapping
* tests for all of the resources now check that duplicate resources are
reported properly
Result: The client can …
> Better convey duplicate name errors to client

- controller/api_test.go
- controller/resourceStore.go
This allows for proper classification of the error on the client side.
> Report KeyNotFound from etcd as a 404

- INSTALL.md
- README.md
The latest stable release for minikube is published at
storage.googleapis.com/minikube/releases/latest
> Use latest for stable release of minikube

- controller/api_test.go
- controller/httpTriggerApi.go
- types.go
Testing Done:
$ fission route create --method POST --url /test-routes --function test-r
trigger '6b90a150-9a9f-4737-981f-3faabfef3580' created
$ fission route create --method GET --url /test-routes --function test-r
trigger 'bd48e8d6-519f-4ebd-9b86-aa985cd63c7b' created
$ fission route create --method POST --url /test-routes --function test-r
ERRO[0000] Failed to create http trigger                 err="(Error 0) HTTP error 409" name=6d0a8286-99da-4315-9aaf-775308d5d994
Failed to create HTTP trigger: (Error 0) HTTP error 409
> Allow unique HTTP route & method (#102)

- controller/client/client.go
- controller/resourceStore.go
- error.go
- types.go
Motivation: The output when an error occurs shows an integer error code,
which isn't very helpful. And in the case of an error when creating a
resource, you also get a redundant log message from the controller
client.
Modifications:
* the controller client now has a flag to suppress error logging
* the CLI client uses a logger with that flag set
* the error codes enum is now typed to allow `stringer` to generate a
String() for it
* a go:generate directive was added to run stringer automatically when
`go generate` is called
* the generated String() allows for the enum name to be displayed in the
error output
* the type used for an error code is now public (fission.ErrorCode) so
it can be used as an argument to MakeError(), since the enum is now
typed.
* the format of the error message from …
> Improve command-line client error output

- .gitignore
`vendor/` was erroneously removed from `.gitignore` in 99d6a95bc19a479bc7bbab538984f0e00de59711. This PR re-adds it
> Ignore the vendor folder

- examples/nodejs/kubeEventsSlack.js
- change comma to semicolon
- change variable name `path` to `slackWebhookPath`
example is not working without these changes.
> fix(kubeEventsSlack): typo and wrong variable name

- poolmgr/gp.go
This PR aims to fixed the issue (https://github.com/fission/fission/issues/139) when fission is busy at creating functions. 
Here is the explanation of the root cause. (https://www.goinggo.net/2013/09/iterating-over-slices-in-go.html)
> Fixed pod has no ip (#139)

- README.md
I had a bit of trouble compiling fission since I am new to the Go ecosystem - it was not clear to me that I needed to clone to `$GOPATH/src/github.com/fission/fission`.
> Make it more clear where to clone this repo

- controller/api_test.go
- controller/functionStore.go
- controller/resourceStore.go
The current version may delete the function record and left some function code behind if an uid is provided.
If no uid provided, all versions of function files and record will be deleted.
If an uid provided, delete the specific version code, update the function with the latest code.
> Fix function delete with uid

- controller/client/client.go
- controller/environmentApi.go
- controller/functionApi.go
- controller/httpTriggerApi.go
- controller/watchApi.go
Partially resolves #143 
One weird issue:
I was trying to set the `Location` header with 
```go
w.Header().Set("Location", "/v1/functions/"+f.Name)
```
but it always ended up being stripped out of the response for some reason. Any ideas?
> Return 201 for created resources

- environments/nodejs/.gitignore
- environments/nodejs/Dockerfile
- environments/nodejs/package.json
- environments/nodejs/server.js
- environments/nodejs/test/test.js
- examples/nodejs/hello-callback.js
- examples/nodejs/hello.js
- examples/nodejs/kubeEventsSlack.js
- examples/nodejs/stock.js
This PR upgrades the Node.js environment to Node.js 7.6.0+. Node 7.6.0 introduced async/await without the harmony flag, which allows you to write cleaner (asynchronous) functions without the mess that is callbacks. With this change, Node environment functions now look like this:
```javascript
module.exports = async function(context) {
const response = await request({ url: 'http://google.com'});
const anotherResponse = await request({ url: 'http://google.com'});
return {
status: 200,
body: "Hello, world!\n"
};
}
```
Changelog:
* Upgrade Node.js to 7.6.0+
* Add support for `async` functions
* Replace `request-promise` with `request-promise-native`
> Upgrade node environment to Node.js 7.6.0+

- .travis.yml
We use plugins in the Golang environment, it's easiest to just move to Go 1.8 for the whole project.
> Drop Go 1.7, use Go 1.8

- controller/api.go
- controller/api_test.go
When the request is handled successfully, json data is returned, this
patch changes the response Content-Type header from text/plain to
application/json
Fixes: #144
> Set correct Content-Type in the http response

- environments/python3/Dockerfile
- Saves 241 MB from the base example image, bringing things down to 242MB
in total.
> Lighten up the python3 base image (alpine)

- charts/fission/templates/deployment.yaml
- charts/fission/templates/svc.yaml
- charts/fission/values.yaml
Primarily this involved removing the release namespace, which is
controlled by helm.  If you want resources in a namespace you set
--namespace= with helm install, anything else leaves helm unable
to properly manage the resources.
I think the functions namespace won't work either on a delete.
> Make the chart work with helm 2.2

- README.md
- fission-openshift.yaml
Add the minimal OpenShift components needed to deploy Fission with the
same functionality as with Kubernetes, using only a deployment template
file (fission-openshift.yaml). No need of objects creation via CLI.
Update deployment instructions in README.md
> Add OpenShift support (#107)

- examples/nodejs/stock.js
The example returns a JSON object, but headers are not properly set.
Also no checks or validations are performed on processing the body. This is probably a good opportunity  to show how to deal with errors.
> Modify the stock example to show how to change the Content-Type

- fission-rbac.yaml
To deal with the issue of lack of RBAC permission noted in fission/fission#160 , created 'fission-rbac.yml'. Made it a separate file so that users have choice (in case they use older k8s) on whether to install with RBAC permissions or not.
If changes are approved, happy to help update documentation to reflect changes.
> Adding fission-rbac.yml for 

- Documentation/Roadmap.md
Correct two incorrect links in the roadmap doc due to typo (cut/paste from previous header).
> Fix two links in Roadmap doc

- poolmgr/gpm.go
The generic pool manager creates a generic pool with the reference of environment metadata. Since the reference is the address of loop variable, the content of metadata will be replaced with the last element of env list. So pool manager sets up logging with the wrong env.
> Fix pool contains wrong environment metadata

- controller/api.go
- controller/api_test.go
- controller/environmentApi.go
- controller/fileStore.go
- controller/functionApi.go
- controller/functionStore.go
- controller/httpTriggerApi.go
- controller/resourceStore.go
- controller/timeTriggerApi.go
- controller/watchApi.go
- fission/logdb/logdb.go
- glide.lock
- glide.yaml
- logger/logger.go
Because of https://github.com/sirupsen/logrus/issues/543 `glide install` fails to install `logrus` right now. This PR simply bumps us to the newest version with correct references
Used latest SHA on master for locking which obviously isn't ideal but until a new release is cut ( https://github.com/sirupsen/logrus/issues/555 ) probably good enough
> Fix s/Sirupsen/sirupsen/ for logrus

- environments/go/Dockerfile
- environments/go/README.md
- environments/go/builder/Dockerfile
- environments/go/builder/go-function-build
- examples/go/README.md
Addresses #222.
Plugins and the binaries loading them need to be built with the exact
same go version.
Also update README instructions.
> Specify full golang version in Dockerfiles and build helper script

- poolmgr/client/client.go
- router/functionHandler.go
For every function call, the router has to make a tap-service request to poolmgr.
We can aggregate the requests in a interval (5 seconds).
> Aggregate tap service request in interval

- router/functionHandler.go
Retrieve gorilla/mux URL params in functions
Add them in HTTP headers, such as X-Fission-Params-${key}: ${value}
> Retrieve URL params in functions (#158)

- poolmgr/api.go
- poolmgr/gp.go
- router/functionServiceMap.go
This is a proposal for fixing creating redundant pods on heavy load cold start.
When there are many requests on a cold function and the func service is not ready, each of the request will trigger poolmgr to specialize a pod. If the env pool size is smaller than the incoming concurrent requests, the request is hung up until a pod is available in the env pool. Then a pod is specialized and deleted if a func service already exists (beated by other requests). In `poormgr.go`, there is a already TODO showing we need a fix for this.
In this commit, the first request will create the func service as usual and create a channel for other requests to block on. Once the func service is ready, it will notify all the wait requests to fetch the func request from the cache again. There is no lock to …
> Fix creating redundant pods on heavyload coldstart

- fission/function.go
This PR aims to improve the usability of fission CLI mentioned in https://github.com/fission/fission/issues/237. Also, fix the argument `--package` is not working in `fission fn update`. 
Now, at least one argument (`--env`, `--code`, `--package`) needs to specify when a user tries to update a function.
> Fission update must require at least one change to function

- environments/ruby/README.md
- environments/ruby/fission/context.rb
- environments/ruby/fission/handler.rb
- environments/ruby/fission/request.rb
- environments/ruby/fission/specializer.rb
- environments/ruby/server.rb
- examples/ruby/README.md
this PR adds a helper method in the ruby context/request to make using path parameters easier
e.g.
given a route /path/:id
and a request for /path/123
a header would be present with the form `X-Fission-Params-Id: 123`
and with this update `request.params` would return the hash `{'id' => '123'}`
> include path parameters in params hash for ruby environment

- fission/main.go
small PR to fix a typo in the usage for the CLI
"function" was mis-spelled as "funtion"
> fix typo funtion -> function

- mqtrigger/messageQueue/nats.go
This PR aims to fix nats trigger tries to reply message even when the resptopic was not set.
Thanks for @yqf3139 's test
> Fix nats trigger replies message to non-existing response topic

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/svc.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
Remove hardcoded "fission" namespace in various places.
Remove etcd deployment and service, since we use K8s APIs now.
Add ClusterRoleBinding for the fission service account, to allow fission components to access TPRs. We currently make the service account a cluster admin. This is more permissive than it should be; we should define a specific role for just fission resources.
> Helm chart updates

- controller/environmentApi.go
- controller/functionApi.go
- controller/httpTriggerApi.go
- controller/mqTriggerApi.go
- controller/timeTriggerApi.go
- controller/tpr.go
- controller/watchApi.go
This small PR aims to improve the usability of fission CLI when a user tries to create a resource with an invalid name. (https://github.com/fission/fission/issues/269)
> Parse metadata.Name before creating tpr resource

- fission/main.go
- fission/mqtrigger.go
- mqtrigger/messageQueue/nats.go
- types.go
This PR aims to add content-type to http header when mqtrigger tries to post message to the function. (https://github.com/fission/fission/issues/275)
The user can specify content-type of messages when creating the mqtrigger, and update it later.
```
$ fission mqtrigger create --name h1 --function hello1 --mqtype "nats-streaming" --topic "foo.bar" --resptopic "foo.foo" --contenttype "application/xml"
$ fission mqtrigger update --name h1 -c application/json
```
Also, `mqtrigger list` shows the message content type now.
```
$ fission mqtrigger list
NAME FUNCTION_NAME MESSAGE_QUEUE_TYPE TOPIC   RESPONSE_TOPIC PUB_MSG_CONTENT_TYPE
h1   hello1        nats-streaming     foo.bar foo.foo        application/json
```
> Set message content-type based on the trigger.Spec.ContentType

- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
- fission-rbac.yaml
- poolmgr/gp.go
This PR creates a service account for fetcher to access TPR(https://github.com/fission/fission/issues/286).
> Fix fetcher failed to access TPR if RBAC is enabled

- charts/README.md
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
This PR aims to update helm charts, so that a user can change fetcher image with poolmgr env (https://github.com/fission/fission/blob/master/poolmgr/gp.go#L90).
> Set fetcher image through poolmgr env

- controller/api.go
Tested using both v1 and v2 CLIs against v2 server
> Improve error message if an older CLI attempts to make a request

- examples/go/README.md
Really minor documentation fix that might trip people up otherwise. Changes the `--env` referenced in the create command to match the env that is created earlier in the example.
> Minor documentation fix for the Go example

- charts/fission-all/Chart.yaml
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
- hack/runtests.sh
- test/build_and_test.sh
- test/test_utils.sh
- test/tests/test_node_hello_http.sh
- tpr/tpr_test.go
End to end tests on a Kubernetes cluster. Travis CI builds now build fission-bundle, cli, fetcher; deploy the helm chart on a k8s cluster; and run a simple hello world test against this setup.
This PR includes a bunch of little bugfixes to the helm charts as well, which I found while getting this test to work.
> Helm chart bugfixes + end to end test bugfixes

- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
- controller/api.go
- controller/api_test.go
- controller/client/function.go
- controller/client/package.go
- controller/functionApi.go
- controller/packageApi.go
- environments/fetcher/fetcher.go
- fission/function.go
- poolmgr/gp.go
- poolmgr/poolmgr_test.go
- test/test_utils.sh
- tpr/client.go
- tpr/package.go
- tpr/tpr.go
- tpr/tpr_test.go
- tpr/types.go
- types.go
Motivation:
* Functions will need to share packages
* A package storage system may be more generally useful than just functions (for example, for storing static assets)
> [wip] Split out the Package type into a first class Kubernetes resource

- fission/environment.go
- fission/function.go
- fission/main.go
This PR is a first PR for Environment v2. In this PR, a user can add the env builder & source pkg through the cli.
env builder
```
$ fission env create --name nodejs --image fission/node-env --builder fission/node-env --buildcmd "./build.sh"
```
src pkg
```
$ fission fn create --name hello1 --env nodejs --srcpkg test.zip --method GET
```
> Add env builder & srcpkg through cli

- environments/fetcher/fetcher.go
- glide.lock
- glide.yaml
In env v2, the fetcher has couple things to do:
1. archive deployment package and upload it after the build is finished
2. unarchive source package for builder to build with
2. unarchive deployment package for function container to run with
In this PR, fetcher will check the file type and unarchive it if it's a zip file. And since a deployment package may be a directory instead of a piece of code, a user needs to specify the entry point of function so that env runtime knows how to load the function.
> Unarchive zip file after fetcher downloads the package

- poolmgr/api.go
- router/functionReferenceResolver.go
- router/functionServiceMap.go
- router/httpTriggers.go
- test/tests/test_function_update.sh
This PR aims to solve https://github.com/fission/fission/issues/287.
When an HTTP request comes to the router, it will send a tap request to pool manager with function metadata. The metadata within payload may be out-of-date, so pool manager always returns the IP address of old function pod to the router. In this situation, a user received wrong function response until the pod is killed by the pool manager.
With this PR, when a `getServiceForFunction` request comes to pool manager, pool manager will fetch the latest function metadata from TPR and use this metadata to find correspond service cache. If cache missed, then a new function pod will be created to serve the user request.
> Use latest function metadata to check cached function service.

- controller/api_test.go
- controller/packageApi.go
- environments/fetcher/fetcher.go
- fission/function.go
- poolmgr/api.go
- tpr/tpr_test.go
- types.go
Rename the old "packages" to "archives".
"Packages" are now a pair of source and deployment archives.
Functions now have a single FunctionPackageRef into a single Package,
instead of two separate references.
The Package type will also have a PackageStatus, which will contain
build information.
> Move builds to package level

- Documentation/docs-site/content/install.md
- Documentation/docs-site/content/upgrade-from-v0.1.md
- fission/main.go
- fission/upgrade.go
- v1/types.go
This allows people to upgrade to 0.2.1 without losing their state or having to manually migrate it. 
Upgrade guide will be at: http://fission.io/docs/v0.2.1/upgrade-from-v0.1/
Tested on platform9-ops internal cluster.
closes #303
> Upgrade tool for 0.1 -> 0.2.1

- environments/nodejs/Dockerfile
7.x has not been maintained since April. 8.x is going into LTS
during October and will receive another 30 months of support.
This update should simply work out of the box. Let me know if
I can help with anything
> Upgrade Node Environment to 8.x

- cache/cache.go
- poolmgr/functionServiceCache.go
- poolmgr/gp.go
This adds a little bit of support for multiple specialization to the
function service cache. It allows Add() to succeed if the pod and
address maps already contain entries.
But it doesn't deal with DeletePod and TouchByAddress. That's ok for
now, because the workflow engine never deletes the environment pod
(that pod is the workflow engine).
However, if/when we want full support for multiple specialization,
that will require updating both DeletePod and TouchByAddress.
> Function service cache partial support for multiple specialization

- hack/release.sh
Currently some of the `latest` images are not deployed into DockerHub, as described in the issue #328
> Tag and push the latest environment images

- charts/fission-all/templates/post-install-job.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/post-install-job.yaml
- charts/fission-core/values.yaml
- test/test_utils.sh
This lets us count how many people install fission.
It can be disabled with `helm install --set analytics=false ...`
> Post-install hook to poke analytics function

- environments/nodejs/package.json
Since `mz` has already bumped for several times without
breaking change, it's better to follow the updates.
```console
$ npm outdated
Package  Current  Wanted  Latest  Location
mz         2.1.0   2.1.0   2.7.0  fission-nodejs-runtime
```
Fixes: https://github.com/fission/fission/issues/167
> Update a dependency in the package.json

- environments/dotnet20/Dockerfile
- environments/dotnet20/ExecutorModule.cs
- environments/dotnet20/FissionCompiler.cs
- environments/dotnet20/FissionContext.cs
- environments/dotnet20/Function.cs
- environments/dotnet20/Program.cs
- environments/dotnet20/README.md
- environments/dotnet20/build.sh
- environments/dotnet20/dotnet20.sln
- environments/dotnet20/fission-dotnet20.csproj
- examples/dotnet20/arguments.cs
- examples/dotnet20/echo.cs
- examples/dotnet20/helloworld.cs
- examples/dotnet20/requestbody.cs
- examples/dotnet20/requestheaders.cs
Adding a new dotnet environment, supporting dotnet core 2.0.
Project structure changed. Project.json was abandoned. Project..csproj is now used.
All tests, referenced in documentation were done. 
A new docker image should be created officially : fission/dotnet20-env
> Fission dotnet 2.0 env

- mqtrigger/messageQueue/messageQueue.go
Fix for #340 
The issue was that `range` allocates the `trigger` value once which causes the newTriggerMap to have reference to last instance trigger.
To fix the issue, create a new trigger by pulling it off the original map.
> Multiple Trigger Definitions Fix

- environments/nodejs/server.js
Currently, the node-env only uses the 'json' and 'raw' bodyparser. These only handle bodies with content-types `application/octet-stream` and `application/json`. Bodies of other formats are ignored by the `request.body` (and would need to be fetched with the bit awkward parsing).
Adding `app.use(bodyParser.text({ type : "*/*" }));` will parse any other content-types (other than json and raw which take precedence) to plain text to `request.body`. This should avoid most issues with missing bodies.
The `*/*` could definitely be left out. But I propose it to avoid also missing bodies for 'related' content types like text/html.
> Add bodyparser for text/plain to node-env

- glide.lock
- glide.yaml
- router/functionReferenceResolver.go
- router/httpTriggers.go
- router/router.go
- router/router_test.go
- tpr/client.go
Before this PR, resolver takes long time to resolve function because of `kube-api-qps` of api server.
In this PR, resolver uses informer cache to resolve function instead of making http call every time to avoid hitting the qps of api server. And now the resolve time is down to average 5µs (original ~400ms) each time. (solve issue https://github.com/fission/fission/issues/366)
> Reduce function resolving time

- test/test_utils.sh
Some failed helm releases were not deleted after the testing and caused helm failed to deploy new release to test k8s cluster. This PR add cleanup step to remove failed releases before deploying new helm release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/393)
> Delete failed helm releases to prevent test case failure

- router/functionReferenceResolver.go
- router/httpTriggers.go
- router/router.go
- router/router_test.go
In router we launch two watcher to watch function changes. One for HTTPTriggerSet, another for functionReferenceResolver. 
In some situation, two watchers may not receive change events at the same time.  So functionReferenceResolver return out-of-date function metadata  back to httpTrigger. In this case, router proxies request to the old pod and caused test failure.
This PR aims to solve this problem by sharing http trigger resource store with functionReferenceResolver to prevent data consistency problem.
Following is the interaction diagram for this problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/390)
> Fix functionReferenceResolver return out-of-date function metadata

- poolmgr/functionServiceCache.go
- poolmgr/functionServiceCache_test.go
- poolmgr/gp.go
Poolmgr uses Pod name in FuncSvc in functionServiceCache. With new backends being developed, we need a generic way which can encompass more kinds of objects. This change uses api.ObjectReference instead. This was needed in #387 as part of #193 development.
The only caveat is that the backend has to make sure that queries to K8S API are handled appropriately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/391)
> Changed podName to a generic objectReference in cache implementation

- .travis.yml
- builder/builder.go
- builder/cmd/Dockerfile
- buildermgr/common.go
- buildermgr/envwatcher.go
- environments/python/builder/Dockerfile
- hack/release.sh
- test/build_and_test.sh
- test/test_utils.sh
- types.go
This PR tackles a couple of issues with builder(mgr)
It...:
- ...fixes the issue where the environment-scoped buildcmd was not used.
- ...allows files to be passed to the builder
- ...adds a `fission/builder` docker image avoiding the need to compile fission to get the binary.
- ...fixes the issue where the builder did not log the stderr
~~As a flyby, I updated the deploy script to correspond with the one in fission workflows~~
cc @life1347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/397)
> Add fission/builder image

- fission/function.go
- fission/logdb/influxdb.go
- fission/logdb/logdb.go
- fission/main.go
This PR solves an issue with fission function logs where the log records were displayed to the console in an erroneous order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/405)
> fission function logs returns logs in correct order now

- environments/fetcher/fetcher.go
- fission/common.go
- fission/function.go
- fission/main.go
- fission/package.go
- test/test_utils.sh
- test/tests/test_package_command.sh
- types.go
This PR adds `package` command to CLI. `package` provides some useful subcommands to use such as packages CURD and display package detail information. Also its able to reuse existing package at function creation.
```
NAME:
fission package - Manage packages
USAGE:
fission package command [command options] [arguments...]
COMMANDS:
create     Create new package
update     Update package
getsrc     Get source archive content
getdeploy  Get deployment archive content
info       Show package information
list       List all packages
delete     Delete package
OPTIONS:
--help, -h  show help
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/385)
> Add package command

- environments/fetcher/client/client.go
Pool manager crashed due to nil pointer problem when it failed at calling fetcher to fetch code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/418)
> Fix pool manager crash problem if failed at http call

- router/functionHandler.go
In `http.Request` contains a `Host` field that holds the hostname the HTTP request targeting. When a request comes to the router, the router will proxy the request to one of backend function pods. 
Normally, it will be fine not changing the Host field of the request. But after some experiment for istio integration, the request with mismatched Host and Url was rejected by istio-proxy automatically. And the solution is to replace Host with right hostname the request targeting.
Since it's not really related to istio, so I separated it into an independent PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/419)
> Overwrite request host with internal host to prevent request rejection

- charts/README.md
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
tested fission on openshift 3.7.0 and installed fine, without having to use openshift variables
those variables were used prior to switching to custom resource definitions, and as such are obsolete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/424)
> Removed openshift specifics as they are no longer necessary

- builder/builder.go
- builder/client/client.go
- buildermgr/api.go
- buildermgr/common.go
- buildermgr/pkgwatcher.go
This PR tends to fix the bug ~introduced in PR #397~ that builder manager updates package with empty build logs when build script exited with non-zero code. Also fix a potential nil pointer issue. (issue #423)
(Update: 2017/12/05 )
Looks like this bug existed at the beginning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/426)
> [Issue 423] build logs not saved on build error

- executor/poolmgr/gp.go
Hi,
Here is a small contribution to allow Fission to talk to IPv6 function pods. 
I'm able to make all work except to communications to IPv6 function pod : 
poolmgr logs : 
```
Error: 500: Post http://1404:f600:f::0:e:16:d0bb:8000/: invalid URL port "404:f600:f::0:e:16:d0bb"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/408)
> Prepare Fission for IPv6 uses

- glide.lock
Last two travi-ci builds failed due to glide unable to check out github.com/dsnet/compress version. This PR update the dsnet/compress and gorilla packages version in glide.lock to fix the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/429)
> Fix glide failed to check out github.com/dsnet/compress

- executor/fscache/functionServiceCache.go
- executor/fscache/functionServiceCache_test.go
- executor/poolmgr/gp.go
Addresses #415
In poolmgr backend fsvc could store only one Kubernetes object, but newdeploy backend created three objects for a function (Deployment, Service, HPA). This PR adds support for storing multiple Kube objects in FuncSvc. As a side effect, the DeleteByKubeObject does not work very well so this PR also adds a new DeleteOld implementation and changes the ListOld implementation a bit. Finally all these changes impact the generic pools idlePodRepaer hence that has been changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/435)
> Fscache support for multiple kubernetes objects

- environments/python/server.py
- test/test_utils.sh
This PR aims to fix python environment failed to launch problem.
```
2018-01-20 10:09:15,137 - INFO - Starting server
Traceback (most recent call last):
File "server.py", line 98, in <module>
app.run(host='0.0.0.0', port='8888')
File "/usr/lib/python3.5/site-packages/flask/app.py", line 843, in run
run_simple(host, port, self, **options)
File "/usr/lib/python3.5/site-packages/werkzeug/serving.py", line 733, in run_simple
raise TypeError('port must be an integer')
TypeError: port must be an integer
```
Also, fix `no such file or directory` when trying to execute `helm_setup` and helm_uninstall_fission` problems in test script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission …
> Fix python environment failed to launch

- builder/builder.go
- cache/cache.go
- crd/client.go
- crd/crd_test.go
- environments/fetcher/fetcher.go
- executor/executor_test.go
- executor/fscache/functionServiceCache.go
- executor/poolmgr/gp.go
- fission-bundle/main.go
- router/functionHandler.go
- storagesvc/client/storagesvc_test.go
use time.Since instead of time.Now().Sub
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/449)
> use time.Since instead of time.Now().Sub

- fission/function.go
This PR aims to fix issue https://github.com/fission/fission/issues/428 when a user tries to create a function with a non-existed environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/436)
> Show warning when user tries to create a function with a non-existed environment

- examples/python/guestbook/add.py
By default, flask turns redirects into absolute URLs. This is
undesired behaviour on Kubernetes, because the Pod's own IP address is
not really useful to any client that's not in the cluster (and even
within the cluster most clients will want to use the address of a
Service, not a Pod).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/467)
> Fix broken redirect in python example

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- test/test_utils.sh
The test code was combining the fluentd image name and tag into a single argument when passing to `helm_install_fission" procedure like this: `$fluentdImage:$fluentdImageTag`
This worked fine until #462, after which resulting fluentd image url during tests looked like:
`gcr.io/fission-ci/fluentd:test:test` causing test failures for PRs. Helm logs show that logger could not start:
```
[kube] 2018/01/31 08:30:25 Pod is not ready: f-1ef641/logger-92lgf
[kube] 2018/01/31 08:30:29 Pod is not ready: f-1ef641/logger-92lgf
[tiller] 2018/01/31 08:30:29 warning: Release "1ef641" failed: timed out waiting for the condition
[storage] 2018/01/31 08:30:29 updating release "1ef641.v1"
[tiller] 2018/01/31 08:30:29 failed install perform step: release 1ef641 failed: timed out waiting for the condition
``` …
> Fluentd image tag issue in tests - an additional tag was appended

- .travis.yml
Fission-bundle is not able to build once the dependencies version of `k8s.io/apiextensions-apiserver` and `k8s.io/apimachinery` in glide.lock are upgraded.
Build logs:
```
$ go build
../crd/client.go:70:58: cannot use config (type *"github.com/fission/fission/vendor/k8s.io/client-go/rest".Config) as type *"github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/client-go/rest".Config in argument to clientset.NewForConfig
../crd/crd.go:35:115: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions in …
```
> Add glide flag to strip nested vendor

- fission/spec.go
Go vet logs
```
$ ./hack/verify-govet.sh
./fission/spec.go:431: the pkgWatchCancel function is not used on all paths (possible context leak)
./fission/spec.go:473: this return statement may be reached without using the pkgWatchCancel var defined on line 431
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/483)
> Fix possible context leak problem

- charts/fission-all/templates/deployment.yaml
This change removes the artificial limit in place for the number channels that NATS streaming defaults to. We need this because we use this deployment of NATS streaming for Fission Workflows - creating channels to group events of workflow invocations together. Unfortunately, channels are not yet deletable in NATS Streaming (though they are working on it), which causes us to hit this limit eventually. Performance-wise there does not seem to be a performance impact going beyond this default limit.
For details on the arguments see https://hub.docker.com/_/nats-streaming/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/482)
> Removed limit on max number of channels in NATS Streaming deployment

- fission/spec.go
Fix potential nil pointer problem when both watchResources and waitForBuild are equal to false.
I moved L431 out of if condition, it's more clean and easy to understand.
https://github.com/fission/fission/blob/fe9453a92eec70ff63dd38166da84e7d85c7381e/fission/spec.go#L427-L433
https://github.com/fission/fission/blob/fe9453a92eec70ff63dd38166da84e7d85c7381e/fission/spec.go#L443-L446
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/485)
> Fix potential nil pointer problem

- environments/binary/server.go
Subpackage k8s.io/client-go/pkg/api/v1 is no longer exist in HEAD.
(https://github.com/kubernetes-incubator/external-storage/issues/324)
For now, just duplicate the FunctionLoadRequest struct like what go environment did.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/487)
> Fix binary environment build failure due to package not found

- .gitignore
- Makefile
- charts/README.md
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/secrets.yaml
- charts/fission-all/templates/svc.yaml
- charts/fission-all/values.yaml
- fission-bundle/Dockerfile
- fission/main.go
- fission/mqtrigger.go
- glide.lock
- glide.yaml
- mqtrigger/messageQueue/asq.go
- mqtrigger/messageQueue/asq_test.go
- mqtrigger/messageQueue/messageQueue.go
These commits implement support for consuming messages from an Azure storage queue to trigger Fission functions.
Implemented:
* Helm chart modified to allow the MQTM to be configured for consuming Azure storage queues instead of NATS (see updated README for details).
* Modified the MQTM to support the `azure-storage-queue` option.
* Implemented a message queue provider that consumes messages from an Azure storage queue.
* Automatic retry (up to three attempts currently) implemented for failed invocations.
* Automatic moving of messages causing failure to a "poison" queue; this is similar to what Azure Functions does for failed messages.
* Added a root Makefile with the following targets:
* `test` - Runs all tests in the repo.
* `build` - Builds both the client and server (bundle) …
> Implement support for Azure storage message queue triggers

- .travis.yml
- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
- common.go
- controller/api.go
- controller/controller.go
- environments/fetcher/cmd/main.go
- environments/fetcher/fetcher.go
- executor/api.go
- executor/executor.go
- executor/poolmgr/gp.go
- router/httpTriggers.go
- router/router.go
- storagesvc/storagesvc.go
- storagesvc/stowClient.go
- test/build_and_test.sh
- test/test_utils.sh
- test/tests/test_archive_pruner.sh
- test/tests/test_backend_newdeploy.sh
- test/tests/test_backend_poolmgr.sh
- test/tests/test_buildermgr.sh
- test/tests/test_function_update.sh
- test/tests/test_internal_routes.sh
- test/tests/test_logging/test_function_logs.sh
- test/tests/test_node_hello_http.sh
- test/tests/test_package_command.sh
- test/tests/test_pass.sh
- test/tests/test_secret_cfgmap/test_secret_cfgmap.sh
This PR is for https://github.com/fission/fission/issues/472
1. Readiness and liveness probes are added to most fission containers, along with corresponding `healthz` http handlers.
2. A signal Handler for SIGTERM (used by liveness probe to restart containers) is added to most fission containers so we have enough information to debug issues. 
(I found that the above 2 helped troubleshoot/get rid of most of the `getsockopt` errors in my CI runs.)
4. For helm install failures,  `kubernetes events` and `tiller logs`( of previous 30 minutes ) are added to the CI logs.
5. Helm install timeout has been changed from 10 minutes to 9 minutes to prevent travis from killing the build script before dumping all logs and objects.( this because travis has a build timeout of 10 minutes too)
3. Added …
> CI modifications

- builder/cmd/build.sh
- environments/fetcher/cmd/build.sh
- environments/go/builder/Dockerfile
- fission-bundle/build.sh
- hack/release.sh
This PR adds the step for releasing env builder image and build flags to remove $GOPATH in go binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/494)
> Improve release script

- executor/newdeploy/newdeploy.go
- executor/poolmgr/gp.go
- executor/util/util.go
This PR adds default resources for Fetcher pod for both executors - pool manager and new deployment (And fixes #478 ). Currently, the resource numbers are based on experimentation. In future maybe we could look at the numbers from monitoring (Prometheus?)
Also, the getFetcherResources method is duplicated in both executors. On one hand, I wanted different fetcher resources for both but also wanted to avoid code duplication. I can not move the method up at executor level as it will cause cyclical dependency of packages, maybe create a util package within executor and then import in both executors?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/500)
> Adds default resources for fetcher pod

- executor/cleanup.go
- executor/poolmgr/gpm.go
- types.go
This fixes the compatibility part of the issue #506. There are two things that had to be done to make this work in a correct way:
- Add a check that if `env.Spec.Version < 3` then default `poolsize` to 3
- Since we changed the name from `poolmgrInstanceId` to `executorInstanceId` - we had to add a check for previously created deployments etc. to be cleaned up. Technically this is one time activity after upgrade and can be done manually - so can remove if that is what we conclude to do. Or we can leave for 2 releases and then remove it.
The testing that is done to prove that change works is described below:
**Install Helm**
```helm install --name fission --namespace fission https://github.com/fission/fission/releases/download/0.4.1/fission-all-0.4.1.tgz```
**Create environment & verify** …
> Fixes the backward compatibility with older environment versions

- Documentation/docs-site/content/tutorial/enabling-istio-on-fission.md
- Documentation/docs-site/content/tutorial/istio-integration.md
- builder/client/client.go
- buildermgr/buildermgr.go
- buildermgr/common.go
- buildermgr/envwatcher.go
- buildermgr/pkgwatcher.go
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/post-install-job.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/templates/post-install-job.yaml
- charts/fission-core/values.yaml
- common.go
- controller/api.go
- controller/functionApi.go
- crd/crd.go
- environments/fetcher/client/client.go
- environments/fetcher/cmd/main.go
- executor/fscache/functionServiceCache.go
- executor/newdeploy/newdeploy.go
- executor/newdeploy/newdeploymgr.go
- executor/poolmgr/gp.go
- executor/poolmgr/gpm.go
- fission/environment.go
- fission/main.go
- mqtrigger/messageQueue/messageQueue.go
- router/mutablemux.go
- timer/timerSync.go
- types.go
This is the very first step for fission to integrate with Istio and there are still couple problems need to be solved. For those  interested in trying integrate fission with istio, following is the set up tutorial (Tutorial also post on [here](https://tachingchen.com/blog/fission-and-istio-integration/)). (https://github.com/fission/fission/issues/278, https://github.com/fission/fission/issues/344) 
* Google Kubernetes Engine: 1.8.4-gke.0
Enable both RBAC & initializer features on kubernetes cluster.
** NOTICE ** `kubectl logs -f` is [not working correctly](https://github.com/kubernetes/kubernetes/issues/54205#issuecomment-340111607) on GKE alpha cluster right now.
```
$ gcloud container clusters create istio-demo \
--enable-kubernetes-alpha \
--machine-type=n1-standard-2 \
--num-nodes=1 …
```
> Istio integration

- Documentation/docs-site/content/installation/installation.en.md
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/svc.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/templates/svc.yaml
- fission/function.go
- fission/main.go
- fission/portforward.go
This makes set up easier for new users.  Users can still set
FISSION_NAMESPACE but it will default to "fission".  Users can also
still set KUBECONFIG, but it will default to $HOME/.kube/config.
Also, update the post-install chart notes.txt and the install guide to
use "fission function test" as the first step after install.  This
means that if there's anything wrong with the setup, the user will see
useful errors instead of "internal server error".  Also, they can test
their setup without worrying about nodeports or ingresses or whatever.
All existing functionality of FISSION_URL and FISSION_ROUTER continues
to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/518)
> Default values for FISSION_* env vars

- fission/main.go
- fission/portforward.go
This PR removes the hard coded default "fission" namespace that I added in the last PR, replacing it with some logic to figure out where fission is installed and connecting to it.  If there is more than one fission install, error out with a useful message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/519)
> Detect fission namespace in cli

- executor/poolmgr/gp.go
Istio-proxy may return error HTTP code (e.g. 404) or block connection before new config is populated.
So always retry when istio is enabled.
```
2018/03/08 07:39:54 [hello] specializing pod
2018/03/08 07:39:54 Failed to specialize pod: Post http://istio-hello-default.fission-function:8888/specialize: read tcp 10.60.1.52:57034->10.63.240.45:8888: read: connection reset by peer
2018/03/08 07:39:54 Error in pod 'nodejs-b8854294-22a1-11e8-b17e-42010af001a7-1rtgetlj-867cfwr6bt', scheduling cleanup
2018/03/08 07:39:54 Error: 500: Post http://istio-hello-default.fission-function:8888/specialize: read tcp 10.60.1.52:57034->10.63.240.45:8888: read: connection reset by peer
127.0.0.1 - - [08/Mar/2018:07:39:54 +0000] "POST /v2/getServiceForFunction HTTP/1.1" 500 143
```
---
This change is [<img …
> Always retry when istio is enabled.

- builder/builder.go
- builder/cmd/build.sh
- builder/cmd/main.go
- controller/api.go
- environments/fetcher/cmd/build.sh
- environments/fetcher/cmd/main.go
- environments/fetcher/fetcher.go
- fission-bundle/build.sh
- fission-bundle/main.go
- fission/main.go
- hack/release.sh
- version.go
Set fission version through go `ldflags`. Following is the command output. (https://github.com/fission/fission/issues/362)
```
$ fission --version
Client Version: {"GitCommit":"84bf6d32ed9eccba48f0016fecc3bec94a47f043","BuildDate":"2018-03-08T15:54:56Z","Version":"test"}
Server Version: {"GitCommit":"81db94f3db335efbc209994b5bdaaafde4f9cec5","BuildDate":"2018-03-08T16:23:48Z","Version":"dummy-version"}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/538)
> Show fission deployment version with cli

- fission/function.go
The warning should not be given when updating to new deploy executor type, as the warning is only applicable for pool manager type of functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/545)
> Fixes #537 - warning should not be given when updating to newdeploy

- Compiling.md
- Makefile
- buildermgr/envwatcher.go
- common.go
- controller/api_test.go
- executor/newdeploy/newdeploy.go
- executor/poolmgr/gp.go
- glide.lock
- glide.yaml
- merge_test.go
- test/run_test.sh
- test/test_utils.sh
- test/tests/test_env_vars.sh
- types.go
~This PR adds the ability to add environment variables to (build) environments.~
~To keep the spec api consistent with the Kubernetes api, I choose to follow the EnvVar approach taken there using a `env` field in the object.~
~I created a separate EnvVar implementation, because I did not want to introduce a dependency on kubernetes types in the fission types, but I am open to change that. (your thoughts on this @soamvasani ?)~
This PR adds the ability for users to provide a template/container to influence the deployment of the containers. The current motivation behind this is to allow the setting of environment variables in the runtime environment containers.
I have been testing quite a bit (due to the incompatible client issue), and in the process added a script to run a single e2e test …
> Add container spec config options  to (build) environments

- charts/fission-core/templates/deployment.yaml
The Deployment definition for executor, controller, router contains readines/liveness probes. The port definition for those probes should be numbers, instead of string, i.e. port: "8888" should be port 8888.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/563)
> This change fixes an error in a yaml file in the fission-core chart.

- fission/function.go
- fission/logdb/influxdb.go
There were two problems with `fission fn logs` implementation on client side:
1. In case of error, it was returning null so user feedback was missing that there is an error in getting logs
2. After port forward implementation, the proper way to get server URL was missing in `GetLogDB`
That was the reason that test_function_log.sh was failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/587)
> Uses proper way to get server URL

- fission/spec.go
Here the flag name should be `specdir`, not `specs`, that should match to:
```go
specDirFlag := cli.StringFlag{Name: "specdir", Usage: "Directory to store specs, defaults to ./specs"}
```
in fission/main.go
Currently it cause the specific specs dir not to work.
```
$ fission spec apply --specdir <my spec dir>
Everything up to date.
```
Signed-off-by: xiekeyang <keyang.xie@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/595)
> bug fix: spec dir flag

- fission/spec.go
- glide.lock
- glide.yaml
This change implement a first cut of `fission spec validate`.  It implements basic checks for duplicate resources, dangling references, and unused resources.  These checks can be extended in the future to add warnings around best practices and so on.
It also collects all errors before exiting, so the the user can fix more errors before re-running `fission spec`.  
The validator is also called during `fission spec apply`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/560)
> Spec validator, better errors, apply waits for previous build 

- fission/function.go
- fission/main.go
Add the deprecated message to subcommand `pod` and remove it in next the realease. So that users have time to migrate existing scripts. #590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/592)
> Add deprecated message to subcommand pods

- buildermgr/buildermgr.go
- controller/controller.go
- crd/client.go
- crd/crd.go
- executor/executor.go
- executor/executor_test.go
- kubewatcher/main.go
- mqtrigger/main.go
- router/router.go
- timer/main.go
Some of the components use listwatch to watch CRDs changes. The component pod will enter crash state if it starts before CRDs exist.
```
2018/04/03 09:17:28 Creating NewDeploy ExecutorType
2018/04/03 09:17:28 starting executor at port 8888
E0403 09:17:28.388019       1 reflector.go:201] src/github.com/fission/fission/executor/newdeploy/newdeploymgr.go:142: Failed to list *crd.Function: the server could not find the requested resource (get functions.fission.io)
2018/04/03 09:17:28 Failed to get environment list: the server could not find the requested resource (get environments.fission.io)
```
This PR tends to solve this problem by adding `WaitForCRDs` to components startup process. Also, fix `ensureCRD` return nil while the error may not be empty. …
> Fix components crash before crds creation

- common.go
- controller/api_test.go
- controller/client/environment.go
- controller/client/function.go
- controller/client/httptrigger.go
- controller/client/kuberneteswatchtrigger.go
- controller/client/mqtrigger.go
- controller/client/package.go
- controller/client/timetrigger.go
- controller/crd.go
- controller/environmentApi.go
- controller/functionApi.go
- controller/httpTriggerApi.go
- controller/mqTriggerApi.go
- controller/packageApi.go
- controller/timeTriggerApi.go
- controller/watchApi.go
- crd/types.go
- fission/httptrigger.go
- fission/main.go
- fission/migrate.go
- fission/mqtrigger.go
- fission/upgrade.go
- mqtrigger/messageQueue/asq_test.go
- mqtrigger/messageQueue/messageQueue.go
- types.go
- validation.go
Right now we have at least two ways to create fission resource: a) fission CLI b) spec YAML, which means that we need to write validate function in multiple places. 
That caused some problems:
1. Duplicate work to check field values in the different place
2. No unified error format
This PR tends to solve this problem by adding `Validate()` function to each fission object, and the function will be invoked before any resource creation/update. Also, add a new error message format which looks like following:
```
Failed to create HTTP trigger: Invalid fission HTTPTrigger object:
* FunctionReference.Name: Invalid value: findped.ts: [a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', …
```
> Add validate function to crd resource and do validate before creation/update

- README.md
It looks like at some point these readme links got out of sync with the website url schema. This PR fixes some of those links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/628)
> Update readme to point to the proper link

- buildermgr/pkgwatcher.go
This PR aims to fix https://github.com/fission/fission/issues/572 .
Build manager use the same variable to store function (`updatePackage`) return value, which is nil pkg pointer if the function failed to update package. And builder manager tries to print pkg information with that nil pointer.
Rename function parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/626)
> Fix buildmgr SEGFAULT when it failed to update package

- logger/fluentd/fluent.conf
Notice some logs get lost if set time_precission to second, change it to nanosecond can mitigate the failure problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/646)
> Change time precision for fluentd influxdb plugin to nano second

- executor/newdeploy/newdeploymgr.go
Newdeploy backend does not delete function related kubobject after the function was deleted.
GetByFunction uses resource version as part of cache key, however, the resource version in function metadata will be changed when a function is deleted and cause newdeploy backend fails to delete the entry. 
Use GetByFunctionUID instead of GetByFunction here to find correct fsvc entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/657)
> Fix newdeploy backend failed to delete deployment due to incorrect resource version

- buildermgr/envwatcher.go
- executor/cleanup.go
- executor/poolmgr/gp.go
1. Migrate DeleteOptions `OrphanDependents` to `PropagationPolicy`. 
2. Remove legacy code (workaround) for old k8s version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/630)
> Delete deployment with proper delete propagation policy

- environments/python/Dockerfile
- environments/python/Dockerfile-2.7
- environments/python/requirements.txt
- environments/python/server.py
Werkzeug as underlying WSGI server of Flask is not suitable for serving high load traffic. After some research and end up using Bjoern as the alternative. The performance graph will be attached later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/672)
> Replace Werkzeug  with Bjoern as underlying WSGI server

- glide.lock
@soamvasani @erwinvaneyk  This is to fix the issues with Windows development discussed in Slack, specifically to address the folder shown here https://github.com/docker/distribution/tree/cd27f179f2c10c5d300e6d09025b538c475b0d51/contrib/docker-integration/generated_certs.d , which contains several files with colons in the file names. The effect of that is that git is unable to pull the entire repo due to an error being thrown by Windows on the attempted file creation. The folder is removed in commit sha db713e127ba35bd15595113df56ee964de24637a, with differences between the commits shown here https://github.com/docker/distribution/compare/cd27f179f2c10c5d300e6d09025b538c475b0d51...db713e127ba35bd15595113df56ee964de24637a . I think it's worth bringing up the question of whether a larger …
> docker-distribution version bump for windows compatibility

- controller/storagesvc.go
- controller/workflowApiProxy.go
- environments/binary/server.go
- environments/fetcher/fetcher.go
- error.go
- executor/api.go
- fission/migrate.go
- fission/upgrade.go
- mqtrigger/messageQueue/asq_test.go
- storagesvc/storagesvc.go
It had better to indicate HTTP status code by library const name, instead hard number.
Signed-off-by: xiekeyang <keyang.xie@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/703)
> Indicate HTTP status code by library const

- examples/spec-example/hello/build.sh
- examples/spec-example/specs/env.yaml
- fission/spec.go
`filepath.Walk` does nothing if spec directory does not exist
1. Use `os.Stat` to check spec directory exists before reading spec files
2. Fix spec example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/709)
> Check spec directory exists before reading spec files

- charts/fission-all/templates/deployment.yaml
The default update strategy for DaemonSet is `OnDelete` (Meaning the user has to go and manually delete the pod). This has been the default strategy and is still there for backward compatibility. We should instead switch to `RollingUpdate` so that users don't have to intervene in case logger changes.
https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/714)
> Logger daemonset's update strategy

- builder/builder.go
- controller/api.go
- controller/client/client.go
- environments/fetcher/fetcher.go
- fission-bundle/main.go
- fission/main.go
- fission/timetrigger.go
- info.go
Address #678 
1. Add time trigger spec examination tool
```
$ fission tt create --name h4 --function h1 --cron "@every 30m"
trigger 'h4' created
Current Server Time:    2018-05-29T16:19:52Z
Next 1 invocation:      2018-05-29T16:49:52Z
```
2. Show next invocation time when creating/updating time trigger
```
$ fission tt test --cron "@every 5s" --round 5
Current Server Time:    2018-05-29T16:20:50Z
Next 1 invocation:      2018-05-29T16:20:55Z
Next 2 invocation:      2018-05-29T16:21:00Z
Next 3 invocation:      2018-05-29T16:21:05Z
Next 4 invocation:      2018-05-29T16:21:10Z
Next 5 invocation:      2018-05-29T16:21:15Z
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/680) …
> Add time trigger cron spec examination tool

- controller/packageApi.go
This use constant to instead hard code for ArchiveLiteralSizeLimit. That ensure if the limitation
value is changed in cli, the controller server can follow it. Otherwise, the condition will return
error, and make error HTTP response.
Later, we should delete it in fission-cli, and make it configurable it chart, to work in fission-
servers only.
Signed-off-by: xiekeyang <keyang.xie@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/731)
> ArchiveLiteralSizeLimit: Use Constant Instead Hard Code

- fission/environment.go
This simplifies the message when there are multiple environments in the same namespace.  It also moves it into the verbose category.  Otherwise we'd see it too often, I think.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/725)
> Environment warning message bugfix

- router/httpTriggers.go
When investigating issues 695, found the bug in router. The reference of loop variable was being passed to function. (Not the root cause of 695)
https://github.com/fission/fission/blob/1ab1c3264ec8b68f4da225bef51db4ffe17c5659/router/httpTriggers.go#L112
https://github.com/fission/fission/blob/1ab1c3264ec8b68f4da225bef51db4ffe17c5659/router/httpTriggers.go#L127
And wrong metrics data will be collected.
https://github.com/fission/fission/blob/1b86c367a04aa07f0bedea96786201fe1948b164/router/functionHandler.go#L89-L92
Get reference from slice element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/751)
> Fix executor wrongly passes loop variable reference to function

- router/functionHandler.go
- test/tests/test_fn_update/test_configmap_update.sh
- test/tests/test_fn_update/test_nd_pkg_update.sh
- test/tests/test_fn_update/test_secret_update.sh
This fix tries to address final finding from the issue https://github.com/fission/fission/issues/723 (The issue with router caching the POD IP address: https://github.com/fission/fission/issues/723#issuecomment-395952964 )
As can be seen from builds for commit - with the fix the tests pass and without it, they fail. Of course, the impact of this on the performance etc. is not clear here. Also, this issue has been seen only in CI cluster so far.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/742)
> Testing with keep alive settings for connections

- controller/packageApi.go
- glide.lock
- glide.yaml
`ArchiveLiteralSizeLimit` has constant value. When encountering the package error here, we should warn the exact `ArchiveLiteralSizeLimit` value, but not `256KB` hard code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/735)
> instead hard code by variable in error message

- fission/function.go
This line warn customer that dependent environment doesn’t exist, and present the command line
how to create env.
For variable `envNamespace` is specified, here the `envns` option should be available as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/734)
> envns should be availabe in message line

- environments/go/Dockerfile
Converting to a multi-stage build reduces the size of the final image from ~750MB to ~15MB.
Fixes #624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/683)
> Convert go-env Dockerfile into a multi-stage build

- buildermgr/envwatcher.go
- executor/newdeploy/newdeploy.go
- executor/poolmgr/gp.go
- pkg/apis/fission.io/v1/typefields.go
- test/tests/test_annotations.sh
Annotations are pretty often used to augment or trigger some external service for a given pod. For example, we annotate our environment pods for Istio. To avoid having to add this manually in the source code, I propose that we provide the ability to the users to alter the annotations of an environment. These user-provided annotations are used in both the runtime and the builder pod of the environment. 
We could also expose the entire PodSpec, but I am not sure if (1) that makes things more convenient for users (2) that might open up a range of non-standard/untested behaviour when users can alter everything of the pod template. So instead I now went for the option to just add the annotations map to the environmentspec (but I am not particularly in favor or against any of the two options). …
> Support annotations in environment specs

- .travis.yml
- router/functionHandler.go
This solves the bug that causes the issue https://github.com/fission/fission/issues/641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/701)
> Router liveness

- environments/dotnet/Dockerfile
- environments/dotnet/build.sh
- environments/dotnet20/Dockerfile
- environments/dotnet20/build.sh
- hack/Dockerfile
- hack/release-build.sh
- hack/release.sh
The major changes of this PR are following
1. Move all build process to docker container while the release process remains the same to prevent host environment ($GOPATH...e.g) pollute binaries
2. Use multi-stage build to build dotnet* image
3. Copy charts automatically to chart repo in the end of release process
In future, we can move whole release steps in container as well for release automation.
(The docker image `fission/release-builder` will be push to dockerhub once the change of PR is confirmed.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/682)
> Move build process from host to docker container during release process

- buildermgr/common.go
- environments/fetcher/fetcher.go
- executor/newdeploy/newdeploy.go
- executor/poolmgr/gp.go
- fission/environment.go
- fission/main.go
- pkg/apis/fission.io/v1/typefields.go
- test/tests/test_environments/test_java_env.sh
A new flag `ExtractArchive` was adopted In 0.9.0, which is used by fetcher to see whether a archive needs to extract or not. However, if an environment was created with old CLI the value will be false due to golang default value for the empty field and make the breaking change.
Rename the flag for backward compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/787)
> Change flag name to KeepArchive for backward compatibility

- hack/release-build.sh
1. Fix “rm: missing operand” in release script
2. Remove duplicate build step
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/779)
> Fix “rm: missing operand” in release script

- .travis.yml
Sometimes the build is failed due to a non-zero exit code was returned in the early stage, however, the build keeps running and still failed in the end. This behavior costs lots of time to wait for the build result.
Follow the instruction here: https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build
`If before_install, install or before_script returns a non-zero exit code, the build is errored and stops immediately.`
Move some of script from `scripts` to `before_script` stage so that minor problems can be found before long running build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/790)
> Break & Stop the build immediately if a non-zero exit code was returned

- environments/go/builder/Dockerfile
- environments/go/builder/build.sh
- examples/go/vendor-example/main.go
- examples/go/vendor-example/vendor/go/vendordir/test/test.go
- test/tests/test_environments/test_go_env.sh
For now, vendor directory only works under `$GOPATH/src`.  With this PR, the go builder will first copy `SRC_PKG` to `${GOPATH}/src/<pkg_name>` and change work directory then do build process.
```
$ ls
total 656
-rw-r--r--@ 1 taching  staff   781B Jun 26 16:47 README.md
-rw-r--r--@ 1 taching  staff   2.1K Jul  2 18:01 accountFn.go
-rw-r--r--@ 1 taching  staff   2.5K Jul  2 16:54 accountFn_test.go
-rw-r--r--@ 1 taching  staff   288K Jul  4 16:08 bank.zip
-rw-r--r--@ 1 taching  staff   986B Jun 27 18:17 common.go
-rw-r--r--@ 1 taching  staff   698B Jul  2 16:58 glide.lock
-rw-r--r--@ 1 taching  staff   253B Jul  2 16:58 glide.yaml
-rw-r--r--@ 1 taching  staff   188B Jul  2 18:01 main.go
-rw-r--r--@ 1 taching  staff   318B Jun 27 17:52 types.go
drwxr-xr-x@ 3 taching  staff    96B Jul  2 …
```
> Add go environment vendor directory support

- buildermgr/envwatcher.go
This changes image pull policy from `Always` to `IfNotPresent`. The previous
policy forbid customer to use the exact image existing on K8S Node.
And it should be OK to use fixed policy here. Customer need not set policy by
their own.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/793)
> change image pull policy of builder manager

- fission/function.go
- fission/main.go
This PR adds `--query, -q` options to the (already very useful) `function test` subcommand. I choose to use the `net/url` package for creating the url to avoid having to deal with query escaping and all that. Regardless of the query addition, using that package seems safer to detect invalid urls earlier.
The reason that I added it is that it would useful to have in the workflows CI, and that we (in my opinion) should not ignore these (query) settings which are common practice for REST-based APIs.
Resolves #401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/782)
> Add query options to `fission function test`

- executor/executor.go
- executor/poolmgr/gp.go
Router sends requests to executor to get service for function, however, exectuor replies error without some useful information/message. This PR appends message/information to error message to provide more clues when debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/752)
> Add more meaningful error messages to executor when getServiceForFunction

- fission/function.go
- fission/main.go
- fission/package.go
Currently, CLI doesn't have a convenient way to retry on a failed package. You have to update one of flag to trigger build process. That's really not an ideal way for retrying failed package.
This PR add `retry` subcommand to `pkg` command, it helps user to do retry without updating anything. 
Turn this
```
$ fission pkg update --name restapi-go-pkg --env go
```
into this
```
$ fission pkg retry --name restapi-go-pkg
Set package 'restapi-go-pkg' to pending state
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/808)
> Add retry subcommand to pkg command

- executor/client/client.go
Notice router no longer sending tapping requests to the executor. This PR fixes the problem and also handles the error returned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/860)
> Fix router not taps function services

- common.go
- executor/poolmgr/gp.go
Notice there is an issue(https://github.com/kubernetes/kubernetes/issues/61376) indicates that `status.phase` of pod is in `Running` even when the pod is in `Terminating` state. 
This PR aims to resolve the problem to prevent the terminating pod was selected by poolmgr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/861)
> Check pod container ready state

- test/tests/test_environments/test_java_env.sh
Making the Maven build quite for Java env test, right now it is too verbose for CI. 
Currently has 100s of lines of INFO:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< io.fission:hello-world >-----------------------
[INFO] Building hello-world 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (3.9 kB at 9.9 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded …
```
> Java env test - Maven verbosity reduction

- environments/jvm/Dockerfile
This PR solves #925 and enables providing options to JVM heap.  The heap options can be passed with spec file for environment as shown in example below:
```
apiVersion: fission.io/v1
kind: Environment
metadata:
creationTimestamp: null
name: jvm
namespace: default
spec:
TerminationGracePeriod: 360
builder: {}
keeparchive: true
poolsize: 3
resources: {}
runtime:
functionendpointport: 0
image: fission/jvm-env
loadendpointpath: ""
loadendpointport: 0
container:
env:
- name: JVM_OPTS
value: "-Xms256M -Xmx1024M"
version: 2
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/936)
> Adding JVM heap options to environment

- charts/fission-all/templates/deployment.yaml
- logger/influxdb/Dockerfile
- logger/influxdb/README.md
- logger/influxdb/config.toml
- logger/influxdb/run.sh
- logger/influxdb/types.db
- test/tests/test_environments/test_java_env.sh
The influxdb image repo(`tutum/influxdb`) fission used is no longer exists. We need to find an alternative image to fix installation failure. After some testing, the official influxdb image is not compatible with current fission deployment and require some changes. 
To fix the installation failure and backward compatibility issue, fission will maintain a copy of influxdb image until we are able to fully adopt official image.
For people encounter same problem, please replace influxdb image with `fission/influxdb`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/957)
> Fix failed to pull influxdb image from dockerhub

- environments/jvm/builder/Dockerfile
The OpenJDK version previously available seems missing from Alpine repo, so to fix upgrading to latest available version
Related change in Dokerfile of the alpine OpenJDK:
https://github.com/docker-library/openjdk/commit/47a6539cd18023dafb45db9013455136cc0bca07#diff-fe1bcb93483d1e28f57338fb56f20cef
In longer term to avoid such issues, we need to find an alternative, related issue here: https://github.com/fission/fission/issues/984
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/985)
> Alpine OpenJDK not available anymore

- executor/newdeploy/newdeploy.go
- executor/newdeploy/newdeploymgr.go
- executor/poolmgr/gp.go
- executor/util/util.go
- types.go
PR https://github.com/fission/fission/pull/182 is a little bit old, create a new one instead.
The field `GenerateName` will cause newdeploy not able to find the correct hpa, svc and deploy to update/delete due to 3 resource's suffix are different. 
Since the original purpose of the PR is to shorten the name of deployment, so use `Name` but without `gp.env.Metadata.UID` in pool deployment name. Also, add environment information to annotation for troubleshooting when dumping the CRDs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/975)
> Shorten poolmgr deployment name

- environments/python/requirements.txt
- environments/ruby/Gemfile.lock
Two security alerts for environment dependencies
1. https://github.com/fission/fission/network/alert/environments/ruby/Gemfile.lock/rack/open
2. https://github.com/fission/fission/network/alert/environments/python/requirements.txt/requests/open
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1006)
> Upgrade environment dependencies for security alert

- executor/newdeploy/newdeploy.go
- fission/environment.go
- fission/function.go
- fission/function_test.go
- fission/log/log.go
- fission/main.go
- pkg/apis/fission.io/v1/validation.go
To fix part of https://github.com/fission/fission/issues/955 (minscale to 1) and some other issues when specifying resources/scales during updating/creation process.
1. default minscale to 1
2. fix failed to update min/max resources in one time.
3. fix user can create env with improper req/limits resource.
4. add `[FATAL]` to CLI log message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/970)
> Fix issues when specifying resources/scales during updating/creation process

- executor/newdeploy/newdeploymgr.go
- executor/poolmgr/gp.go
In some cases, the newdeploy creates multiple different name k8s objs for the same function after PR #975 .
This PR use `executor type` as a delimiter to fix the problem and also preventing the name conflict mentioned in PR975 comments.
For example:
1. fn-name: a-b fn-namespace: c => a-b-newdeploy-c
2. fn-name: a fn-namespace: b-c => a-newdeploy-b-c
Though the format is less beautiful but solves the problem without adding a random string to deploy name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1009)
> Use executor type as a delimiter to prevent deploy name conflict

- fission/main.go
Fix #1014 
```
$ fission fn create name t4
Fatal error: No valid flags are provided. Please ensure flag name has "--" prefix.
$ fission fn create --name t4 --env nodejs \
--code /github.com/fission/fission/examples/nodejs/* --minscale 0 --maxscale 4 \
--executortype newdeploy sfdfhjdhkjsdf
Fatal error: Unable to parse flags: --code, --executortype
The argument should have only one input value. Please quote the input value if it contains wildcard characters(*).
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1017)
> Validate command flag input by adding cli hook

- common.go
- fission/function.go
- fission/main.go
- fission/package.go
- fission/spec.go
- fission/upgrade.go
3 changes:
1. Archives with multiple files were being handled with only one input file (when multiple --src flags were provided)
2. Avoid creating a zip file when we don't need to
3. Check for duplicate ArchiveUploadSpecs and Package.Specs before writing them to the spec dir 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1018)
> handle duplicate archive and package specs; handle multifile archives better

- builder/builder.go
- environments/fetcher/fetcher.go
- mqtrigger/messageQueue/asq.go
- mqtrigger/messageQueue/kafka.go
- mqtrigger/messageQueue/nats.go
- publisher/webhookPublisher.go
- redis/redisApi.go
- router/functionHandler.go
- router/util.go
Header.Add() appends string if there are same header key exists. Use Header.Set() to prevent this.
Fix #1027
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1032)
> Use Header.Set() to override the existing header value

- charts/README.md
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- mqtrigger/messageQueue/kafka.go
- test/tests/mqtrigger/kafka/hellokafka.js
- test/tests/mqtrigger/kafka/kafka_pub/kafka-pub.go
- test/tests/mqtrigger/kafka/test_kafka.sh
- Add support for Kafka record headers
- This makes sure that the headers received from a function are
converted to Kafka record headers
- Also extracts the headers from a Kafka record and sends them to
function
- ref: https://issues.apache.org/jira/browse/KAFKA-4208
- Make Kafka version configurable
- Adds version field to Kafka struct
- Adds `MESSAGE_QUEUE_KAFKA_VERSION` environment variable
- Drop headers from Kafka record if specified Kafka version is `< 0.11.0.0`
- Update helm chart fission-all for Kafka record headers
- Adds new field `kafka.version`
- Sets the `MESSAGE_QUEUE_KAFKA_VERSION` environments variable to `kafka.version`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add support for Kafka record headers

- pkg/apis/fission.io/v1/validation.go
Currently, Kafka topic name validation does not allow capital case letters.
Fixes #1049
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1051)
> Changed Kafka topic name validation 

- router/functionHandler.go
- router/httpTriggers.go
- router/router.go
- router/router_test.go
- router/svcAddrUpdateLock.go
- throttler/throttler.go
Address followup comments in #991 and add new throttler package.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1047)
> Replace router svcAddrUpdateLocks with new throttler package for code readability&reusability

- executor/executor.go
- executor/poolmgr/gp.go
- fission/function.go
Fixes #952 
This is not perfect but good for review fix. There are mainly two things that need to be fixed separately:
1) Right now the error is so long is because it is wrapped and passed on at every layer. This is great for tracing error but not for the end user. The challenge is determing which part of multiple errors is most useful for users. I don't know the solution yet, but the problem statement is fairly clear.
2) Currently, we are checking one pod since none is ready - there is room for future addition!
```
$ fission fn test --name hello
Error calling function hello: 500; Please try again or fix the error: Error updating service address entry for function hello_default: Internal error - Timeout: waited too long for pod of deployment python-poolmgr-default in namespace …
```
> Clear message in case of function/pod failure

- executor/api.go
- executor/executor.go
- executor/fscache/functionServiceCache.go
- executor/newdeploy/newdeploy.go
- executor/newdeploy/newdeploymgr.go
- executor/poolmgr/gp.go
- executor/poolmgr/gpm.go
- test/tests/test_backend_newdeploy.sh
Fix #1054 
The root cause of the issue was introduced by PR https://github.com/fission/fission/pull/1009/files .
To be short, even the CRD of environment was delete, it still takes time for executor (poolmgr) to destroy env pool. So, when a user can create a same name env, following logs will be shown.
```
2019/01/08 11:01:26 Error creating deployment for nodejs-poolmgr-default in kubernetes, err: deployments.extensions "nodejs-poolmgr-default" already exists
2019/01/08 11:01:26 eager-create pool failed: deployments.extensions "nodejs-poolmgr-default" already exists
```
In our cases, the previous test creates an env and delete it when test finished, then the next one creates a same name env, but failed to create pool due to the deploy name conflict like log above. So the executor selects …
> Fix executor tries to create same name deployment

- charts/fission-all/values.yaml
- mqtrigger/messageQueue/kafka.go
- If Kafka version is < 0.11.0.0 log a warning about headers not being
passed in the HTTP request
- Update the values.yaml of fission-all helm chart with proper
explanation for specifying the Kafka broker version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1083)
> [Kafka MQT] Add warning about Kafka version

- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
As of K8s 1.8, RBAC mode is stable and backed by the rbac.authorization.k8s.io/v1
API. Using v1beta1 API version for RBAC based objects fails helm deployment
of fission on minikube
Alter ego of #477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1124)
> Change RBAC api version to v1

- fission/function.go
- fission/support/dump.go
- fission/util/portforward.go
- fission/util/util.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1126)
> support KUBECONFIG with multiple kube config files

- fission/util/portforward.go
Remove misleading log in portforward functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1134)
> Fix misleading log when setup portforward

- .travis.yml
From go release history (https://golang.org/doc/devel/release.html#go1.11)
and travis ci build history, looks like 1.11.7 and 1.11.8 contains unknown
bugs that breaks build. To avoid this, fix go version to 1.11.6 for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1154)
> Fix TravisCI go environment version to avoid go bugs

- fission/function.go
- fission/main.go
Currently the implementation of the CLI (or any Fission component) specifies any timeout on
the `fission fn test` functionality. If a user function or environment does not specify any
timeout the command will stall. Nor is there any parameter to set a timeout if the user 
wanted to. 
Besides that I propose to set a sensible default for the timeout to 30 seconds, to avoid new
users having to figure this out the hard way. The alternative could be to set the timeout to 
0 (no timeout).
For a future PR/discussion: extend this timeout parameter to a global flag, and support 
timeouts on all CLI commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1091)
> Add configurable timeout to fission function test

- environments/binary/README.md
- environments/dotnet/README.md
- environments/dotnet20/README.md
- environments/go/README.md
- environments/jvm/README.md
- environments/nodejs/README.md
- environments/perl/README.md
- environments/php7/README.md
- environments/python/README.md
- environments/ruby/README.md
I noticed that environment READMEs tend to have either no link to the examples, 
or have a link at the far bottom of the document. This PR resolves adds a direct 
link to examples of each environment near the top of the README.
I tried to keep the text consistent, but (for example for the DotNet environments) I
merged it into existing text to avoid having to spend time ensuring that the flow 
of the text is (accidentally) broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1090)
> Add links to examples for each Fission environment

- charts/fission-all/templates/fluentbit.yaml
- logger/logger.go
- logger can't create symlink because `/var/log/fission` does not exist. The test can pass because `/var/log` is a `hostPath` volume and `/var/log/fission` already exists on all nodes.
- fluentbit cannot open database `/var/log/fission/flb_kube.db`
- Use an init container to create `/var/log/fission`.
- Create `fissionSymlinkPath` if it does not exist when logger start. It's in case if the log path changed in the future or someone run logger directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1166)
> Fix the logger not working

- canaryconfigmgr/prometheusClient.go
The prometheus server may not up in a short time or a cluster doesn’t have a storage class config. Because of this, the connectivity test will increase controller initialization time and so the controller will fail at readiness probe detection. Since we don’t want to delay the time that controller comes up also canary config manager prints error log when it failed at connecting to prometheus server, I remove the connectivity test here.
Fix #1165 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1179)
> Remove prometheus server connectivity test during controller initialization

- pkg/executor/newdeploy/newdeploy.go
- pkg/executor/poolmgr/funcwatcher.go
- pkg/executor/poolmgr/gp.go
Fix #548 
Known issue: Jaeger shows <trace-without-root-span> (This may related to Istio problem.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1209)
> Fix Istio-proxy cannot collect HTTP-level information

- pkg/fission-cli/support/dump.go
I noticed that the `fission support dump` command had typos in some of the names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1239)
> Fix typo where "spec" is spelt "sepc" in some dump directories.

- pkg/error/network/error.go
- pkg/executor/client/client.go
- pkg/router/functionHandler.go
- pkg/router/httpTriggers.go
- pkg/router/router.go
- pkg/utils/utils.go
1. Fix roundtripper doesn't increase request timeout setting after each retry.
2. Fix "context canceled" problem when calling getServiceEntry due to short request timeout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1216)
> Fix roundtripper doesn't increase request timeout setting after each retry

- pkg/fission-cli/spec.go
Looks like it was caught up in the package rename search and replace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1250)
> Revert change of product name in  README

- pkg/fission-cli/main.go
- pkg/fission-cli/spec.go
Fix #1232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1249)
> Allow to set deployment config uid during initialization

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/fluentbit.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/_helpers.tpl
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
…yaml
This fix allows the empty repository tag in values.yaml file.
The changes are done in the templates of deployment and fluentbit where repository tag will be added
in the docker image name only when specified with some value in case of empty repository tag image name
contain the name of image and tag only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1259)
> Issue #1258: Allow empty repository tag in chart values.yaml

- pkg/mqtrigger/messageQueue/kafka.go
fix bug: 
funciton errorHandler use err.Error(), that will cause panic, because errors.Wrapf("request returned failure: %v", resp.StatusCode) return nil
<pre>
panic: runtime error: invalid memory address or nil pointer dereference
/go/src/github.com/fission/fission/pkg/mqtrigger/messageQueue/kafka.go:256
</pre>
@life1347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1271)
> fix a panic bug caused by err.Error()

- environments/go/server.go
The current error for v2 reports CODE_PATH instead of loadreq.FilePath
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1294)
> Update go environment errors for specializeHandlerV2

- go.mod
- pkg/apis/fission.io/v1/types.go
- pkg/apis/fission.io/v1/validation.go
- pkg/fission-cli/cmd/httptrigger/parse.go
- pkg/fission-cli/cmd/httptrigger/parse_test.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/httptrigger.go
- pkg/fission-cli/main.go
- pkg/router/ingress.go
- pkg/router/util/util.go
- pkg/router/util/util_test.go
- test/test_utils.sh
- test/tests/test_ingress.sh
- test/utils.sh
For each ingress controller, the format of ingress host, path and annotations are different.
To support different kinds of controller, this PR adds new ingress config field to http trigger spec.
A user can set annotations, host and path based on the type of underlying ingress controller with CLI.
Command example:
```
fission route create --name foo \
--url /foo/{bar} --function foofn --createingress \
--ingressannotation "nginx.ingress.kubernetes.io/ssl-redirect=false" \
--ingressannotation "nginx.ingress.kubernetes.io/use-regex=true" \
--ingressrule "*=/foo/*"
```
Fix #989 #1323 #1158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1325)
> Add Ingress host, path and annotations support

- pkg/apis/fission.io/v1/types.go
- pkg/fission-cli/cmd/httptrigger/parse.go
- pkg/fission-cli/cmd/httptrigger/parse_test.go
- pkg/fission-cli/httptrigger.go
- pkg/fission-cli/main.go
- pkg/router/util/util.go
- pkg/router/util/util_test.go
- test/tests/test_ingress.sh
This PR aims to add the Ingress TLS support by specifying the
TLS secret when creating/updating the HTTP trigger.
Command example:
```
fission route create --name foo \
--url /foo/{bar} --function foofn --createingress \
--ingressannotation "nginx.ingress.kubernetes.io/ssl-redirect=false" \
--ingressannotation "nginx.ingress.kubernetes.io/use-regex=true" \
--ingressrule "*=/foo/*"
--ingresstls "foobartls"
```
Fix #1046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1326)
> Add Ingress TLS support

- pkg/fission-cli/httptrigger.go
- pkg/fission-cli/main.go
Previously, a user has to delete HTTP triggers point to the same function one by one. This PR adds new flag --function to list & delete commands. So that user can delete or list all triggers with the same function. However, this feature is not working for triggers with canary deployment setup.
Fix #1327 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1327)
> List/Delete HTTP triggers by function

- examples/go/specs/env.yaml
- examples/go/specs/function-hello.yaml
- pkg/fission-cli/spec.go
Previously, the spec doesn't update the package status if nothing
in the spec file changed. Due to this, the failed package will
always stay in the failed state.
This PR adds a check to see whether a package is in the failed state.
If yes, then changes the state to pending for builder manager to rebuild it.
Fix #1092
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1332)
> Fix spec doesn't update status of failed package when applying spec files

- pkg/router/functionHandler.go
- pkg/router/functionHandler_test.go
- test/tests/test_function_timeout.sh
Fix #1302 
The router prints error no matter what error type it is. It's useful for troubleshooting, however, it also prints the `context canceled` error, which means that users abort request before reply and its really normal nowadays. Also, the router returns 502 if error is not nil and may confused client if it's a timeout error.
To solve these problems, this PR adds an error handler to reverse proxy to examine the return error and change the status code when needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1310)
> Use ErrorHandler to handle proxy error

- pkg/router/httpTriggers.go
Router readiness probe failed due to kubelet cannot find router healthz endpoint.
This is caused that the healthz endpoint is added only when there is any update request
send to the updateRouterRequestChannel, and makes router failed.
This PR sends an update request right before the router is started to avoid the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1333)
> Fix router health route not found if no HTTP triggers created

- pkg/apis/fission.io/v1/types.go
- pkg/buildermgr/common.go
- pkg/fission-cli/package.go
This change fixes https://github.com/fission/fission/issues/1093
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1334)
> package will now be listed, sorted by lastupdatedtime

- hack/runtests.sh
- pkg/buildermgr/envwatcher.go
- pkg/executor/newdeploy/newdeploy.go
- pkg/executor/poolmgr/gp.go
- pkg/executor/util/merge.go
- pkg/executor/util/merge_test.go
The merge function executor used wasn't merge container correctly, and it
didn't merge all fields in spec except volumeMount & Env which confused people.
To apply user-configured container correctly, this PR changes the way of merge
and follows rules:
1. Slices are merged, and return an error if the elements in the slice have name conflicts.
2. Maps are merged, the value of map of dst container are overridden if the key is the same.
3. The rest of fields of dst container are overridden directly.
Fix #1322 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1339)
> Fix executor doesn't apply user-configured container spec correctly

- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
- cmd/fission-bundle/main.go
- hack/release-build.sh
- pkg/executor/executor.go
- pkg/executor/executor_test.go
If a user deploys fission in the namespace which is different from the one in the single YAML file generated by helm, fission components won't be able to talk to each other due to the wrong namespace appends after the service address.
This PR adds `--namespace` when generating the YAML file to prevent the mismatch problem.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1344)
> Fix the namespace mismatch problem when deploying with a single YAML file

- charts/README.md
- charts/fission-all/templates/router.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/router.yaml
- charts/fission-core/values.yaml
- pkg/router/router.go
Encoded path means the URL path contains encoded string like "/foo%2Fbar".
Gorilla/Mux by default doesn't enable encoded path support, you need to enable
it when initializing the router.
This PR adds a new environment variable USE_ENCODED_PATH to router
deployment to enable encoded path support.
Fix #1317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1347)
> Support encoded path in router

- pkg/controller/api.go
- pkg/executor/executor.go
- pkg/executor/newdeploy/newdeploymgr.go
When a function with executor type newdeploy got created, Newdeploy
is expected to create deployment/HPA/service for it and insert serviceEntry
to the cache for later use. Once clients call the function, newdeploy returns
the serviceEntry to the router.
However, the log shows that the newdeploy was unable to find the entry and
prints "Resource not found - key 'xxx' not found". The root cause is that the
informer controller instead of processing items in parallel, it dispatches XXFunc
to process items one by one. So if there is any problem during the creation of the
kubernetes resource, it takes a longer time to process the next item and hence
the serviceEntry was not inserted before clients call the function.
This PR lets the newdeploy to process items in extra goroutines instead of …
> Fix newdeploy failed to find serviceEntry in cache

- pkg/fetcher/fetcher.go
- pkg/fission-cli/cli.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/package/update.go
- pkg/fission-cli/cmd/package/util/util.go
- pkg/fission-cli/cmd/spec/apply.go
- pkg/fission-cli/cmd/support/dump.go
- pkg/fission-cli/function.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- test/init_tools.sh
- test/tests/test_create_fn_with_url.sh
Fix #441 
In case of large files, it takes a long time for user to download
the source from the URL and then upload it to StorgeSvc through
CLI.
This PR allows a user to use URL as the function source when creating a function
and provides a new flag "--keeparchiveurl" to let the user to decided
whether the CLI should download the file first or store the file URL in the
archive directly. If "--keeparchiveurl" is true, then no checksum will be
generated, it's the user's responsibility to ensure the file won't be changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1360)
> Allow using URL as archive source when creating functions

- environments/tensorflow-serving/server.go
- examples/tensorflow-serving/README.md
Tensorflow Serving supports three kinds of API: predict, classify, regress. In order to fully support possible API types, this PR adds code to split the entry point with separator ":" to get model name and the API type separately. And append the API type to proxy URL when receiving the requests.
```
$ fission fn create --name t1 --pkg <pkg name> \
--env tensorflow --entrypoint "half_plus_two:regress"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1371)
> Allow to set API type for tensorflow serving environment

- environments/tensorflow-serving/server.go
- pkg/controller/functionApi.go
- pkg/controller/storagesvc.go
- pkg/controller/workflowApiProxy.go
- pkg/fission-cli/logdb/influxdb.go
Istio sidecar proxy blocks all requests sent through the reverse proxy
to the target service if the request.Host is not properly set to the
internal target service host. This PR sets the target service hosts
before establishing the proxy for the client in order to pass the
Istio sidecar proxy check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1377)
> Fix reverse proxy shows 404 not found when Istio enabled

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/router.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/templates/router.yaml
- cmd/fission-bundle/main.go
- pkg/fetcher/config/config.go
To follow 12-factor app rules, make jaeger collector endpoint
as an environment variable instead of CLI args. It's easier to
replace the value in different deployments. Also, we can utilize
valueFrom to get value from the configmap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1399)
> Set jaeger collector endpoint as an environment variable

- charts/fission-all/templates/router.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/router.yaml
- charts/fission-core/values.yaml
- pkg/router/router.go
- pkg/router/router_test.go
Jaeger preserves the trace data of router healthz endpoints
which is not so helpful for monitoring function metrics and
consumes storage to store such trace data.
This PR uses `GetStartOptions` to examine the request's path and
check if it's a request to healthz endpoint. If yes, skip and not
to trace it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1400)
> Skip trace for router healthz endpoint

- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/log.go
- pkg/fission-cli/cmd/function/test.go
- test/tests/test_ingress.sh
When `fn test` failed to retrieve logs from the function
pod, it turns to query logs from the log database. However,
the logdb type flag is not set to `fn test`, hence the logdb
type is empty (even without default value) and causes `fn logs`
returns an error due to unable to find the corresponding log
database type.
This PR adds logdb type flag to `fn test` to resolve the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1401)
> Fix fn test failed to query logs from log database

- pkg/fission-cli/cmd/package/command.go
- pkg/fission-cli/cmd/package/info.go
- pkg/fission-cli/cmd/package/util/util.go
- pkg/fission-cli/cmd/package/util/util_test.go
- pkg/fission-cli/cmd/spec/buildwatch.go
The character `\n` in buildlog stores in package status
are escaped and so when we have to replace them with
actual line breaker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1403)
> Build error formatting on fission spec apply --wait

- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/cmd/package/command.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/package/update.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- test/tests/test_create_fn_with_url.sh
To keep archive creation implementation simple and prevent any
confusion, we decided to remove `--keepurl` flag and embed URL 
directly without downloading the file from it . In this way, we can 
ensure consistent behavior in either package creation or spec file 
creation. Also, it increases the portability of spec file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1413)
> Always embed given URL in the archive

- pkg/router/functionHandler.go
If the context of request is closed before ReverseProxy finishing writing
a huge response body to the response writer, the client will only receive
a truncated response body.
To solve this, we move the context cancel after ReverseProxy finished.
Fix #1409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1420)
> Fix truncated body returned from router

- pkg/apis/fission.io/v1/types.go
- pkg/executor/newdeploy/newdeploymgr.go
When a function is created before the creation of environment it's used, the newdeploy will not be able to create kube objs. Hence no function service record is inserted into the cache.
When getFuncSvc is called, the newdeploy tries to find the record in service cache in order to create kube objs with the same name used in previous kubeobjs creation. However, due to no record in the cache, a NotFound error is returned directly and causes the problem. To solve this, we use fn meta UID to ensure we always get the same obj name instead of getting it from cache.
Fix #1426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1428)
> Fix no kubeobjs get created if fn created before env creation

- pkg/executor/api.go
- pkg/executor/cms/cmscontroller.go
- pkg/executor/executor.go
- pkg/executor/executortype/executortype.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/reaper/reaper.go
- pkg/types/types.go
- test/utils.sh
Previously, once the executor is deleted for reasons (like upgrade or cluster scale-in), 
the new executor deletes all existing resources created by the old executor and creates 
new one. This mechanism becomes a problem when there are requests connecting to the 
existing pods. Also in the worst case, the cluster may not have enough resources to create 
new pods and cause service downtime.
This PR let each executor type adopts existing resources before starting the executor 
API services, and so the alive connections won't experience failure. However, the requests 
send to the function that doesn't have alive function pods will still fail due to the 
executor is in bootstrapping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Adopt existing orphan kubernetes resources when executor starts up

- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/poolmgr/gp.go
When a new executor starts up, it adopts the orphan kubernetes resources created 
by the old executor instance. However, the adopted resource won't reflect the changes 
come with the new executor, for example, the fetcher image inside won't be changed. 
To solve this, executor updates the resource spec (HPA/Deployment/Service) with the 
latest resources spec. By doing this, we can prevent the inconsistency between resources 
created by different executor instance, also minimizes the impact on users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1447)
> Fix adopted deployment uses old fetcher image

- pkg/apis/fission.io/v1/const.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
We used to update timestamp in the deployment environment field in order to trigger a rolling update when the function referenced resources get updated. However, use timestamp means we are not able to avoid triggering a rolling update when executor tries to adopt orphaned deployment due to timestamp changed which is unwanted. In order to let executor adopt deployment without triggering a rolling update, we need an identical way to get a value that can reflect resources changed without affecting by the time. 
To achieve this goal, the sum of the resource version of all referenced resources is a good fit for our scenario since the sum of the resource version is always the same as long as no resources changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Prevent newdeploy updates deployment if no resources changed

- pkg/executor/cms/cmscontroller.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/util/util.go
The pod template is embedded inside the deployment. So if 
the pod annotation contains instance-id, the deployment
will get updated and thus triggers a rolling update whenever
a new executor starts which is unwanted.
After this PR, poolmanager will patches instance-id when a 
pod is chosen for a function. 
For newdeploy, unlike poolmanager manages the lifecycle 
of function pod directly, newdeploy is only responsible 
to create the deployment so we append instance-id to top-
level controller (deployment) only.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1454)
> Prevent deployment from rolling update due to different instance-id

- pkg/executor/executor.go
- pkg/executor/executortype/executortype.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/reaper/reaper.go
Add CleanupOldExecutorObjects to executor type interface in order
to let an executor type manages how to clean up the resources it created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1455)
> Let executor type manages how to do cleanup for old kubeobjects

- pkg/fission-cli/cmd/function/create.go
If we are referring more than one configmaps in our command while creating function it fails, but doesnt say the configmap name that is not present.
This change fixes that.
This is how the error message gets displayed now
```
Error: error checking configmap cmtwo: Resource not found - NotFound
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1462)
> Add the not present cmname while fn create in err message [CLI-UX]

- pkg/fission-cli/cmd/function/test.go
Removing use of environment variable FISSION_ROUTER for `fission fn test`
The check for the variable is in a `if` block. Removing the `if` doesn't harm with some modification.
Added a warning for the user.
Resolves https://github.com/fission/fission/issues/1404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1465)
> Remove FISSION_ROUTER for fn test

- environments/go/server.go
The 3rd party package version used by the go server may be different from the one in the user's source code and will cause plugin version mismatched. Hence, we should never import any external packages except the Fission or built-in packages.
This PR replaces all 3rd-party packages with built-in packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1469)
> Fix go-server failed to load plugin

- pkg/fission-cli/cmd/spec/command.go
- pkg/fission-cli/cmd/spec/list.go
Fixes #852 
Adding fission spec list functionality. It lists Functions, Environment, Packages, HTTPTrigger, MessageQueueTriggers, Canary Config, TimeTrigger, KubeWatch created by an application specification. 
Here is the screenshot of the result: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1468)
> Add spec list feature

- hack/travis-kube-setup.sh
- test/cluster/main.tf
- test/test_utils.sh
- test/tests/test_ingress.sh
- test/upgrade/fission_upgrade_test.sh
Don't know somehow after moving to the new CI cluster with newer Kubernetes version (13 -> 15) the informer delete event arrives router after ~20secs and causes failure of ingress test. In order to not block the CI, this PR modified the ingress test script to regenerates the TEST_ID before creating a new trigger to avoid the name conflict issue.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1500)
> Move to new CI cluster

- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
The root cause of the problem is that eagerPoolCreator
tries to create the deployment when the poolmanager
is trying to delete it. To avoid this, start eager pool
creator after executor starts serving requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1511)
> Fix poolmanager wrongly delete env pool

- cmd/fission-cli/app/app.go
- pkg/controller/client/fake_client.go
- pkg/controller/client/v1/fake/fake_canaryconfig.go
- pkg/controller/client/v1/fake/fake_environment.go
- pkg/controller/client/v1/fake/fake_function.go
- pkg/controller/client/v1/fake/fake_httptrigger.go
- pkg/controller/client/v1/fake/fake_kuberneteswatchtrigger.go
- pkg/controller/client/v1/fake/fake_misc.go
- pkg/controller/client/v1/fake/fake_mqtrigger.go
- pkg/controller/client/v1/fake/fake_package.go
- pkg/controller/client/v1/fake/fake_timetrigger.go
- pkg/controller/client/v1/fake/fake_v1.go
- pkg/fission-cli/cmd/version/command.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
This PR adds a fake controller client for local CLI operations like offline spec generation or for unit test purposes. The fake client now only implements the "Version()" function and more functions will be implemented once we figure out how to achieve the goals mentioned above.
Fix #1514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1515)
> Add fake client for local command operation

- pkg/apis/core/v1/types.go
- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/pkgwatcher.go
- pkg/controller/controller.go
- test/test_utils.sh
- test/tests/test_kubectl/spec-yaml/env-go.yaml
- test/tests/test_kubectl/spec-yaml/function-go.yaml
- test/tests/test_kubectl/test_kubectl.sh
- test/utils.sh
If the user applies package YAML file has no status field, 
the package won't be able to be compiled or deployed due 
to lack of status. This PR aims to add a check at buildermgr 
to set initial package status to those packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1522)
> Set initial package status if its empty

- pkg/controller/api.go
- pkg/controller/client/v1/fake/fake_misc.go
- pkg/controller/client/v1/misc.go
- pkg/controller/configmapApi.go
- pkg/controller/secretApi.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/cmd/spec/spec.go
This PR changes the behavior of controller API which
wrongly exposes sensitive data to the client. Now, the
API only returns success if secret/configmap exists;
otherwise, an error will be returned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1543)
> Avoid exposing sensitive data to client

- environments/python/Dockerfile
During the implementation of Fission in our company infrastructure, I've noticed that the default runtime image for Python environments uses Python version `3.5`.
Most of our applications uses `^3.7` and the previous version is impossible to use for most of those.
I was planning to create a custom environment, but creating a custom environment just to bump 2 versions is overkill. In my opinion we should use `alpine' latest, which uses Python 3.7 instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1547)
> Bump Python environment to latest Alpine

- pkg/controller/api.go
This PR let the controller returns the detail error message 
of kubernetes error which makes users understand what's
happening instead of meanless error msg.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1560)
> Return Kubernetes full error message

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/fluentbit.yaml
- charts/fission-all/templates/pre-upgrade-job.yaml
- skaffold.yaml
This PR changes the Skaffold and some manifests to make it work with cloud clusters as well as with Kind. This will enable a seamless way of building and deploying across both the targets.
Future improvements could be:
- Build the only fission-bundle image and skip Fetcher and preupgradecheck (Most cases fetcher and upgrade won't change a lot). This is right now not working with Skaffold patches but works by commenting lines in build and artifactOverrides sections.
- Debugging support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1700)
> Skaffold kind

- pkg/mqtrigger/messageQueue/kafka/kafka.go
This PR addresses the issue https://github.com/fission/fission/issues/1682 to add details to error topics created for Kafka MQT. It adds additional information to the error topics to track source of error messages, allowing multiple MQTs to be using single error topic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1701)
> Add headers to Kafka MQT error topics

- cmd/builder/main.go
- cmd/fetcher/main.go
- cmd/fission-bundle/main.go
- cmd/preupgradechecks/main.go
- environments/tensorflow-serving/server.go
- pkg/controller/api_test.go
- pkg/crd/crd_test.go
- pkg/executor/executor_test.go
- pkg/executor/fscache/functionServiceCache_test.go
- pkg/logger/logger.go
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq_test.go
- pkg/router/functionHandler_test.go
- pkg/router/functionServiceMap_test.go
- pkg/router/mutablemux_test.go
- pkg/router/router_test.go
- pkg/storagesvc/client/storagesvc_test.go
Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>
All the logger today use Unix timestamp  in the log statements which is of little use for any operations on the logs
This PR is an effort to change that to ISO format imestamps
example: ` {"level":"info","ts":"2020-09-09T12:54:44.622Z","caller":"fission-bundle/main.go:130","msg":"skipping trace exporter registration"}`
Tested: The change has been tested with all components wherever the changes related to logs are made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1708)
> logs: change timestamp to ISO

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
- pkg/executor/executortype/poolmgr/gp.go
Exposed podReady Timeout configuration used in the PoolManager strategy to give more fine-grained control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1788)
> Added flag for podReadyTimeout

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
Added new http keda connector for kinesis in https://github.com/fission/keda-connectors repo, so to use that with fission i have included that in chat's deployment and values yaml file of fission-all and fission-core folder under mq_keda section
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1817)
> Update aws-kinesis image name in values.yaml

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
Added new http keda connector for nats streaming in https://github.com/fission/keda-connectors repo, so to use that with fission i have included that in chat's deployment and values yaml file of fission-all and fission-core folder under mq_keda section
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1839)
>  Update nats streaming image name in values.yaml and deployments yaml 

- go.mod
- pkg/router/analytics.go
- pkg/router/functionHandler.go
- pkg/router/functionReferenceResolver.go
- pkg/router/functionServiceMap.go
- pkg/router/httpTriggers.go
- pkg/router/mutablemux.go
- pkg/router/mutablemux_test.go
- pkg/router/requesthHeader.go
- pkg/router/router.go
- pkg/router/util_test.go
This PR addresses issues reported by `golangci-lint` in the package `/fission/pkg/router`.
Inline with issue #1835 
**Issues Reported**
```
~/go/src/github.com/gauravgahlot/fission/pkg/router (router_cleanup) ✔ 
➜ golangci-lint run  
functionHandler.go:214:46: Error return value of `roundTripper.funcHandler.unTapService` is not checked (errcheck)
go roundTripper.funcHandler.unTapService(fn, serviceUrl)
^
functionHandler.go:587:11: Error return value of `rw.Write` is not checked (errcheck)
rw.Write([]byte(msg))
^
functionReferenceResolver.go:115:18: Error return value of `frr.refCache.Set` is not checked (errcheck)
frr.refCache.Set(nfr, *rr)
^
mutablemux_test.go:31:22: Error return value of `responseWriter.Write` is not checked (errcheck)
responseWriter.Write([]byte("old handler"))
^ …
```
> Fixed golangci-lint issues: /fission/pkg/router

- go.mod
- pkg/executor/api.go
- pkg/executor/client/client.go
- pkg/executor/cms/cmscontroller.go
- pkg/executor/executor.go
- pkg/executor/executor_test.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/fscache/functionServiceCache.go
- pkg/executor/fscache/metrics.go
- pkg/executor/reaper/reaper.go
- pkg/executor/util/merge.go
- pkg/executor/util/util.go
This PR addresses issues reported by `golangci-lint` in the package `/fission/pkg/executor`.
Inline with issue #1835 
**Reported Issues**
```
~/go/src/github.com/gauravgahlot/fission/pkg/executor (executor_fixes) ✔ 
➜ golangci-lint run             
executortype/newdeploy/newdeploymgr.go:473:29: Error return value of `deploy.cleanupNewdeploy` is not checked (errcheck)
go deploy.cleanupNewdeploy(ns, objName)
^
executortype/newdeploy/newdeploymgr.go:481:29: Error return value of `deploy.cleanupNewdeploy` is not checked (errcheck)
go deploy.cleanupNewdeploy(ns, objName)
^
executortype/newdeploy/newdeploymgr.go:488:29: Error return value of `deploy.cleanupNewdeploy` is not checked (errcheck)
go deploy.cleanupNewdeploy(ns, objName)
^
executortype/newdeploy/newdeploymgr.go:730:21: S1039: …
```
> Fixed golangci-lint issues: /fission/pkg/executor

- README.md
added github action build status badge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1887)
> Replace build status badge to use GH Actions status

- pkg/builder/builder.go
- pkg/buildermgr/pkgwatcher.go
- pkg/controller/api.go
- pkg/controller/api_test.go
- pkg/controller/client/v1/function.go
- pkg/controller/functionApi.go
- pkg/crd/crd_test.go
- pkg/fetcher/fetcher.go
- pkg/fission-cli/cliwrapper/driver/cobra/cobra.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/kubewatcher/kubewatcher.go
- pkg/kubewatcher/watchSync.go
- pkg/logger/logger.go
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq.go
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq_test.go
- pkg/newcache/poolcache_test.go
- pkg/storagesvc/client/storagesvc_test.go
- pkg/storagesvc/storagesvc.go
- pkg/storagesvc/stowClient.go
- pkg/timer/timer.go
- pkg/timer/timerSync.go
This PR addresses issues reported by `golangci-lint` in the package `/fission/pkg/`.
Inline with issue #1835 
```
~/go/src/github.com/gauravgahlot/fission/pkg (master) ✔  
➜ golangci-lint run                 
logger/logger.go:173:22: Error return value of `zapLogger.Sync` is not checked (errcheck)
defer zapLogger.Sync()
^
fission-cli/cliwrapper/driver/cobra/cobra.go:98:30: Error return value of `(*github.com/spf13/pflag.FlagSet).MarkDeprecated` is not checked (errcheck)
cmd.Flags().MarkDeprecated(f.Name, usage)
^
fission-cli/cliwrapper/driver/cobra/cobra.go:100:26: Error return value of `(*github.com/spf13/pflag.FlagSet).MarkHidden` is not checked (errcheck)
cmd.Flags().MarkHidden(f.Name)
^
fission-cli/cliwrapper/driver/cobra/cobra.go:108:23: Error return value of `cmd.MarkFlagRequired` …
```
> Fixed golangci-lint issues: /fission/pkg

- go.mod
- pkg/router/functionHandler.go
- pkg/router/functionHandler_test.go
Fixes https://github.com/fission/fission/issues/1875
Returns the correct status code for rate limits. 
Since there's no way to fetch correct response code from RoundTrip, had to rely on parsing it from the error message. 
Also, I think we  shouldn't retry when we hit the rate limit, instead user is expected to retry later. This way, we avoid holding requests for long time and save resources.
> Fix status code for rate limit

- pkg/executor/executortype/poolmgr/gpm.go
- skaffold.yaml
While playing around with Fission I found I was unable to get more than about 5 req / sec out of my cluster, regardless of Fission settings. After digging deeper I found the router component was making a call into the k8s APIs on every request to check the pod's status and k8s was rate-limiting that check.
This PR adds a [SharedIndexInformer](https://pkg.go.dev/k8s.io/client-go/tools/cache#SharedIndexInformer) for pods to the router so it is kept up-to-date with pod changes and doesn't need to consult k8s on every request. With these changes the same cluster was able to handle over 200 req / sec, and at that rate all CPUs were 100% used.
> Add a SharedIndexInformer for pods to router.

- cmd/builder/Dockerfile.fission-builder
- cmd/fetcher/Dockerfile.fission-fetcher
- cmd/fission-bundle/Dockerfile.fission-bundle
- cmd/preupgradechecks/Dockerfile.fission-preupgradechecks
Alpine 3.10 has reached end-of-support. Using alpine 3.13 instead.
Reference: https://alpinelinux.org/releases/
> Change alpine base image from 3.10 to 3.13

- test/tests/mqtrigger/nats/stan-sub/main.go
- test/tests/mqtrigger/nats/test_mqtrigger.sh
- test/tests/mqtrigger/nats/test_mqtrigger_error.sh
In test_mqtrigger.sh and test_mqtrigger_error.sh tests, we timeout program
if not received right output. Ensuring we capture timeout signal and do program
cleanup accordingly. Also printing due to which signal program failed.
> Handle SIGTERM signal in mqtrigger subscriber

- go.mod
- go.sum
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/fscache/metrics.go
Addresses  https://github.com/fission/fission/issues/1989
Users can view the metrics in PromQL directly once they've deployed prometheus. 
This PR introduces two metrics:
* fission_pod_reaptime_seconds : Amount of seconds to reap a pod
* fission_idle_pod_time : Number of seconds it took for Reaper to detect the pod was idle
> Add metrics to Reaper

- .github/workflows/push_pr.yaml
We are facing issue https://github.com/golang/go/issues/37436
in CI for multiple PRs. Trying to switch to latest go version from 1.14 tree.
Reference https://github.com/actions/go-versions/blob/main/versions-manifest.json
> Use latest 1.14 go version in CI

- cmd/fission-bundle/main.go
- cmd/preupgradechecks/main.go
- pkg/mqtrigger/messageQueue/kafka/kafka.go
Running `golangci-lint` reports use of deprecated code:
```
fission on ~ master [$] via 🐹 v1.16.3
➜ golangci-lint run
pkg/mqtrigger/messageQueue/kafka/kafka.go:215:2: SA1019: tlsConfig.BuildNameToCertificate is deprecated: NameToCertificate only allows associating a single certificate with a given name. Leave that field nil to let the library select the first compatible chain from Certificates. (staticcheck)
tlsConfig.BuildNameToCertificate()
^
cmd/fission-bundle/main.go:259:20: SA1019: docopt.Parse is deprecated: Parse is provided for backward compatibility with the original docopt.go package. Please rather make use of ParseDoc, ParseArgs, or use your own custom Parser. (staticcheck)
arguments, err := docopt.Parse(usage, nil, true, version, false)
^
cmd/preupgradechecks/main.go:54:20: …
```
> Update deprecated functions/methods calls

- README.md
- charts/fission-all/templates/NOTES.txt
- charts/fission-core/templates/NOTES.txt
- test/tests/test_create_fn_with_url.sh
Since we recently migrated all fission examples to fission/examples repository, we need to change
respective references.
> Change examples references to examples repostiory

- cmd/preupgradechecks/preupgradechecks.go
Note: the newer CRDs are not present in this commit or the latest branch yet. 
Newer CRDs are generated in this PR:
https://github.com/fission/fission/pull/2033
> OnlyOnce preupgrade check

- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/fission-cli/cmd/environment/command.go
- pkg/fission-cli/cmd/environment/create.go
- pkg/fission-cli/cmd/environment/update.go
- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/fission-cli/util/util.go
- pkg/utils/maps/map.go
This PR adds,
1. Support for adding labels and annotations to fuctions & environment via fission CLI thrrough create & update command.
2. Change ensures labels and annotations assigned to environment would reflect on pods created via executortype poolmanager and newdeploy.
Usage:
```sh
fission env create --name nodejs --image fission/node-env --poolsize 1 --labels="env=node,author=sanket" \
--annotation "abc.com/foo=bar" --annotation "secret-inject: my-secret"
fission env update --name nodejs --labels="env=node,author=sanket,another-label=value"
```
> Labels and annotation support for functions and environments

- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/container/deployment.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- Newdeploy/container function service names should fit in 63 characters 
- Added error message to dump deployment status before and after update in case of failure
- Dump if any error in case of newdeploy cleanup
> Newdeploy/container function service names should fit in 63 characters 

- cmd/builder/Dockerfile.fission-builder
- cmd/fetcher/Dockerfile.fission-fetcher
- cmd/fission-bundle/Dockerfile.fission-bundle
- cmd/preupgradechecks/Dockerfile.fission-preupgradechecks
- cmd/reporter/Dockerfile.reporter
Change is required for vulnerability fixes also there were few DNS failures in recent alpine builds.
> Update alpine base image to 3.14

- pkg/executor/executortype/newdeploy/newdeploymgr.go
Currently when we update env, even if we dont have newdeploy related
functions env is getting is getting triggered. Added filter in finding
related functions to avoid this behaviour.
> Consider newdeploy functions only for env update in newdeploy manager

- pkg/buildermgr/buildermgr.go
- pkg/canaryconfigmgr/canaryConfigMgr.go
- pkg/executor/executor.go
- pkg/logger/logger.go
- pkg/mqtrigger/scalermanager.go
- pkg/router/httpTriggers.go
Currently most of informers used in Fission are using resync
period of 30sec which is quite low and causes lot of disturbances
in overall system. Since informers already have watchers which would
be delivering events to the handlers. If any handlers require lower
sync period they should register handler with `AddEventHandlersWithResyncPeriod`
instead of we generaling informer.
> Change default informer resync period to 30 minutes

- charts/fission-all/templates/deployment.yaml
- pkg/crd/key.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/common.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/utils/informer.go
- Use informers and listers in executors 
- Passing context properly in pool manager executor
- Environment updates in pool manager would not cause updates in the deployment
- Environment update minimizing downtime
- Use replicaset controller and environment delete triggers to cleanup specialized pods
> Use pool pod controller with env informer 

- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
In upgrade tests, sometimes in race condition pool manager podLister
takes time to sync in which case, poolpodcontrolller gets nil reference
for gpm.podLister. Passing podInformer to poolpodcontroller so that
we wait for podInformer cache to sync.
> Pass podinformer to poolpodcontroller instead of reference to pool manager

- pkg/fetcher/config/config.go
- pkg/fetcher/fetcher.go
When fetch request is received by fetcher, it fetches
package information. Adding resource version also in fetch request
so that we ensure package resource version mentioned in fetch req
matches with one received.
> Check package resource version from fetch request with fetched package

- cmd/fetcher/app/server.go
- cmd/fission-bundle/main.go
- pkg/builder/client/client.go
- pkg/buildermgr/common.go
- pkg/executor/api.go
- pkg/executor/client/client.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/container/deployment.go
- pkg/executor/executortype/container/hpa.go
- pkg/executor/executortype/container/svc.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/fetcher/client/client.go
- pkg/fetcher/fetcher.go
- pkg/router/functionHandler.go
- pkg/router/httpTriggers.go
- pkg/storagesvc/client/client.go
- pkg/utils/otel/attributes.go
- pkg/utils/otel/log.go
- pkg/utils/otel/provider.go
- pkg/utils/tracing/tracing.go
1. We capture all spans from router to function pod
2. Within a span different events are captured
3. Logs with context should have traceID, so by trace ID we can travel all logs. Logs with trace ID are enabled even if opentelemtry collector not mentioned.
```text
executor-7758b648f6-2tsgn executor {"level":"info","ts":"2021-09-14T11:32:01.971Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:480","msg":"chose pod","trace_id":"26394b2c0739b896b5dada41d2bba00e","labels":{"environmentName":"go","environmentNamespace":"default","environmentUid":"97e63265-4846-4b19-8035-d6d862164409","executorType":"poolmgr","functionName":"go-otel-func","functionNamespace":"default","functionUid":"53c273ec-842c-4071-bd62-13d944a251cf", …
```
> feature: Capture important events with span in fission and add trace id in logs

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/router.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/_helpers.tpl
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/templates/router.yaml
- charts/fission-core/values.yaml
- cmd/fetcher/app/server.go
- cmd/fission-bundle/main.go
- go.mod
- pkg/fetcher/config/config.go
- pkg/utils/otel/provider.go
- pkg/utils/tracing/tracing.go
- skaffold.yaml
Opentelemetry defines standard variables which are supported by multiple observability platforms.
[1] https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md
[2] https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md
By defining support for standard env vars, Fission open telemetry support can be leveraged with different
platforms such as NewRelic, SigNoz, DataDog etc.
Any open telemetry compatible collectors can be configured with Fission.
> fix: Use standard env variables for opentelemtry

- .github/workflows/lint.yaml
> chore:Add codecov coverage reporting in CI flow

- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/controller/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/kubewatcher/deployment.yaml
- charts/fission-all/templates/mqt-keda/deployment.yaml
- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/templates/storagesvc/deployment.yaml
- charts/fission-all/templates/timer/deployment.yaml
- charts/fission-all/values.yaml
- skaffold.yaml
In Fission CI as well in couple of scenarios, noticed Fission pods
getting preempted when Function pods are getting created. As both
Fission components and function pods have same priority class
fission component pods might get preempted. It to be recommended to
set higher priority class for components such as Fission router, executor,
controller so that Fission functioning doesnt get disrupted.
Most of Fission components work fine with restart except executor. So
user should set priorityClass for Fission executor.
> Add support to mention priorityClassName for Fission components

- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/readyPodController.go
- pkg/utils/informer.go
Reactored ready pod controller code to user lister and cache sync checks,
so that we avoid querying lister if cache is not synced in choodPod function.
Also, as noticied in #2258 we were initializing workqueue in goroutine
which was causing nil pointer reference. We have moved it out of goroutine
and kept specific parts in goroutine.
> Issue #2258 Reafctor ready pod conroller to use lister and cache sync checks

- cmd/fetcher/app/server.go
- cmd/fetcher/main.go
- cmd/fission-bundle/main.go
- cmd/preupgradechecks/main.go
- cmd/reporter/app/cmd_event.go
- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/pkgwatcher.go
- pkg/controller/api_test.go
- pkg/controller/controller.go
- pkg/executor/executor.go
- pkg/executor/executor_test.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/reaper/reaper.go
- pkg/kubewatcher/kubewatcher.go
- pkg/kubewatcher/main.go
- pkg/logger/logger.go
- pkg/mqtrigger/scalermanager.go
- pkg/router/router.go
- pkg/storagesvc/archivePruner.go
- pkg/storagesvc/client/storagesvc_test.go
- pkg/storagesvc/storagesvc.go
- pkg/timer/main.go
- pkg/timer/timerSync.go
- pkg/tracker/tracker.go
- pkg/utils/otel/provider.go
- pkg/utils/signals/signals.go
Currently, fission component doesnt handle shutdown signals.
So we dont get any to do required cleanup before fission process
exits. Adding signal capture process with cancelling context so
that all dependent process stop working when process gets term
signal.
> Capture os signals to gracefully shutdown fission components

- cmd/builder/Dockerfile.fission-builder
- cmd/fetcher/Dockerfile.fission-fetcher
- cmd/fission-bundle/Dockerfile.fission-bundle
- cmd/preupgradechecks/Dockerfile.fission-preupgradechecks
- cmd/reporter/Dockerfile.reporter
- go.mod
- go.sum
- Update alpine base image to 3.14.3
- Update github.com/opencontainers/image-spec to v1.0.2
> Update alpine base image to 3.14.3 and security fixes

- pkg/storagesvc/stowClient.go
If a bucket name passed by a user already exists on the cloud, allow the user to use that one as storage and do not throw an error. So users don't really have to create a bucket always and no need to give create buckets privileges to access keys.
Fixes https://github.com/fission/fission/issues/2199
Created multiple buckets on S3 having the same prefix, and the code picked the right bucket (with exact match)
> Allow user to use existing bucket with same name via fission storage service

- cmd/preupgradechecks/checks.go
- cmd/preupgradechecks/main.go
Added error logs that capture if any missing fields in CRDs.
These were identified as missing error capture logs during one of the debugging sessions.
Fixes #
Test image : tripples/pre-upgrade-checks:sanket-dev
> Capture error from schema check in preupgrade verification

- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/kubewatch/create.go
- pkg/fission-cli/cmd/mqtrigger/create.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/spec/apply.go
- pkg/fission-cli/cmd/spec/command.go
- pkg/fission-cli/cmd/spec/destroy.go
- pkg/fission-cli/cmd/spec/list.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/cmd/spec/validate.go
- pkg/fission-cli/cmd/timetrigger/create.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/fission-cli/util/constants.go
- pkg/utils/gitrepo/gitrepo.go
When `--commitlabel` is passed to the `fission spec apply` command, the resources created will have `commit`
label with value set depending upon the status of the spec file in the git repository. If the `specdir` is not part of git repository then despite passing the `--commitlabel` flag this label will not be applied on the resources created/updated.
The value of the `commit` label for different status of the file is as follows:
| Git File Status | Label Value |
| :--- | :---: |
| New untracked file | `untracked` |
| New staged file | `staged` |
| Tracked file with changes in worktree | `<commitID>-unstaged` |
| Tracked file with changes staged | `<commitID>-staged` |
| Tracked file with clean commit | `<commitID>` |
The value of `<commitID>` will be the short commit version of the …
> feature: Apply commit label on resources created/updated when '--commitlabel' is passed

- pkg/mqtrigger/scalermanager.go
Kafka connector deployment issue if default namespace is not used.
Fixes #1987 #2242 
Tried kafka triggers in different namespaces.
> Kafka connector namespace issue

- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/common/clusterrole.yaml
- charts/fission-all/templates/common/clusterrolebinding.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/misc-functions/clusterrole.yaml
- charts/fission-all/templates/misc-functions/role.yaml
- charts/fission-all/templates/misc-functions/rolebinding.yaml
- charts/fission-all/values.yaml
- pkg/apis/core/v1/const.go
- pkg/buildermgr/pkgwatcher.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/poolmgr/funchandlers.go
- pkg/executor/executortype/poolmgr/packagehandlers.go
- pkg/utils/rbacutils.go
Changes consider Helm Release name while creation of RBAC ClusterRole resources. This change allows users to have multiple Fission releases on the same cluster.
Fixes https://github.com/fission/fission/issues/2291
Verified two Fission release install on same cluster.
On  creation of env and function both installations created deployment. 
Fission function could be tested by setting `FISSION_NAMESPACE` env variable.
```
FISSION_NAMESPACE=fission
fission fn test --name hello-world
FISSION_NAMESPACE=fisison-canary
fission fn test --name hello-world
```
> Rbac resources per release

- pkg/fission-cli/cmd/mqtrigger/create.go
The terminal throws error while creating mqtrigger if the given function is not present. Previously, nothing was displayed by the terminal. Please let me know if you want to show just a warning like in the case of httptrigger.
Fixes #2300
> show error while creating mqtrigger if given function is not present

- pkg/executor/executortype/container/deployment.go
- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/run_container.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
Added flag to configure grace period while creating container functions.
For negative input I've given a warning. Let me know if you want to throw an error instead. 0 is a valid input according to this - https://doc.crds.dev/github.com/fission/fission/fission.io/Function/v1@v1.15.0#spec-podspec-terminationGracePeriodSeconds. Also in the same doc it says default is 30 seconds. I believe it is a typo mistake. Shouldn't it be 360 seconds?
Fixes #2284
> make graceperiod configurable for container functions

- charts/fission-all/templates/NOTES.txt
- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/templates/router/secret.yaml
- charts/fission-all/values.yaml
- cmd/fission-cli/app/app.go
- go.mod
- go.sum
- pkg/apis/core/v1/types.go
- pkg/error/httperror.go
- pkg/featureconfig/types.go
- pkg/fission-cli/cmd/function/test.go
- pkg/fission-cli/cmd/token/command.go
- pkg/fission-cli/cmd/token/create.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/fission-cli/util/constants.go
- pkg/router/httpTriggers.go
This PR adds new feature to enable authentication for fission routers. 
This is **a optional feature** which can be enabled/disabled as per the needs of the user. 
On enabling this feature, an endpoint for authentication will be registered in the router and all function API calls with be routed via authentication middleware. 
The user has to first create auth token by passing credentials. 
The token generated has to be then passed in the authorization header for all susbequent API calls to access the function.
This feature can be turned on by setting the key `authentication.enabled` in `charts/fission-all/values.yaml ` to `true` during the time of deployment. 
Along with this there are other keys like 
- `authUrlPath`
-  `authUsername`
- `jwtSigningKey`
- `jwtExpiryTime` 
- `jwtIssuer` …
> feature: Basic auth support with fission router

- pkg/fission-cli/cmd/spec/apply.go
- pkg/fission-cli/cmd/spec/command.go
- pkg/fission-cli/cmd/spec/destroy.go
- pkg/fission-cli/cmd/spec/validate.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
Added allowconflicts flag to specs.
Fixes #2109 
Rebuilt the fission-cli and tested the command.
> [Feature] Force spec apply even if conflicting resources exist with different deployment ID

- pkg/fission-cli/cmd/environment/command.go
- pkg/fission-cli/cmd/environment/delete.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
Prevents deletion of environment even if one function is using it.
```
fission env create --name nodeenv --image fission/node-env
fission fn create --name consumer --env nodeenv --code consumer.js
```
- `fission env delete --name nodeenv`
```
Options:
--name=''                           Environment name
--envNamespace='default' (--envns)  Namespace for environment object
--ignorenotfound=false              Treat "resource not found" as a successful delete.
--force=false (-f)                  Force delete env even if one or more functions exist
Global Options:
--server=''         Server URL
--verbosity=1 (-v)  CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)
--kube-context=''   Kubernetes context to be used for the execution of Fission commands
Usage:
fission environment delete …
```
> Prevent env deletion if any function exists

- pkg/fission-cli/cmd/spec/destroy.go
Changed spec deletion order according to dependency.
Tested using this example. [https://github.com/fission/examples/tree/master/spec-example/hello-spec-exmaple](url)
Sample Output:
- `fission spec destroy`
```
Deleted Function default/hello
Deleted Package default/hello-pkg
Deleted Environment default/python-27
```
> Changed spec deletion order according to dependency

- pkg/controller/client/v1/misc.go
Secret should be created in the same namespace as the function. Before this fix, SecretExists() didn't raise a warning but now it does.
Fixes #2304
> Fix validation for secret & configmap reference with function  

- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/controller/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/kubewatcher/deployment.yaml
- charts/fission-all/templates/mqt-keda/deployment.yaml
- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/templates/storagesvc/deployment.yaml
- charts/fission-all/templates/timer/deployment.yaml
- charts/fission-all/values.yaml
Fix helm templating on `resources:` of router deployment and add `resources:` attribute to other fission deployments
> [helm chart] fission deployments resources

- pkg/canaryconfigmgr/prometheusClient.go
- pkg/executor/fscache/metrics.go
- pkg/router/metrics.go
This change mainly fixes few things around router and executor
exposed metrices.
1. We are trying to follow standard in metric names.
2. Lables such as namespace are colliding with kube-prometheus standards
so they are getting relabled to exported_namespace. Added function prefix
to resolve this.
3. Also made required changes in canary config Prometheus queries.
- Labels changed 
- `name` to `function_name`
- `namespace` to `function_namespace`
- Changes affects following metrics exposed by router
- `fission_function_calls_total`
- `fission_function_errors_total`
- `fission_function_duration_seconds`
- `fission_function_overhead_seconds`
- `fission_function_response_size_bytes`
- Labels 
- `funcname` -> `function_name`
- `funcuid` -> …
> Refactoring prometheus metrics and labels

- .github/workflows/push_pr.yaml
- charts/fission-all/Chart.lock
- charts/fission-all/Chart.yaml
- charts/fission-all/README.md
- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/values.yaml
- hack/generate-helm-manifest.sh
- pkg/canaryconfigmgr/prometheusClient.go
- skaffold.yaml
Removing prometheus dependency from Fission chart and request user to have their own prometheus deployment.
We would recommend [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) helm chart from prometheus-community and link it with fission installation.
Fixes #
> [helm chart] Remove prometheus chart dependency from Fission

- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/executortype/poolmgr/gp_deployment_test.go
Poolmgr pod naming convention changed
Fixes #2379
> Fixed poolmgr pod naming error

- charts/fission-all/templates/mqt-keda/deployment.yaml
- charts/fission-all/values.yaml
Typo in gcp-pubsub connector causes error in creating mqtrigger
Fixes #2392 
Successfully created mqtrigger after fixing typo.
> Fixing gcp connector name typo

- charts/fission-all/templates/mqt-fission-kafka/deployment.yaml
- cmd/fission-bundle/main.go
- cmd/fission-bundle/mqtrigger/mqtrigger.go
- pkg/mqtrigger/messageQueue/kafka/kafka.go
- pkg/mqtrigger/metrics.go
- pkg/mqtrigger/mqtmanager.go
- pkg/mqtrigger/mqtmanager_test.go
- skaffold.yaml
- Use mqtrigger watch instead of polling mqtrigger every 5 seconds
- Added metrics to monitor no of subscriptions, and no of messages per subscription
- Add standard go metrics exported by prometheus
- Enable prometheus discovery for mqtrigger pod
- Optimized mqtrigger manager cache
Fixes #
> Added metrics for fission mqtrigger and optimizations in trigger subscriptions

- pkg/executor/client/client.go
- pkg/router/functionHandler.go
We should avoid tap service call to executor if service
URL retrieved from executor is empty.
Added sanity checks to ensure that.
Fixes #
> Avoid tapservice call to executor with empty URL

- cmd/builder/app/server.go
- cmd/builder/main.go
- cmd/fetcher/app/server.go
- cmd/fetcher/main.go
- cmd/fission-bundle/main.go
- pkg/controller/api.go
- pkg/executor/api.go
- pkg/executor/executor.go
- pkg/mqtrigger/metrics.go
- pkg/mqtrigger/mqtmanager.go
- pkg/router/mutablemux_test.go
- pkg/router/router.go
- pkg/storagesvc/client/storagesvc_test.go
- pkg/storagesvc/storagesvc.go
- pkg/utils/httpserver/server.go
- pkg/utils/httpserver/server_test.go
- pkg/utils/metrics/server.go
- pkg/utils/profile/profile.go
Defining httpserver package capture httpserver shutdown and
introduces uniform running of http server across codebase.
Fixes #
> Use common httpserver across fission

- pkg/executor/executortype/poolmgr/funchandlers.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/packagehandlers.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/executortype/poolmgr/poolpodcontroller_test.go
- pkg/executor/reaper/reaper.go
- pkg/fetcher/config/config.go
- pkg/utils/informer.go
- pkg/utils/rbacutils.go
In pool pod controller we were using pool namespace
rather than pod namespace in cleanup which was causing
issue in few scenarios. Using pod namespace now instead.
Also add unit test for scenario which was failing.
Using kubernetes client interface now across instead of
kubernetes ClientSet for testing.
Fixes #2373
> Fix namespace used in speciallized pod cleanup

- charts/fission-all/templates/controller/servicemonitor.yaml
- charts/fission-all/templates/executor/servicemonitor.yaml
- charts/fission-all/templates/router/servicemonitor.yaml
- charts/fission-all/templates/storagesvc/servicemonitor.yaml
- charts/fission-all/values.yaml
- skaffold.yaml
Initially the user had to implement the service monitors kube-prometheus-stack. Now it would be implemented with helm.
Fixes #
> Added service monitors for components whose metrics are exposed

- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/controller/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/kubewatcher/deployment.yaml
- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/templates/storagesvc/deployment.yaml
- charts/fission-all/templates/timer/deployment.yaml
- charts/fission-all/values.yaml
- skaffold.yaml
- I have added `securityContext` in the following fission components -
1. buildermgr
2. controller
3. executor
4. kubewatcher
5. router
6. timer
7. storagesvc
- By default, I kept the `component.securityContext.enabled: false`; however, I made it `true` in the Fission CI.
Fixes https://github.com/fission/fission/issues/2401
> [issue-2401] Added pod security context for Fission Components

- pkg/storagesvc/localstorage.go
- pkg/storagesvc/s3storage.go
- pkg/storagesvc/storagesvc.go
- pkg/storagesvc/stowClient.go
Earlier archivepruner used to delete all files in S3 bucket irrespective of the subdir mentioned. Now the scope of archivepruner has been reduced to the subdir mentioned if any.
Fixes #2397 
Tested manually by uploading files outside subdir in S3 bucket.
> Fix for archivepruner to delete files only from subdir

- pkg/executor/api.go
Executor sending invalid ips because validation function is getting skipped as the active number of requests allow it to pass the condition. 
This error occurs when a pod is killed but the untap function is not called which influences the value of active variable.
Fixes #2438
> Ensure poolmanager fn address validation even if pod has active connections

- pkg/builder/builder.go
- pkg/builder/builder_test.go
Fixes #2445
- Added unit tests to ensure sufficient testing
- Verified locally by building fission builder image `tripples/builder:dev` image and go builder `tripples/go-builder:dev`.
- Wrote a script used with builder.
```sh
fission spec init
fission env create --name go --image fission/go-env-1.16 --builder tripples/go-builder:dev --spec
fission function create --name hello-go --env go --src hello.go --entrypoint Handler --buildcmd "./custom-build.sh" --spec
```
```
% cat custom-build.sh
echo "Custom script builder args" $*
/usr/local/bin/build
% cat hello.go
package main
import (
"net/http"
)
// Handler is the entry point for this fission function
func Handler(w http.ResponseWriter, r *http.Request) {
msg := "Hello, world!\n"
w.Write([]byte(msg))
}
```
> builder: Allow command with arguments via custom build options

- charts/fission-all/templates/storagesvc/deployment.yaml
- charts/fission-all/values.yaml
- pkg/storagesvc/storagesvc.go
- skaffold.yaml
Earlier the archivePruner was always enabled with an interval. Now the users can disable it if they want to.
Fixes #
> Added variable to enable or disable archivePruner

- charts/fission-all/templates/buildermgr/configmap.yaml
- charts/fission-all/templates/executor/configmap.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/values.yaml
- go.mod
- pkg/apis/core/v1/const.go
- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/envwatcher.go
- pkg/executor/executor.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller_test.go
- pkg/executor/util/util.go
- pkg/executor/util/util_test.go
- pkg/utils/utils.go
- skaffold.yaml
The users can now set the pod spec for builder and fn pods via helm chart.
Currently we have set some default securitycontext for the pods. Before there were no permissions set and the user would by default enter root when `kubectl exec` into pod. Now the permissions have been set and the user will not be able to access root directory in poolmgr and newdeploy pods.
Fixes #2401
Fixes #1820 
Added unit tests and did some manual testing.
> Added support to set builder and fn pod specs via helm chart

- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/fscache/functionServiceCache.go
Function pod immediately terminates once user change the idle timeout in case of new deployment and container executor type. 
This fix will prevent to immediate termination of pods and user will no more face any error for the same. Pod will get terminate as per the idle timeout provided by user.
Fixes #2451
1. Created a simple function for executor type as pool manager, just to check my changes didn't broke the existing functionality.
2. Created a function for executor type as new deployment with idle timeout of 60 sec, and then tested the function.
3. Created a function for executor type as new deployment with idle timeout of 60 sec, and then wait to terminate the pods, once the pod get terminated, now updated the function idle timeout to something else like 50 sec, and then test the …
> Pods immediately terminate for idletimeout in new deployment and container executer type

- pkg/fission-cli/util/portforward.go
Fission CLI get time out in port forwarding, currently the timeout for port forwarding is 1 ms.
This fix will increase the port forwarding time initially to 5 sec, and then time will increase exponentially like 10, 20, 40 and so on.
Fixes # https://github.com/fission/fission/issues/2462
forward the port of controller and test changes for the same.
> Increase time for port forwarding

- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/create_test.go
- pkg/fission-cli/cmd/package/create.go
While creating a package if package name is more than 63 characters, then package get failed.
This fix will allow to create a package even if package name is more than 63 characters by taking first 26 characters as package name and appending unique id to it, and will trim rest of the characters of package name.
Fixes # https://fissionio.slack.com/archives/C3LUX6BBP/p1657148131481119
Created a simple function with function name less than 63 characters.
Created a function with function name more than 63 characters.
Created a function using spec with function name less than 63 characters.
Created a function using spec with function name more than 63 characters.
Created a package manually with package name less than 63 characters.
Created a package manually with package name more than 63 …
> Generate package within 63 character limit when creating function

- crds/v1/fission.io_packages.yaml
- pkg/apis/core/v1/types.go
Package resource get stuck in Pending state if package resource is being created without fission CLI. For fission CLI it's working fine.
This issue is occurring because of ambiguous value of BuildStatus in CRD. This fix will change the value of BuildStatus and use the same value everywhere.  
Fixes #2488
> Package resource get stuck in Pending state when created without Fission CLI

- pkg/fission-cli/cmd/function/create.go
1. add check to ensure proper error message is shown when user is trying to create function with executor type container
2. add hint to the actual command
Fixes #2463
> Prevent creating function of executor type container via fn create command

- pkg/router/router.go
Whenever github action workflow run then workflow show an error message "ERROR fission-bundle/main.go:52 failed to parse tracing sampling rate from 'TRACING_SAMPLING_RATE'". Since we are no more using TRACING_SAMPLING_RATE environment variable so it will be better to remove from the code.
This fix will remove the mentioned above error during github action workflow.
Fixes # https://github.com/fission/fission/issues/2496
> removed unused reference of TRACING_SAMPLING_RATE

- charts/fission-all/values.yaml
Update Keda connector versions
- kafka: v0.11
- rabbitmq: v0.10
- awskinesis:  v0.10
- aws_sqs: v0.10
- nats_steaming: v0.12
- gcp_pubsub: v0.5
- redis: v0.3
> Update keda connector versions

- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr_test.go
- pkg/executor/executortype/poolmgr/gpm.go
Configmap inside pods for newdeploy and pool manager executor type, were not being updated if user update the configmap.
This fix will help to update the pods for both executor type with new configmap. As per the changes if there is any configmap update then pods will get restarted for both executor type and then it will refer new configmap.
Created two function for new deploy and attached with the same configmap and then updated the configmap, now new deploy pods got restarted and configmap got updated.
> Ensure newdeploy function pod restart on referred configmap update

- pkg/mqtrigger/messageQueue/kafka/consumer.go
- pkg/mqtrigger/metrics.go
These changes have specifically made for kafka. This will expose a new metric named as fission_mqt_message_lag, that will show total number of messages lag per topic and partition.
We can use this metric in auto scaling of pod for new deploy type executor function.While creating a new deploy function we need to add hpa metrics of external type inside function definition.
```
hpaMetrics:
- type: External
external:
metric:
name: fission_mqt_message_lag
selector:
matchLabels:
trigger_namespace: default
trigger_name: kafkatest
target:
type: AverageValue
averageValue: 40
```
Note - value for trigger_namespace(under matchLabels) must be same as namespace in which trigger has been created and trigger_name must be the name of trigger.
Setup prometheus first and then we will be creating a …
> Add metric fission_mqt_message_lag for kafka mqt connector 

- .github/workflows/release.yaml
- hack/build-yaml.sh
Adds yaml manifests for direct install, Minikube and OpenShift to the releases generated by Github Actions
Tested on my fork [github.com/kanuahs/fission](https://github.com/kanuahs/fission/actions/workflows/release.yaml) by running multiple times.
> Add yaml manifest generation for CI releases

- pkg/executor/client/client.go
Span for executor and fetcher was missing from router tracing.
We have injected otelhttp transport in executor, After this fix user will be able to see all the traces from router itself.
Fixes https://github.com/fission/fission/issues/2545
Attached is the image before and after making changes.
Before changes
After changes
> Inject open telemetry(OTEL) transport in executor

- skaffold.yaml
we are using the `--force` flag on upgrade. This essentially means calling `helm upgrade --force` which will make helm force resource updates through a replacement strategy. This is resulting in errors as dynamically provisioned PVCs cannot be replaces as certain values are immutable
Fixes #2362
> Remove `--force` option from upgrade strategy in skaffold.yaml - fix #2362

- pkg/fission-cli/cmd/environment/delete.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/util/util.go
Removed extra warning message while creating HTTP trigger. And updated some verbose logs to show info related to namespace.
None
Create httptrigger and check logs
> Improve warning/verbose messages around namespace in Fission CLI

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/controller/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/kubewatcher/deployment.yaml
- charts/fission-all/templates/mqt-fission-kafka/deployment.yaml
- charts/fission-all/templates/mqt-keda/deployment.yaml
- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/templates/storagesvc/deployment.yaml
- charts/fission-all/templates/timer/deployment.yaml
- charts/fission-all/values.yaml
- pkg/apis/core/v1/const.go
- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/pkgwatcher.go
- pkg/canaryconfigmgr/canaryConfigMgr.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr_test.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/executortype/poolmgr/poolpodcontroller_test.go
- pkg/mqtrigger/mqtmanager.go
- pkg/mqtrigger/scalermanager.go
- pkg/router/functionReferenceResolver.go
- pkg/router/httpTriggers.go
- pkg/utils/informer.go
These changes will allow to configure CRD resources according to namespaces. Previously CRD could have only be configured in default namespace provided by user in values.yaml file under defaultNamespace field.
Helm Changes
We have added two new field in helm.
1. additionalFissionNamespaces: [] - This will be a type of array, where user can provide multiple namespaces.
eg-
```
additionalFissionNamespaces: 
- namespace1
- namespace2
- namespace3
```
2. singleDefaultNamespace: boolean - This will be a boolean value and default value will be true. If this field sets to true then fission will always use only default namespace provided by user under defaultNamespace field. If this set to false then fission will use namespaces defined in additionalFissionNamespaces field along with …
> Allow namespace configuration for different CRD resources in Fission

- .github/workflows/push_pr.yaml
- pkg/fission-cli/util/util.go
Fission falied to list resources in default or all-namespaces, if namespace flag is not provided and current-context namespace is not set **OR** namespace flag is not provided and FISSION_DEFAULT_NAMESPACE environment variable not set.
These changes will set namespace as default in case of no namespace is available and will list resources in the default or all namespace if namespace flag is not provided.
Fixes https://github.com/fission/fission/issues/2578
> Fission failed to list resources if namespace flag is not provided

- pkg/executor/executortype/newdeploy/newdeploymgr.go
> List Fission resource for specific namespace in newdeploy reaper 

- pkg/buildermgr/pkgwatcher.go
If we create any function other than the default namsespace then package status always show in pending state.
These changes will run package informers in go routine. 
Fixes #
> Package status is in pending state if package get created other than default namespace

- pkg/executor/cms/cmhandler.go
- pkg/executor/cms/cmscontroller.go
- pkg/executor/cms/secrethandler.go
- pkg/executor/executor.go
We allow functions to refer configmap/secrets. We are monitoring all namespaces for configmaps and secrets and also allow cross-namespace references.
This fix monitors configmaps/secret updates in specific namespaces. Also, we ignore cross-namespace references for configmap/secret updates.
Fixes #
> Monitor specific namespaces for configmap/secret updates

- cmd/preupgradechecks/checks.go
- pkg/buildermgr/pkgwatcher.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/reaper/reaper.go
- pkg/router/functionReferenceResolver.go
- pkg/storagesvc/archivePruner.go
Fixes #
Created two environment in go. One in default namespace and second in testns1 namespace.
Created 1 pool manager executor type function in each environment.
Verified that all the deployment, services etc for function created inside testns1 namespace, were created inside testns1 namespace.
Tested both functions individually and verified that idle object reaper is reaping pods in their respective namespaces.
Created 1 newdeploy executor type function in each environment.
Tested both functions individually and verified that idle object reaper is reaping pods in their respective namespaces according to their idletimeout .
Performed same steps for python environment as well,
> List fission resources in specific namespace instead of all namespace

- pkg/fission-cli/util/util.go
- pkg/router/httpTriggers.go
Exposed a version API on router to fetch server version info.
Used the API from CLI instead of using controller APIs
Fixes #
> Add Fission version API to router for CLI consumption

- pkg/buildermgr/envwatcher.go
fission env delete -> deletes wrong builder service in case of multiple environment.
These changes will select the and delete the builder service that is associate with environment name using environment label.
Fixes  https://github.com/fission/fission/issues/2615
> Delete builder service associated with environment name

- pkg/fission-cli/cmd/function/log.go
- pkg/fission-cli/cmd/kubewatch/command.go
Use namespace flag (--namespace) from the global options for watch command instead of local flag for specifying ns value.
Fixes #
https://github.com/fission/fission/issues/2595
use: -n or --namespace flag for specifying namespace value in `watch` command. 
eg, `fission watch list -n ns1`
> use namespace flag from global options for watch command

- pkg/apis/core/v1/function_webhook.go
Validation will make sure that functions and its corresponding secrets/configmaps are present in same namespace.
This helps in achieving multi-tenancy goals
Fixes #
> Validation to allow functions use secrets/configmap from function's namespace 

- pkg/healthcheck/healthcheck.go
Removed CLI check for controller in  `fission check` command  as Controller is deprecated from 1.18-rc1 release. 
Fixes #
> Remove healthy Controller check in CLI `fission check` command 

- go.mod
- go.sum
- pkg/router/httpTriggers.go
We run a Fission deployment with about 12k functions and 12k triggers.
When the K8S Informers for HTTPTrigger and Function are instantiated their state is synchronized by calling the `AddFunc` event handler for each function and trigger. In our deployment, this means 24k calls to `syncTriggers`.
Every time `syncTriggers` is called the router's `Mux` is rebuilt from scratch as part of `getRouter`.
In our deployment, this causes our routers to max out their CPU for a couple hours after they are rebooted. The routers are still able to serve traffic while this is happening, but they time out many more requests than they should.
We have this code running in production and the results were immediately visible. All of our router pods were rebooted without any kind of significant CPU usage.
> Add sync triggers debounce in router

- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/log.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/fission-cli/logdb/influxdb.go
- pkg/fission-cli/logdb/kubernetes_log.go
- pkg/fission-cli/logdb/logdb.go
- test/upgrade_test/fission_objects.sh
- Handle error while fetching logs
- use %s instead of %v while printing data to CLI
- use correct time to fetch updated logs 
- add `--all-pods` flag-
- all-pods= true - fetches logs from all the Pods which are running for the Fission function. 
- all-pods= false(**default value**) -  fetches logs for latest pod which was running for the function
eg of `fn log` command with `--all-pods` flag,
Fixes #
> Handle logs from all pods in function and error condition in fission fn log command

- charts/fission-all/values.yaml
- skaffold.yaml
We enable security context by default now, so that fission pod do not have root access to system.
Fixes #
> Enable security context by default

- pkg/apis/core/v1/const.go
- pkg/logger/logger.go
- pkg/utils/informer.go
> K8s informer to work with specific namespaces for logger

- pkg/fission-cli/cmd/support/dump.go
- pkg/fission-cli/cmd/support/resources/crd.go
- pkg/healthcheck/healthcheck.go
add canary config in dump
check `webhook` server is running fine
eg,
also,
`fission check -v 2` gives info about Fission version  
Fixes #
> add version info in fission check CLI

- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/pkgwatcher.go
With the support of multi tenancy, fission will work with roles instead of cluster roles. And to achieve this fission needs to work with only specific namespaces instead of all namespaces.
With these changes informers for builder manager will work only in specific namespaces as provided by user in helm chart.
Fixes #
> K8s informer to work with specific namespaces for builder manager

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/buildermgr/role-kubernetes.yaml
- charts/fission-all/templates/controller/role-kubernetes.yaml
- charts/fission-all/templates/executor/role-kubernetes.yaml
To support the backward compatibility, fission should allow to create environment and builder pods in their respective namespaces as mentioned by user in helm chart.
As of now fission is not able to create environment/builder pods inside functionNamespace and builderNamespace, if value for singleDefaultNamespace is set to true in helm chart.
With these changes roles will get get created inside  functionNamespace and builderNamespace as mentioned by user in helm chart and fission will be able to create environment and builder pods in their respective namespaces.
Fixes #
> Generate kubernetes roles in fission-function and fission-builder namespace

- charts/fission-all/templates/buildermgr/configmap.yaml
- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/executor/configmap.yaml
- charts/fission-all/templates/executor/deployment.yaml
- go.mod
- pkg/apis/core/v1/const.go
- pkg/buildermgr/buildermgr.go
- pkg/executor/executor.go
- pkg/executor/executortype/newdeploy/newdeploymgr_test.go
- pkg/executor/util/util.go
- pkg/executor/util/util_test.go
- pkg/utils/utils.go
If the user wants to patch all function pods or builder pods, he can configure the runtime pod spec patch or builder pod spec patch.
As of now, we are reading config maps with data directly. Because of this executor/builder need to get permission to confimap in the fission namespace.
Trying to avoid this permission with the fix and mounting configmap data directly.
Fixes #
> Consume podspec patch directly on executor/builder mounts

- pkg/crd/client.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr_test.go
- pkg/executor/executortype/poolmgr/funchandlers.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/executortype/poolmgr/poolpodcontroller_test.go
- pkg/mqtrigger/scalermanager.go
- Pass the informer factory directly to all executors instead of individual informers
- Factory registers informers based on references
- We make a start call on the factory. Whichever informers are registered will be started
- Run function informer handlers in pool pod controller only if istio enabled
- Fix default namespace hardcoding in WaitForCRDs and mqt scalar manager code
Fixes #
> Executor user informer factory in executors in place of informers

- pkg/router/httpTriggers.go
As we already register Otel handler at router level here https://github.com/fission/fission/blob/300739c031cd34e6f2f0b2e804d218303fa16423/pkg/router/router.go
We don't need to define an Otel handler for the function handler level. 
Initial analysis was done by Alex
https://fissionio.slack.com/archives/C3LUX6BBP/p1670500425911999
Fixes #
All span connections working properly.
> Remove otel handler per function handler in router

- charts/fission-all/templates/_function-access-role.tpl
- charts/fission-all/templates/misc-functions/role.yaml
- charts/fission-all/templates/misc-functions/rolebinding.yaml
- pkg/fetcher/fetcher.go
As we have removed creating role and role bindings through backend code, So we need to make sure all role and role binding should get created through helm chart.
Currently fission is not able to create package for functions other than default namespace because of missing role and role binding of event-fetcher.
Now we have added roles and role binding for event-fetcher and with these changes fission will now able to create package for functions in multiple namespaces.
Fixes #
> Create role and rolebinding for event-fetcher in multiple namespaces

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/buildermgr/role-fission-cr.yaml
- charts/fission-all/templates/buildermgr/role-kubernetes.yaml
- charts/fission-all/templates/canary-config/role-fission-cr.yaml
- charts/fission-all/templates/canary-config/role-kubernetes.yaml
- charts/fission-all/templates/controller/role-fission-cr.yaml
- charts/fission-all/templates/controller/role-kubernetes.yaml
- charts/fission-all/templates/executor/role-fission-cr.yaml
- charts/fission-all/templates/executor/role-kubernetes.yaml
- charts/fission-all/templates/fluentbit/role-kubernetes.yaml
- charts/fission-all/templates/kubewatcher/role-fission-cr.yaml
- charts/fission-all/templates/kubewatcher/role-kubernetes.yaml
- charts/fission-all/templates/misc-functions/role.yaml
- charts/fission-all/templates/misc-functions/rolebinding.yaml
- charts/fission-all/templates/mqt-fission-kafka/role-fission-cr.yaml
- charts/fission-all/templates/mqt-fission-kafka/role-kubernetes.yaml
- charts/fission-all/templates/mqt-keda/role-fission-cr.yaml
- charts/fission-all/templates/mqt-keda/role-kubernetes.yaml
- charts/fission-all/templates/pre-upgrade-checks/role-fission-cr.yaml
- charts/fission-all/templates/router/role-fission-cr.yaml
- charts/fission-all/templates/router/role-kubernetes.yaml
- charts/fission-all/templates/storagesvc/role-fission-cr.yaml
- charts/fission-all/templates/timer/role-fission-cr.yaml
- charts/fission-all/templates/timer/role-kubernetes.yaml
- charts/fission-all/values.yaml
- pkg/utils/serviceaccount.go
We have removed `singleDefaultNamespace` field from helm chart. Fission will work with both default and additional namespace(if values present in additional namespace).
Fixes #
> Remove singleDefaultNamespace field from helm chart

- charts/fission-all/values.yaml
- pkg/utils/serviceaccount.go
- pkg/utils/serviceaccount_test.go
- Allow setting interval to 0 so that service account check only once
- Set namespace in LocalSubjectAccessReview 
- Change log level to Info for important logs
Fixes #
> Allow service account check to run only once at start of executor

- pkg/timer/timerSync.go
Signed-off-by: Shubham Nazare <shubham4443@gmail.com>
Simply removed the condition.
Fixes #2596
> Fix issue with updating timetrigger without --cron flag

- charts/fission-all/templates/analytics/nonhelm-install-job.yaml
- charts/fission-all/templates/analytics/post-install-job.yaml
- charts/fission-all/templates/analytics/post-upgrade-job.yaml
- charts/fission-all/templates/fluentbit/fluentbit.yaml
- charts/fission-all/templates/influxdb/deployment.yaml
- charts/fission-all/templates/pre-upgrade-checks/pre-upgrade-job.yaml
Some pods in the helm chart do not use the image pull secrets defined in the values. This adds the required sections to make use of the image pull secrets in the respective pods.
As requested in https://github.com/fission/fission-charts/pull/68 I created a new pull request in this repo.
> fix: add missing imagePullSecrets sections to pods

- go.mod
- go.sum
- pkg/apis/core/v1/timetrigger_webhook.go
- pkg/apis/core/v1/validation.go
- pkg/controller/timeTriggerApi.go
- pkg/fission-cli/cmd/timetrigger/create.go
- pkg/fission-cli/cmd/timetrigger/test.go
- pkg/timer/timer.go
1. Updated the robfig/cron module to the latest v3
2. Added support for writing cron syntax in its standard format i.e. (Min Hour DoM Month DoW)
3. Cron can still be written in the previous 6 fields format with the seconds field as optional.
Fixes #1813
> Change cron syntax to standard format

- pkg/executor/executortype/container/deployment.go
Signed-off-by: saltbo <saltbo@foxmail.com>
nil panic for the latestDepl.Name if not return in the for cycle
Fixes #2681
> fix: nil panic for the latestDepl.Name if not return in the for cycle

- pkg/executor/fscache/functionServiceCache.go
- pkg/executor/fscache/poolcache.go
- pkg/executor/fscache/poolcache_test.go
Merged pool cache package into fscache to avoid import cycle. Also changed all types in pool cache from interface to specific types.
Fixes #
> internal: Making poolcache typed and merge into fscache

- pkg/fission-cli/util/util.go
If authentication.enabled is set to true in helm chart then fission version failed to show result for server version. This happens due to authorization header is not being pass to router handler that contains bearer token.
With these changes we have added authorization header to be sent in router. Now If authentication is enabled then token will get validated.
Fission user needs to set FISSION_AUTH_TOKEN as environment variable. Go through this link to generate token.
https://fission.io/docs/installation/authentication/#generating-auth-token
Fixes https://github.com/fission/fission/issues/2691
> Fission version failed if authentication.enabled is set to true

- charts/fission-all/templates/router/secret.yaml
This issue occurs only during helm upgrade if authentication is enabled, router pod fails to run because of secret for router is not available. This issue happen because template rendered before creating a secret for router during helm upgrade.
With these changes, we will make sure secret for router should get created before rendering the router templates. 
Fixes https://github.com/fission/fission/issues/2690
> Secrets for router not created if authentication is enabled during helm upgrade

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/analytics/nonhelm-install-job.yaml
- charts/fission-all/templates/analytics/post-install-job.yaml
- charts/fission-all/templates/analytics/post-upgrade-job.yaml
- charts/fission-all/templates/mqt-fission-kafka/deployment.yaml
- charts/fission-all/values.yaml
- skaffold.yaml
- test/upgrade_test/fission_objects.sh
We have changed our release process to push fission images to github container registry(ghcr.io) instead of docker.io. So now in order to pull fission images from ghcr.io, we need to make changes in helm chart.
This PR includes changes in helm chart to pull images from ghcr.io.
> Make ghcr.io to default container registry

- charts/fission-all/templates/router/role-kubernetes.yaml
Currently when user create ingress for router then they get an error `cannot create resource "ingresses" in API group "networking.k8s.io" in the namespace "fission` This error occurs because currently router don't have any permissions to create any k8s resources in the release namespace(where fission is installed)
This PR include changes to create necessary permission to allow router to create ingress resource in release namespace.
Fixes https://github.com/fission/fission/issues/2708
> Allow permission to router for ingress resources in release namespace

- pkg/fission-cli/cmd/function/test.go
Currently if user define function timeout(--fntimeout) while creating function to execute function for a long time and test function using fission-cli then function doesn't consider value of fntimeout and terminate in middle of processing even after defining functionTimeout.
These changes will make sure function should wait till the fntimeout is reached.
> CLI: Use fntimeout to stop terminating of function in middle

- pkg/executor/fscache/poolcache.go
Introduce a new structure in executor poolcache in order to store the function svc details 
#1939
> Add funcSvcGroup type in pool cache for grouping of function services

- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/executortype/poolmgr/readyPodController.go
Signed-off-by: Nikhil Sharma <nikhilsharma230303@gmail.com>
This PR stops pod specialization when the pod namespace and cm/secret namespace are mismatched in the case of **poolmgr**.
> poolmgr: stop pod specialization when pod namespace and cm/secret namespace is mismatched

- pkg/executor/executortype/poolmgr/gpm.go
Websocket event listener uses wrong event name in  `NoActiveConnectionEventChecker` . 
It cause pod being killed immediately.
Fixes https://github.com/fission/fission/issues/2743
This is a obvious bug. Maybe a typo
update: I run a websocket function on this fix with idletimeout = 120s, it keep alive for more than  5min.
> Wrong event name in websocket event listener

- pkg/utils/httpserver/server.go
This PR ensures to pass the correct value of addr in case when port is passed in `host:port` format in the [StartServer](https://github.com/fission/fission/blob/main/pkg/utils/httpserver/server.go#L11) func.
Fixes #2744
> handle addr when port is passed in host:port format in the StartServer func

- pkg/error/httperror.go
- pkg/error/httperror_test.go
The old unwrap code is invalid for the `Error` when the error is wrapped by the `errors.Wrap`.
As a result, the error code returned is always 500
Fixes #
> Invalid error unwrap for the httperror

- pkg/utils/metrics/http_metrics.go
- pkg/utils/metrics/http_metrics_test.go
No Flush implement for the metric middleware cause not support chunked response for the router
Fixes #2767
> fix: add flush to support chunked for the metric middleware

- pkg/fission-cli/cmd/environment/create.go
- pkg/fission-cli/cmd/environment/update.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/run_container.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/httptrigger/update.go
- pkg/fission-cli/cmd/kubewatch/create.go
- pkg/fission-cli/cmd/mqtrigger/create.go
- pkg/fission-cli/cmd/mqtrigger/update.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/package/update.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/cmd/timetrigger/create.go
- pkg/fission-cli/cmd/timetrigger/update.go
Signed-off-by: Nikhil Sharma <nikhilsharma230303@gmail.com>
This PR adds the functionality to update the specs of the fission CRs. And also stops the updation of fission resources on the server when `fission update % --spec` is used.
Fixes #2526
> add functionality to update spec of fission custom resources

- pkg/executor/api.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/executortype.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/fscache/functionServiceCache.go
- pkg/executor/fscache/poolcache.go
- pkg/executor/fscache/queue.go
- pkg/executor/fscache/queue_test.go
This PR adds a couple of fixes to handling specialization failures.
- Cleanup svc waiting for the counter in the pool manager if specialization fails 
- Cleanup active requests counter in pool manager if client exists the demand for function service while we have allocated function service
- Consider specialization timeout if pod ready timeout > specialization timeout in waiting for ready pod. We also consider if the request to choosePod is cancelled.
- We ensure if we have requests waiting for service requests but if there is no pod in the specialization we clean up those.
> Ensure handling for specialization failure in pool manager

- pkg/executor/api.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/executortype.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/fscache/functionServiceCache.go
- pkg/executor/fscache/poolcache.go
- pkg/executor/util/util.go
These changes will help to dump some necessary information to debug executor. Currently we will be supporting dump of pool manager functions only.
A new dump file will get created for every request under temporary directory of executor pod.
Dump file name will be in the format of fission-dump-*.txt
* -> asterisk represents unique id, that will be unix timezone.
To get the dump, user needs to hit HTTP end point for executor.
End point - /v2/debugInfo
Fixes #
> Executor: Dump function service cache for pool manager functions

- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/values.yaml
This is a port of https://github.com/fission/fission-charts/pull/66
> When deploying the router with deployAsDaemonSet: false, it would be useful to be able to specify how many router replicas would be deployed.
> Configure router deployment replicas

- .github/workflows/push_pr.yaml
we are recently observing CI failures for kind version v1.19.16, Prometheus community have recently released a newer version and that might cause this CI failure.
We have changed prometheus version to 45.28.0 in this PR.
> Changed prometheus version from latest to 45.28.0

- pkg/builder/client/client.go
Not show the build log when all build retries failed.
```bash
Name:        helloworld-e53d4ff5-4d46-42e5-8191-06ce2a2956bf
Environment: go
Status:      failed
Build Logs:
Error building deployment package: Post "http://go-32450.default:8001": POST http://go-32450.default:8001 giving up after 5 attempt(s)
```
Fixes #
> fix: passthrough the build error log 

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/controller/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
Ensure all Namespace related environment variables are passed to the Fission Deployments.
As part of starting the services, CRDs are checked, which requires the correct `FISSION_DEFAULT_NAMESPACE` be set.
Move all Namespace related environment variables to the 'fission-resource-namespace' macro to ensure all services know the relavant namespaces.
Fixes #2732
Tested running in a cluster that doesn't use the `default` namespace; ie:
```yaml
defaultNamespace: tenant-user-funcs
```
> fix missing namespace environment variables for various services

- Makefile
- crds/v1/fission.io_functions.yaml
- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/zz_generated.swagger_doc_generated.go
- pkg/buildermgr/envwatcher.go
- pkg/crd/key.go
- pkg/executor/api.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/executortype.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/fscache/functionServiceCache.go
- pkg/executor/fscache/functionServiceCache_test.go
- pkg/executor/fscache/poolcache.go
- pkg/executor/fscache/poolcache_test.go
- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/router/functionHandler.go
- pkg/timer/timer.go
- pkg/timer/timerSync.go
- added retainPods flag to take in the number of specialized pods to retain
- add retainPods in both the create function and update function command
- modify crd keys to be typed instead of string
- keep track of function generation in case of update function operation
- add delete handler function to make sure specialized pods are deleted in case function is deleted
Fixes #2840
> Ability to retain specialised pods for poolmanager functions

- crds/v1/fission.io_functions.yaml
- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/zz_generated.deepcopy.go
- pkg/executor/reaper/reaper.go
- pkg/executor/util/hpa/hpa.go
- pkg/executor/util/hpa/hpa_test.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/function_test.go
- pkg/fission-cli/cmd/support/resources/kubernetes.go
- pkg/utils/otel/attributes.go
This PR update the Kubernetes Autoscaling API to v2.
This allow support for Kubernetes cluster in version v1.26 and latest. However, this drop the support for Kubernetes clusters in version under v1.23
Fixes #2722
Fixes #2838
- Unitests with `./hack/runtests.sh`
- Builded the `fission/fission-bundle` image locally with `goreleaser` and replaced the `executor` image
- Deployed the following function :
```bash
fission env create --name nodejs --image fission/node-env --poolsize 1 --version 3
fission function create --name hello-js --env nodejs --code  functions/hello.js --minscale=0 --maxscale=5 --executortype newdeploy
```
- Verify :
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", …
```
> Update the Kubernetes autoscaling API to v2 (#2722)

- charts/fission-all/templates/router/role-kubernetes.yaml
Avoid unnecessary role and rolebinding creation for router . 
We are creating role and rolebinding in release namespace for router which is not required and causes installation issue when release namespace and default namespace is same.
Fixes https://github.com/fission/fission/issues/2855
> Avoid duplicate role in release namespace for router

- cmd/builder/app/server.go
- cmd/builder/main.go
- cmd/fetcher/app/server.go
- cmd/fetcher/main.go
- cmd/fission-bundle/main.go
- cmd/fission-bundle/mqtrigger/mqtrigger.go
- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/pkgwatcher.go
- pkg/executor/api.go
- pkg/executor/executor.go
- pkg/mqtrigger/mqtmanager.go
- pkg/router/auth_test.go
- pkg/router/mutablemux_test.go
- pkg/router/router.go
- pkg/storagesvc/client/storagesvc_test.go
- pkg/storagesvc/storagesvc.go
- pkg/utils/httpserver/server.go
- pkg/utils/httpserver/server_test.go
- pkg/utils/manager/manager.go
- pkg/utils/manager/manager_test.go
- pkg/utils/metrics/server.go
- pkg/utils/profile/profile.go
- test/e2e/cli/cli_test.go
- test/e2e/framework/services/services.go
right now **ctx.Done()** is being used to ensure that we pass the cancellation signal to all the go routines but there is no mechanism to wait for the completion of all the running go routines.
This PR adds a manager which can be used to wait for go routines to be finished when context is cancelled.
manager's Add function can be used to start a go routine and then at the end when the context is cancelled manager's Wait function can be used to wait for the go routine to finish.
Fixes #
> added manger to wait for go routines to finish

- pkg/executor/fscache/poolcache.go
- pkg/executor/fscache/poolcache_test.go
Earlier we made fixes for #1939 and #2452
As part of the above issues, we added more swift way to handle concurrency https://github.com/fission/fission/pull/2737
and reduce bursts in pod specialization when initial bulk calls are made to the function.
In the earlier approach, we used all the capacity of a single pod(actual + virtual) and then used to specialize further pods.
This causes failure of requests if specific pod specialization fails.
This PR changes the approach a bit and uses concurrency aggressively until a point it is available(to the limit). Once we exhausted concurrency we consider using the virtual capacity of the pods until specialization finishes.
Combining this and old approach will ensure we specialize pods as much as possible and then switch to virtual capacity up to …
> Use concurrency in poolmanager as per old behaviour

- charts/fission-all/templates/router/secret.yaml
- charts/fission-all/values.yaml
Removed jwtSigningKey default value from values.yaml and modified router secret to generate jwtSigningKey randomly if not passed in values.yaml
Removed the default value set for jwtSigningKey in values.yaml file and added option to generate it randomly if not passed by in router secret.
Fixes #
> Router authentication jwtSigningKey unique for every Fission installation 

- pkg/buildermgr/pkgwatcher.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/canaryconfigmgr/canaryConfigCache.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/fscache/functionServiceCache.go
- pkg/router/functionReferenceResolver.go
- pkg/router/functionServiceMap.go
Making typed common cache with generics so that we don't use wrong types
across set/get methods and more higher level methods can be
defined for the cache.
Currently, we are not able to operate over all keys of the cache due to generic types.
Primary changes made in [pkg/cache/cache.go](https://github.com/fission/fission/pull/2896/files#diff-964e351ee2375d359c78d69e514c4edc42577219761c4475f391ed2daf715e51)
Fixes #
> Make common cache typed with generics

- pkg/apis/core/v1/package_webhook.go
If a package has deployment already, we should set the package status to none instead of pending. If we have a package that has source, we set the status to pending. If both source and deployment are empty, the package is marked as failure.
Fixes #
> Set default package status to none if deployment exists

- go.mod
- pkg/fission-cli/cmd/check/check.go
- pkg/fission-cli/util/constants.go
- pkg/healthcheck/healthcheck.go
- test/e2e/cli/cli_test.go
`fission check` command does not work outside of "fission" namespace. If user provides namespace then use it for running `fission check` command otherwise use `fission` as default namespace.
Fixes #2924
- Fission installed in `fission` namespace.
```
$ fission check
fission-services
--------------------
√ executor is running fine
√ router is running fine
√ storagesvc is running fine
√ webhook is running fine
fission-version
--------------------
√ fission is up-to-date
```
- Fission installed in `check` namespace.
```
$ fission check
fission-services
--------------------
× failed to get executor deployment status
× failed to get router deployment status
× failed to get storagesvc deployment status
Error: Error found: failed to get webhook deployment status
× failed to get webhook …
```
> Fix `fission check` command doesnt work for namespace other than `fission`

- pkg/fission-cli/cmd/package/get.go
- pkg/fission-cli/util/constants.go
- test/e2e/cli/cli_test.go
- Fix CLI command `pkg getsrc` to return source archive instead of deploy archive.
- If source archive is not available then return deploy archive.
Fixes #2839
```
$ fission package getsrc --name hello-py-06b10319-a196-4c84-819f-0238dc09100c
def main():
return "Python, world!\n"
```
```
$ fission package getsrc --name hello-go-c38b5bc1-3a1e-467d-b2da-9d74f9c82af0 
package main
import (
"net/http"
)
// Handler is the entry point for this fission function
func Handler(w http.ResponseWriter, r *http.Request) {
msg := "Hello, world!\n"
w.Write([]byte(msg))
}
```
> Fix CLI command `pkg getsrc` returns deploy archive instead of source archive

- pkg/fission-cli/cmd/spec/apply.go
Fixes `fission spec apply --delete`  failing to delete environments.
There was a typo in `pkg/fission-cli/cmd/spec/apply.go`: the environment namespace was being used rather than the environment name.
Fixes #2942
Tested manually. The example case in #2942 no longer fails, and the environment is correctly deleted.
> Fix `fission spec apply --delete` deleting environments

- pkg/fission-cli/cmd/environment/create.go
- pkg/fission-cli/flag/flag.go
- test/e2e/cli/cli_test.go
Make latest envVersion 3 as default version.
Fixes #
Now we can create env pods with poolsize=1 
```
fission env create --name go --image fission/go-env-1.16 --builder fission/go-builder-1.16 --poolsize 1
```
```
$ kubectl get po
NAME                                         READY   STATUS    RESTARTS   AGE
go-564499-69b8db6f7-ltzhp                    2/2     Running   0          73s
poolmgr-go-default-564499-79c65c544b-mpmlz   2/2     Running   0          73s
```
> Set latest envVersion 3 as default

- charts/fission-all/templates/webhook-server/webhooks.yaml
- test/e2e/framework/webhook-manifest.yaml
This PR resolves an issue with Fission where the existing MutatingWebhookConfiguration conflicts with other packages like Rancher. The name of the MutatingWebhookConfiguration was changed from mutating-webhook-configuration to fission-mutating-webhooks to avoid conflicts.
Fixes #2920 
Modified the mutating webhook configuration name and verified that Fission installs without errors on kind using skaffold:
```
➜  fission git:(fix/helm-webhook-conflict-rancher) k get MutatingWebhookConfiguration
NAME                        WEBHOOKS   AGE
fission-mutating-webhooks   1          47s
➜  fission git:(fix/helm-webhook-conflict-rancher) helm list -n fission -oyaml
- app_version: v1.20.1
chart: fission-all-v1.20.1
name: fission
namespace: fission
revision: "1"
status: deployed
updated: 2024-05-27 …
```
> Fix: MutatingWebhookConfiguration naming conflict

- pkg/fission-cli/cmd/package/util/util.go
issue: #2938
Fixed an error when using the command to download src
Fixes #2938
> Fixed an error when using the command to download src

- pkg/buildermgr/envwatcher.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/container/deployment.go
- pkg/executor/executortype/container/svc.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/util/hpa/hpa.go
- pkg/executor/util/hpa/hpa_test.go
- Set OwnerReferences to Poolmanager and builderManager deployment and service created by environment.
- Set OwnerReferences to deployment, service and HPA created by newdeploy function.
- Set OwnerReferences to builderManager deployment and service created by environment.
- Set OwnerReferences to deployment, service and HPA created by container function.
Fixes #2962 
`OwnerReferences` are added for poolmanager deployement as follows:
```
$ kubectl get deploy poolmgr-go-122-default-253070 -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "1"
executorInstanceId: lpd23pfg
creationTimestamp: "2024-06-25T06:09:57Z"
generation: 1
labels:
environmentName: go-122
environmentNamespace: default
environmentUid: e833d7f4-27bf-4f0d-9fe5-9d6169246de7 …
```
> Set OwnerReferences to K8s resources created by Fission

- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/flag/flag.go
- `--yolo`, `--concurrency` and `--rpp` fields are only valid for executortype `poolmgr` only.
- Show warning to users if these field are used with other executortype.
- Update CLI `--help` page with this information.
Fixes #
```
$ fission fn create --help
Create a function (and optionally, an HTTP route to it)
Options:
--concurrency=500 (--con)             Maximum number of pods specialized concurrently to serve
requests (Only valid for executortype; `poolmgr`)
--requestsperpod=1 (--rpp)            Maximum number of concurrent requests that can be served by a
specialized pod (Only valid for executortype; `poolmgr`)
--onceonly=false (--yolo)             Specifies if specialized pod will serve exactly one request in
its lifetime (Only valid for executortype; `poolmgr`)
```
```
$ fission fn …
```
> Show warning that `--yolo`, `--concurrency` and `--rpp` fields are valid for executortype `poolmgr` only

- cmd/builder/app/server.go
- pkg/builder/builder.go
- pkg/builder/builder_test.go
- pkg/builder/client/client.go
- pkg/buildermgr/common.go
- pkg/fetcher/fetcher.go
- pkg/utils/utils.go
- Builder pod contains builder and fetcher containers and they share a volume.
- Builder build the packages and fetcher uploads the packages to storage service.
- In case of build/upload failure, packages remains in the shared volume. These packages are of no use and needs to be cleaned up. 
- Added a `Clean` API in builder package. This API will be called by `buildermgr` for deleting src pkg after pkg is build and deployment is uploaded. I wanted to delete the src package from builder pod directly after failed/successful build but `buildermgr` uses `retryablehttp` client so in case of build failure `buildermgr` will retry build by sending `Build` request.
- To delete deployment pkg, fetcher `UploadHandler` will delete the deployment pkg after successful/failed upload.
Fixes #2821
- Added …
> Fix: Storage leak in Builder and Fetcher

- .github/workflows/release.yaml
- .goreleaser.yml
- pkg/mqtrigger/messageQueue/kafka/consumer.go
- pkg/mqtrigger/messageQueue/kafka/kafka.go
- pkg/mqtrigger/metrics.go
- Creating large number of MQTs (10+) was making mqtrigger-kafka pod very slow.
- Due to this new MQTs were not creating and trigger processing for old MQTs was also not working.
- We have added two metrics for more visibility.
- `fission_mqt_inprocess` for total number of MQTs in active processing.
- `fission_mqt_status` for status of an individual trigger, 1 if processing otherwise 0..
Fixes #
- Tested on kind cluster by creating 100 MQTs.
- All 100 MQTs were created under five minutes and trigger processing was also working.
> Fixed mqtrigger scaling issue

- .goreleaser.yml
- Armv7 support is removed from Fission `v1.20.3` release.
- This PR removes armv7 references from `goreleaser.yml` file.
Fixes #
> Removed armv7 references from goreleaser file

- cmd/fission-bundle/mqtrigger/mqtrigger.go
- pkg/mqtrigger/mqtmanager.go
- pkg/mqtrigger/mqtmanager_test.go
- Creating 100 MQTs takes around 5 minutes of time.
- This PR introduces workqueue to be used by MessageQueueTriggerManager for create, update and delete of MQTs.
- For create and update, four workers will be running.
- This fix will bring down 100 MQTs creation time from 5 minutes to 1-1.5 minutes.
Fixes #
- Created 100 MQTs which took around 1-1.5 minutes of time.
- Trigger processing was also working..
> Creating large number of MQTs takes time

- pkg/fission-cli/cmd/environment/create.go
- pkg/fission-cli/cmd/environment/update.go
(1) There are misleading comments in the implementation of parameter parsing for creating environment through CLI. The specific content is shown in the following figure. Currently, the parameter EnvVersion is set to a default value of 3. When this parameter is not set when creating env, it will be set to 3. Only when manually setting -- version to 0 will this logic be followed. The current annotations do not match the current implementation and are misleading. It is recommended to delete them.
(2) There is redundant code in the specific implementation of updating the environment through CLI, as shown in the following figure:
Fixes #
> Removing comments from the environment creation process and eliminating redundant code during the update process

- pkg/fission-cli/cmd/mqtrigger/update.go
- pkg/mqtrigger/mqtmanager.go
- pkg/mqtrigger/mqtmanager_test.go
- pkg/mqtrigger/scalermanager.go
This PR fixes a couple of issues:
- Handle `mqt update` which is ignored in mqtManager.
- Update scalemanager to handle scenarios when mqtkind is updated from keda to fission and vice-versa.
- Fix short circuit evaluation in `mqt update` which may fail the metadata update. 
Fixes #
- Updated mqtkind from fission to keda and verified that `scaledobject`, `triggerauthentications` and `deployment` objects are being created.
- Updated mqtkind from keda to fission and verified that `scaledobject`, `triggerauthentications`  and `deployment` objects are being deleted.
- Verified mqt.Spec.Metadata is being updated.
> Fix: Message queue trigger update

- pkg/fission-cli/cmd/client.go
- The PR adds support to `fission-cli` to use in-cluster config if kubeconfig file is not found.
- Now fission-cli can be used to do CRUD operations on fission's resources from inside a pod using service account.
Fixes #2994
- Created ClusterRole, ClusterRoleBinding and a service account.
- Created a docker image of the fission-cli.
- Created a deployment with fission-cli docker image.
- Exec to fission-cli container and run fission commands.
```
/ # ./fission check -v 2
couldn't find kubeconfig file. Set the KUBECONFIG environment variable to your kubeconfig's path.
Using in-cluster config
In-cluster config default namespace "default"
fission-services
--------------------
√ executor is running fine
√ router is running fine
√ storagesvc is running fine
√ webhook is running fine …
```
> Use in-cluster config when kubeconfig file is not found

- charts/fission-all/templates/fluentbit/fluentbit.yaml
This change adds the fission-resource-namespace.envs helper to the logger (fluentbit) helm charts so that FISSION_RESOURCE_NAMESPACES is correctly exposed to the logger pod. This allows the logger to capture logs from functions that are running in non-default namespaces that are defined in additionalFissionNamespaces.
None
Deployed into EKS and checked that the logs are correctly captured from the non-default namespaces into influxdb.
> Add resource namespace to logger

- pkg/fission-cli/cmd/function/test.go
The time unit of 'function.Spec.FunctionTimeout' is second, but after conversion from the function time.Duration, the unit becomes nanosecond. So it needs to be repaired.
> Fixed time unit loss problem after converting time

- pkg/fission-cli/cmd/function/update.go
The function is updated without an "envNamespace" argument, so we need to remove that logic
> Fixed: Remove useless arguments when the function is updated

- crds/v1/fission.io_timetriggers.yaml
- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/zz_generated.swagger_doc_generated.go
- pkg/fission-cli/cmd/timetrigger/command.go
- pkg/fission-cli/cmd/timetrigger/create.go
- pkg/fission-cli/cmd/timetrigger/list.go
- pkg/fission-cli/cmd/timetrigger/update.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/generated/applyconfiguration/core/v1/timetriggerspec.go
- pkg/kubewatcher/kubewatcher.go
- pkg/publisher/publisher.go
- pkg/publisher/publisher_test.go
- pkg/publisher/webhookPublisher.go
- pkg/timer/timer.go
- test/e2e/cli/cli_test.go
- Timetrigger can only trigger a function by HTTP POST method and it can only trigger the root of the function. If function exposes some routes then timetrigger can not trigger those routes.
- This PR adds new flags `method` and `subpath` to timetrigger `create` and `update` commands. Now user can configure the HTTP `method` used to trigger the function and also configure a `subpath` to trigger an internal route exposed by the function.
Fixes https://github.com/fission/fission/issues/3011 https://github.com/fission/fission/discussions/3009
> Add `method` and `subpath` flags to timetrigger object for triggering a function

- .github/workflows/release.yaml
- .goreleaser.yml
- pkg/fission-cli/cmd/timetrigger/create.go
- Add SBOM for all binaries and container images
- Provenance generation and verification in the release pipeline.
- Removed docker registry image push, only kept GHCR now. Due to maintenance efforts.
Fixes #
Changes verified via Release https://github.com/sanketsudake/fission/releases/tag/v1.22.0-rc2
And image https://github.com/sanketsudake/fission/pkgs/container/fetcher/328810497?tag=v1.22.0-rc2
> Fix SBOM and provenance for releases 

- pkg/executor/cms/cmhandler.go
- pkg/executor/cms/secrethandler.go
When I debug executor pod logs, it logs many unrelated updated configmap logs, like this（other operator updates the configmap periodically in k8s）:
It make some trouble for me to find the logs I need. It should only debug log configmap/secret related the fission functions.
> Log only related configmap and secret

- pkg/fission-cli/cliwrapper/driver/cobra/cobra.go
The intention here should be to initialize a slice with a capacity of len(v)  rather than initializing the length of this slice.
The online demo: https://go.dev/play/p/q1BcVCmvidW
Fixes #
> fix: fix slice init length

- pkg/fission-cli/cmd/environment/create.go
If the users on the cluster are namespace scoped they will not have permission to list environments from other namespaces. As you removed the Namespace variable from createEnvironmentFromCmd the m.Namespace will always be the default. This will not allow users to use fission cli to create environments
Fixes #
> Update create.go to handle namespace isolation

- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/util/util.go
- pkg/fission-cli/cmd/spec/spec.go
fix executor container name is error when runtime container custom name， like this
Fixes #
I Have Tested This Fix In My Production Env.
- [ √ ] I ran tests as well as code linting locally to verify my changes. 
- [√ ] I have done manual verification of my changes, changes working as expected.
- [√  ] I have signed all of my commits.
> fix: custom runtime container name is invalid
