- controller/api.go
- fission/function.go
- fission/main.go
Opens the function source in an editor and updates the function with the new source.
> Add "fission function edit <function>" command

- README.md
Instead of getting curl involved just use kubectl
> README: use kubectl create -f http

- .travis.yml
- glide.yaml
- hack/verify-gofmt.sh
- poolmgr/gp.go
This PR need the admin to setup in travis-ci.org
fix https://github.com/platform9/fission/issues/25
> add travis integration test

- .travis.yml
- README.md
1. Added all 1.7 versions of go to test against
2. Added Travis badge for master branch
3. Travis Builds Activated
> #25 Continuous Testing

- environments/python3/server.py
- examples/python/requestdata.py
> Setup app.logger for python environment

- .gitignore
- environments/python3/Dockerfile
- environments/python3/requirements.txt
added libs:
httplib2
python-dateutil
requests==2.7.0
stevedore
websocket-client
ignored pycharm dirs from git
testing: created docker image using this.
> adding commonly used python libraries

- fission/httptrigger.go
- fission/main.go
"fission route update" can now be used to update a route to point to a
different function.
> Implement 'fission route update'

- poolmgr/gp.go
Fix pod leaks on errors in loading the user function.  Addresses a part of #21.
> Poolmgr: fix pod leak bugs on specializePod failure

- poolmgr/gp.go
> Wait for Pod IP while waiting for pod ready

- fission/environment.go
I also renamed image to envImg for consistency
> Error when env name/image not provided

- fission/function.go
- fission/main.go
Download, if URL is provided otherwise use standard file fetch method.
Testing Done:
Download and Update of function using URL and file path.
> function code download using HTTP URL

- environments/dotnet/ExecutorModule.cs
- environments/dotnet/FissionCompiler.cs
- environments/dotnet/FissionContext.cs
- environments/dotnet/README.md
- environments/dotnet/project.json
- examples/dotnet/arguments.cs
- examples/dotnet/helloworld.cs
- examples/dotnet/requestbody.cs
- examples/dotnet/requestheaders.cs
Added support for accessing basic http request information.
This pull request adds basic http request support in flat .Net objects adding no further dependencies.
> Http request support

- fission/function.go
fixing input checks for fnGetMeta and fnUpdate
> Fixing validations of fn actions

- README.md
These are things that tripped me up a bit when trying to build, so I'm passing them along in case they help someone else.
> Minor improvements to build instructions in README

- charts/hello.js
In earlier pull request #90 hello.js was accidentally merged. Removing it.
> Remove redundant hello.js from charts directory

- environments/nodejs/server.js
> Symlink user function's node_modules to server's node_modules

- charts/fission/README.md
> Fix Markdown table

- fission/function.go
use fmt.Errorf() instead of error.New() in line 49
> use fmt.Errorf instead of error.New()

- INSTALL.md
dependent on: https://github.com/fission/fission/pull/168
> Add OpenShift INSTALL.md docs

- INSTALL.md
Please hold on until fission-ui project is transferred to fission group and the first release is tagged.
Feel free to create any issue to fission-ui.
> Add fission-ui intro in readme

- INSTALL.md
- controller/api.go
- controller/functionApi.go
- fission/function.go
- fission/logdb/influxdb.go
- fission/logdb/logdb.go
- fission/main.go
- router/functionHandler.go
This PR tries to let controller establishes a reverse proxy to log database, and redirect query command send from client to database and then proxy back the db responses. So that we dont need to expose database to the public network.
> Retrieve function logs from controller

- timer/timer.go
This PR add additional log when time trigger is removed by the user.
> Print log when timetrigger is removed

- kubewatcher/kubewatcher.go
> Added support for pods and replication controllers to watchers

- environments/ruby/Dockerfile
- environments/ruby/Gemfile
- environments/ruby/Gemfile.lock
- environments/ruby/README.md
- environments/ruby/server.rb
- examples/ruby/events_to_slack.rb
- examples/ruby/hello.rb
- examples/ruby/request_data.rb
attn: @soamvasani 
this PR adds a ruby environment... this initial version just uses webrick
the rack request object (and the full env) are (optionally) passed to the handler in a simple context object
the handler can return either a simple string response (for a 200) or a standard rack response array
includes examples and readme
> add ruby-env

- cache/cache.go
- cache/cache_test.go
- controller/client/client.go
- controller/environmentApi.go
- controller/functionApi.go
- controller/httpTriggerApi.go
- controller/timeTriggerApi.go
- controller/watchApi.go
- fission/environment.go
- kubewatcher/kubewatcher.go
- poolmgr/client/client.go
- poolmgr/functionServiceCache_test.go
- timer/timer.go
This PR aims to fix bugs in the current codebase. So far, I’ve checked all over the project and there is no more similar issue exists after this PR.
> Fix http response body not closed correctly & return immediately when error occurred

- environments/ruby/README.md
- environments/ruby/fission/context.rb
- environments/ruby/fission/handler.rb
- environments/ruby/fission/specializer.rb
- environments/ruby/server.rb
- examples/ruby/request_data.rb
This PR sets up the Rack logger, exposes it through the context, and updates the README and example
(also updates the error cases in the specializer and handler to log failures)
> Ruby logger

- kubewatcher/kubewatcher.go
This PR aims to fix the following issues
1. watchSubscription is unstoppable even the watch is removed by the user.
2. add more checks to make sure that watchSubscription is stopped by the user or the unknow issues
> Fix unstoppable kubewatcher

- logger/logger.go
This PR aims to fix logger prints wrong log that may mislead others.
> Fix logger prints wrong log

- .gitignore
- environments/binary/Dockerfile
- environments/binary/README.md
- environments/binary/build.sh
- environments/binary/env.go
- environments/binary/server.go
- environments/fetcher/build.sh
- examples/binary/README.md
- examples/binary/echo.sh
- examples/binary/headers.sh
- examples/binary/hello.go
- examples/binary/hello.sh
As part of setting up my development environment, I played around with Fission a bit. One of the consequences of that is that I created an environment for executing binary files.
Use cases:
- Execute bash scripts.
- Run executables of languages that have no dedicated environment yet.
It uses a CGI-like interface for exposing the HTTP request to the executable.
Performance-wise, it is not an optimal environment, but it does allow **any** language to be used for creating a Fission function, as long as it can compile to a Linux binary. So the best way to view this environment, is as a fallback option in case a dedicated environment for a particular language is not available.
Kudos for the first person to write a Brainfuck Fission function 😁 
@soamvasani ready for review
> Binary Environment

- charts/fission-all/templates/deployment.yaml
This PR remove etcd deployment from helm charts fission-all
> Remove etcd deployment & svc

- environments/fetcher/cmd/build.sh
- fission-bundle/build.sh
- fission-bundle/main.go
- glide.lock
- glide.yaml
- storagesvc/client/client.go
- storagesvc/client/storagesvc_test.go
- storagesvc/storagesvc.go
- test/test_utils.sh
A very rudimentary storage service for archives larger than what can
fit in TPR/CRD resources. The library used allows for using local
files, AWS S3, or other cloud storage APIs.  For now only local paths
are set up.
The storage service doesn't know anything about functions or packages; 
it can be used for arbitrary archives.
There's no CLI integration yet.
> Storage service and client

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/pvc.yaml
- charts/fission-all/templates/svc.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/templates/pvc.yaml
- charts/fission-core/templates/svc.yaml
- charts/fission-core/values.yaml
- controller/storagesvc.go
- fission-bundle/main.go
- storagesvc/client/storagesvc_test.go
- storagesvc/storagesvc.go
Storage service in the helm charts, plus a few bugfixes in the proxy.
> Storage service helm chart integration + bugfixes

- router/httpTriggers.go
- test/tests/test_internal_routes.sh
> Fix internal route setup bug

- storagesvc/storagesvc.go
Fix https://github.com/fission/fission/issues/350
> Fix storage service failed to start after restarting it

- poolmgr/functionServiceCache.go
- poolmgr/gp.go
> Differentiate by environment in fscache eviction

- hack/deploy.sh
Copied from the Fission Workflows code base, as this might serve as a nice base for a Fission deploy script
> Add experimental deploy script

- controller/api.go
- controller/workflowApiProxy.go
This PR fixes the workflow apiserver proxy. Additionally it adds an experimental automated deploy script.
> Fix workflow apiserver proxy

- environments/dotnet20/README.md
- environments/dotnet20/build.sh
- environments/dotnet20/project-build.sh
- hack/release.sh
Fix the dotnet20 build, use docker, and re-enable it in the release script.
> dotnet20 build fixes

- Compiling.md
Containers will get stuck in ErrImagePull/ImagePullBackOff state otherwise
> changed helm install pullPolicy from Always to IfNotPresent when building local docker image

- router/httpTriggers.go
This PR aims to keep store for fast synchronization. (PR https://github.com/fission/fission/pull/376)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/382)
> Use store to sync functions/triggers for fast synchronization

- buildermgr/envwatcher.go
- controller/api.go
- controller/buildermgr.go
- environments/fetcher/client/client.go
- environments/fetcher/fetcher.go
- environments/python3/server.py
- fission/environment.go
- fission/function.go
- poolmgr/gp.go
- test/build_and_test.sh
- test/test_utils.sh
- test/tests/test_buildermgr.sh
- types.go
This PR aims to fix remaining issues in PR https://github.com/fission/fission/pull/308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/367)
> Fix builder manager issues

- examples/python/statuscode.py
It took me a while to figure this out. So I figured I'd post an example to help others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/395)
> Added python example to demonstrate status codes.

- examples/nodejs/README.md
- examples/nodejs/weather.js
Hello team, fission project is just amazing!
I've just started to test it and I've created my own node.js example to get current weather at a given location.
Feel like sharing my humble contribution to you. Please, do not hesitate to discard it if not useful.
Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/394)
> created weather.js in node.js examples, modified README.md

- Documentation/docs-site/content/install.md
Minor change of adding hostname for AWS cloud setup of fission env vars.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/392)
> Added AWS to install cloud setup

- environments/fetcher/client/client.go
Tests & builds fail often when fetcher has fetched the code but the pod is still not responding so this PR adds a retry to fetch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/403)
> Fetcher retry

- executor/api.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/407)
> Executor API panics if there is err in getting function from backends

- glide.lock
- mqtrigger/messageQueue/nats.go
This small PR aims to solve compilation problem after nats related dependencies being updated. (issue https://github.com/fission/fission/issues/410)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/411)
> Update nats dependencies

- controller/httpTriggerApi.go
- fission/httptrigger.go
- router/httpTriggers.go
Include Host in httproute output table and fix
duplicate error detection to consider Host as
well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/425)
> Add support for httproute Host matching

- test/test_utils.sh
Right now, test script may fail at following cases:
1. helm tiller is not ready yet 
2. failed at deploying new release due to old releases
This PR aims to solve problems above for more happier travis-ci build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/434)
> Improve travi-ci test scripts

- charts/fission-all/templates/pvc.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/pvc.yaml
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/445)
> Use storageClassName in Helm Charts (#444)

- hack/travis-kube-setup.sh
- test/test_utils.sh
- test/tests/test_logging/log.js
- test/tests/test_logging/test_function_logs.sh
A few improvements to the integration test:
1. Search for test files recursively in the test dir
1. Output a test report at the end for a quick summary of what tests passed/failed/were skipped
1. Add support skipping test files; skip the logging test since it's broken (#446 is tracking this)
1. Switch to latest helm version
1. Cleanup namespace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/447)
> Integration test improvements

- fission/logdb/influxdb.go
- test/tests/test_logging/test_function_logs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/448)
> Fix fission function logs

- fission-bundle/main.go
This is a quick fix to solve the build failure problem introduced in https://github.com/fission/fission/pull/449
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/456)
> Fix fission bundle build failure

- environments/binary/Dockerfile
- environments/binary/README.md
- environments/binary/build.sh
- environments/binary/builder/Dockerfile
- environments/binary/builder/build.sh
- environments/binary/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/452)
> Convert build.sh to a multi-stage Dockerfile.

- charts/fission-all/templates/deployment.yaml
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/462)
> Build and push fluentd image on release; update chart to use that image

- environments/go/server.go
This PR adds readiness probe to go env.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/461)
> Add readiness probe to go env

- Documentation/docs-site/README.md
- Documentation/docs-site/content/install-workflows.md
- Documentation/docs-site/content/workflows/_index.en.md
This PR adds installation instructions for Fission Workflows 0.2.0 to the documentation website. It is a lightly adapted version of the installation instructions on the Github of Fission Workflows. Most notably, it contains an explanation of the example (which includes some explanation about Fission Workflows)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/453)
> Installation instructions for Fission Workflows

- examples/perl/hello.pm
As promised in #311, I've added some more examples to do things in the perl environment. Please excuse the very long "lunch break" m)
This can be viewed live at
https://fission.svc.0x0a.network/hello-perl?name=foo
May this help someone :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/479)
> Extend perl examples to use more http features

- charts/fission-all/templates/post-install-job.yaml
- charts/fission-core/templates/post-install-job.yaml
Run post install job on upgrade too.
Also fixes #443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/473)
> Helm hook bugfixes: run on upgrade, delete on completion

- Documentation/wip/execution-backends.md
Some early notes to track thoughts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/432)
> NewDeploy Doc

- CHANGELOG.md
- Documentation/docs-site/content/installation/_index.en.md
- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
- controller/api.go
- fission/main.go
- hack/release.sh
Will merge it after final check
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/489)
> Version -> 0.5.0

- Documentation/docs-site/config.toml
- Documentation/docs-site/content/upgrade/_index.en.md
- Documentation/docs-site/content/upgrade/upgrade-from-v0.4.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/490)
> Add upgrade guide from 0.4.x to 0.5.0

- Documentation/docs-site/content/tutorial/_index.en.md
- Documentation/docs-site/content/tutorial/access-secret-cfgmap-in-function.md
* Need example of accessing multiple secrets/configmaps
* Need to update current constraints for updating secrets/configmaps
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/484)
> Add simple usage doc for accessing secret/configmap in function

- environments/go/builder/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/492)
> Go builder for single file functions

- router/httpTriggers.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/495)
> Remove a noisy log from router

- environments/go/README.md
- examples/go/README.md
- examples/go/specs/env.yaml
closes #457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/497)
> Go: Set image to right version, update example readme

- hack/release.sh
This fixes #501 
Although overall the script needs to be improved. Right now it is a mix of some parts being built and pushed in separate procedures, while some procedures do push & build in the same procedure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/509)
> Adds latest tags and pushes to dockerhub for fetcher and fission-bundle

- README.md
Replacing the hard-coded release name from links to latest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/513)
> Replace the release with the latest tag.

- charts/fission-all/templates/post-install-job.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/514)
> Fix post-install-job container failure due to command not found

- buildermgr/envwatcher.go
- executor/newdeploy/newdeploy.go
- executor/poolmgr/gp.go
- fission/function.go
- fission/main.go
- test/tests/test_secret_cfgmap/test_secret_cfgmap.sh
- types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/512)
> Fix CLI not update function's secret/configmap correctly

- executor/newdeploy/newdeploy.go
- executor/newdeploy/newdeploymgr.go
- fission/environment.go
- fission/function.go
- fission/main.go
- test/tests/test_backend_nd_update.sh
This is PR for #465. 
Yet to test extensively, will remove "in progress" flag once ready for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/504)
> Update Fn: Executor New Deployment

- charts/fission-all/templates/post-install-job.yaml
- charts/fission-core/templates/post-install-job.yaml
closes #503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/516)
> Add chart version to job name

- hack/Releasing.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/522)
> Release checklist

- .travis.yml
- common.go
- controller/api.go
- executor/api.go
- router/router.go
- storagesvc/storagesvc.go
- test/tests/test_logging/test_function_logs.sh
The log from readiness and liveness probes were too noisy. So disabling them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/525)
> Delete healthz log

- fission/httptrigger.go
https://github.com/fission/fission/issues/238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/539)
> Show warning when trying to create a route with non-existent function (#238)

- hack/release.sh
Use local variables in functions.  Update latest tags where we were't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/541)
> Release script updates

- executor/cleanup.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/534)
> Fix executor failed to clean cache & kubeobjs after function deleted (#533)

- INSTALL.md
as title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/561)
> [ci skip] update release number

- Documentation/docs-site/content/installation/installation.en.md
This should help other people not get tripped up like I did in #577.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/578)
> Add golang example to installation guide

- fission/environment.go
Env version if not set by the user while using builder should be equal or greater than 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/569)
> Fixes the issue #559 with env versions

- charts/fission-all/templates/post-upgrade-job.yaml
- charts/fission-core/templates/post-install-job.yaml
- charts/fission-core/templates/post-upgrade-job.yaml
Fix https://github.com/fission/fission/issues/535
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/564)
> Add post-upgrade-job to track fission upgrade

- fission/function.go
- fission/httptrigger.go
- fission/spec.go
This is to solve issue : https://github.com/fission/fission/issues/502
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/547)
> Prepending a slash to user input url if missing.

- environments/fetcher/fetcher.go
This PR is for https://github.com/fission/fission/issues/554.
I haven't written a unit test for this trivial change. But tested it manually and it works.
I'll add a separate issue to write unit test case for fetcher and cover this case as part of that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/584)
> Check if the requested file already exists in fetcher and skip fetch

- Documentation/docs-site/config.toml
- Documentation/docs-site/content/_index.en.md
- Documentation/docs-site/content/usage/environments.en.md
- Documentation/docs-site/content/usage/executor.en.md
- Documentation/docs-site/content/usage/functions.en.md
- Documentation/docs-site/content/usage/package.en.md
- README.md
Though we can test function by `fission test`, we still need steps for setting up FISSION_ROUTER. It's quite important for a newcomer to use fission.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/593)
> Add steps to set FISSION_ROUTER env variable & update docs

- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
updating release version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/597)
> changes needed for release 0.7.0

- CHANGELOG.md
- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/598)
> updates to changelog.

- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
- controller/api.go
- controller/controller.go
- controller/functionApi.go
- executor/api.go
- executor/executor.go
- executor/newdeploy/newdeploy.go
- executor/poolmgr/funcwatcher.go
- executor/poolmgr/gp.go
- executor/poolmgr/gpm.go
- fission/environment.go
- fission/main.go
- types.go
This aims to solve issue #515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/544)
> Use a separate controller loop to watch functions change and create a service

- hack/Releasing.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/599)
> Updating releasing guideliness with a few more details.

- fission/environment.go
- fission/httptrigger.go
- fission/main.go
- fission/mqtrigger.go
- fission/spec.go
- fission/timetrigger.go
- fission/watch.go
Add `fission env create --spec ..` and `fission *trigger create --spec ...`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/607)
> `fission X create --spec` flags for env and trigger create commands

- CHANGELOG.md
- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/622)
> Changes needed for release 0.7.1

- fission/main.go
Fix #613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/619)
> Add default value to cli flag

- executor/cleanup.go
- executor/fscache/functionServiceCache.go
Fix #629 
Notice the problem that executor does not delete specialized pod during the benchmark test. A specialized pod never get deleted once the environment, the pod belongs to, was deleted. 
IdleObjectReaper only iterates over the existing environment (L102). We need to check all old funcSvcs even the environment no longer exists.
https://github.com/fission/fission/blob/0194f53e124442986de20ee3bd3032bea61cca68/executor/cleanup.go#L96-L110
1. Modify `functionServiceCache` to list all old funcSvcs without requiring the environment metadata
2. Iterate over old funcSvcs and remove them if necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/633)
> Fix executor does not reap specialized function pod when env no longer exists

- fission/function.go
- fission/logdb/influxdb.go
- fission/logdb/logdb.go
- fission/main.go
Fixes #590 and related to #592
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/594)
> Removed the fn pods functionality

- .travis.yml
- test/build_and_test.sh
- test/test_utils.sh
- test/tests/test_archive_pruner.sh
This prevents commands timing out due to the additional lag introduced by port-forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/611)
> Remove port forward in tests for router, controller and nats pods 

- fission/function.go
- fission/package.go
For issue : https://github.com/fission/fission/issues/636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/637)
> Setting buildStatus to pending when function's source archive is updated.

- test/tests/test_env_vars.sh
- test/tests/test_node_hello_http.sh
This PR tends to address the test cases failure problem. (Log: https://api.travis-ci.org/v3/job/371377211/log.txt)
1. test_node_hello_http.sh
2. test_env_vars.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/647)
> Fix test cases occasional failure

- fission/function.go
Fixes #645
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/652)
> Function update should be possible without change to code

- fission/function.go
- test/tests/test_function_test/errhello.js
- test/tests/test_function_test/hello.js
- test/tests/test_function_test/test_fn_test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/651)
> Fixes the issue with fn test and adds relevant test cases, fixes #650

- environments/fetcher/fetcher.go
- test/tests/test_fn_update/test_nd_pkg_update.sh
- test/tests/test_fn_update/test_poolmgr_nd.sh
- test/tests/test_fn_update/test_resource_change.sh
- test/tests/test_fn_update/test_scale_change.sh
This PR is for issue https://github.com/fission/fission/issues/659
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/661)
> meaningful error message when fetch request is received for a package when build is not successful.

- hack/runtests.sh
- test/benchmark/Dockerfile
- test/benchmark/assets/hello.py
- test/benchmark/picasso.go
- test/benchmark/tests/burst-load/run.sh
- test/benchmark/tests/burst-load/sample.js
- test/benchmark/tests/concurrency-level/run.sh
- test/benchmark/tests/concurrency-level/sample.js
- test/benchmark/tests/package-size/run.sh
- test/benchmark/tests/package-size/sample.js
This PR is the first step for benchmarking fission. More test cases & docs will be added in near future. #571 #528
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/666)
> Add benchmark script

- CHANGELOG.md
- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/670)
> Version -> 0.7.2

- Documentation/wip/java-env-design.md
@soamvasani Based on the discussion we had Monday, here are some options for the request body vs. full object to be passed to function.  Request your comments too @life1347 @smruthi2187 @erwinvaneyk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/642)
> Java environment Design & considerations

- .gitignore
This is a built binary, should be ignore when git committion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/736)
> add build exe to gitignore

- test/tests/test_fn_update/test_configmap_update.sh
- test/tests/test_fn_update/test_nd_pkg_update.sh
- test/tests/test_fn_update/test_secret_update.sh
Will enable again after closure on #723
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/737)
> Temporarily disabling the tests so that other PRs can be worked on

- executor/cleanup.go
Executor not reap idle function pods launched by newdeploy with minScale < 1.
A check for executor type was add in PR https://github.com/fission/fission/pull/534 , and cause execuotr not reaps idle pods.
https://github.com/fission/fission/blob/704a8094e6724f8c26a667909c48c62ba6ee095f/executor/cleanup.go#L135-L139
Rollback to previous implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/744)
> Fix executor not reaps idle function pods for functions with executortype newdeploy

- hack/release.sh
This PR aims to resolve issue #383 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/745)
> Add steps to render & upload fission installation YAML

- environments/python/README.md
- environments/python/requirements.txt
- environments/python/server.py
According to comment https://github.com/fission/fission/pull/686#issuecomment-395609362
* Add gevent based WSGI server framework to Python Environment, for heavy resource utilization cases.
* Clarify Flask based application, to wrap user function, routers, logger initialization, etc to class members.
* Present related explication in README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/750)
> Python Environment: add gevent based WSGI server framework

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/780)
> Committing changelog.

- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/788)
> changes needed for 0.9.1

- test/test_utils.sh
- test/tests/test_obj_create_in_diff_ns.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/791)
> Delete namespace in background to reduce build time

- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
- router/functionHandler.go
- router/functionHandler_test.go
- router/httpTriggers.go
- router/router.go
- router/router_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/713)
> Allow router round-trip to be configurable

- environments/fetcher/cmd/main.go
- mqtrigger/messageQueue/asq.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/760)
> Fixed typos from from goreportcard

- .travis.yml
This PR adds a simple sanity check for the helm charts to the Travis CI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/799)
> Helm lint check in Travis CI

- environments/jvm/README.md
- examples/jvm/java/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/768)
> Added readme for JVM environment

- examples/jvm/java/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/824)
> Fixed the name of JVM builder image name

- fission/spec.go
Address https://github.com/fission/fission/issues/834
Test spec file
```
apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
creationTimestamp: null
name: hEllo
namespace: default
spec:
contentType: application/json
errorTopic: ""
functionref:
name: test
type: name
maxRetries: 0
messageQueueType: nats-streaming
topic: asd
```
Result
```
$ » fission spec validate
Error validating specs: 1 error occurred:
* MessageQueueTrigger.Name: Invalid value: hEllo: [a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Do resources validation when validate spec files

- .travis.yml
- fission/function.go
- fission/package.go
Closing the other PR and opened this instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/866)
> Fix for #662: avoid unnecessary builds

- fission/portforward/portforward.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/867)
> Fix CLI failed to setup port-forward caused by #712

- .travis.yml
- test/tests/mqtrigger/test_mqtrigger.sh
- test/tests/mqtrigger/test_mqtrigger_error.sh
- test/tests/test_backend_newdeploy.sh
- test/tests/test_backend_poolmgr.sh
- test/tests/test_buildermgr.sh
- test/tests/test_environments/test_java_builder.sh
- test/tests/test_environments/test_java_env.sh
- test/tests/test_fn_update/test_configmap_update.sh
- test/tests/test_fn_update/test_env_update.sh
- test/tests/test_fn_update/test_nd_pkg_update.sh
- test/tests/test_fn_update/test_poolmgr_nd.sh
- test/tests/test_fn_update/test_resource_change.sh
- test/tests/test_fn_update/test_scale_change.sh
- test/tests/test_fn_update/test_secret_update.sh
- test/tests/test_function_test/test_fn_test.sh
- test/tests/test_function_update.sh
- test/tests/test_internal_routes.sh
- test/tests/test_logging/test_function_logs.sh
- test/tests/test_node_hello_http.sh
- test/tests/test_package_command.sh
- test/tests/test_router_cache_invalidation.sh
- test/tests/test_secret_cfgmap/test_secret_cfgmap.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/863)
> Add cleanup function to test scripts

- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/870)
> Fix failed to find release-builder dockerfile & push specific tag

- executor/executor.go
- executor/reaper/reaper.go
Don't just look in functionNamespace anymore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/879)
> FIX CleanupOldExecutorObjects in all namespaces

- environments/fetcher/fetcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/889)
> Fix fetcher not close file descriptor correctly

- fission/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/886)
> Removes the spec helm command for now to fix #881

- crd/crd.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/897)
> Check CRD creation error instead of doing return directly

- fission/canaryconfig.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/907)
> Print status with the get option.

- environments/fetcher/cmd/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/911)
> Fixes #758, uses v2 specialize for env versions 2 or higher

- demos/canary-rollback-scenario/run.sh
- demos/canary-successful-scenario/run.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/914)
> Fix flag not found problem when running canary demo scripts

- hack/release-build.sh
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/916)
> Added build and push procedures for Nodejs builder environment

- router/functionHandler.go
This PR aims to solve #876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/890)
> Add X-Forwarded-Host to request header

- environments/python/requirements.txt
To solve #896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/942)
> Bump flask version 

- canaryconfigmgr/canaryConfigCache.go
- canaryconfigmgr/canaryConfigMgr.go
- canaryconfigmgr/prometheusClient.go
Fixes issues listed in https://github.com/fission/fission/issues/928 and https://github.com/fission/fission/issues/921
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/943)
> fix a few canary deployment issues

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
- test/build_and_test.sh
- test/test_utils.sh
- test/upgrade/fission_upgrade_test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/941)
> Support for full url  (base on aalubin 882 changes)

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/953)
> Update readme to include JVM

- hack/release-build.sh
Addresses (a part of) #922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/939)
> Remove version from release name since it contains illegal chars for names

- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/964)
> Keep prometheus and canary deploy set to false in fission-core

- README.md
Updating the link to right document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/965)
> Updating the compile documentation link

- fission/function.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/966)
> Fix CLI not shows package name when creating a function

- fission/environment.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/971)
> Show builder image when list all envs

- charts/fission-all/templates/nonhelm-install-job.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/nonhelm-install-job.yaml
- charts/fission-core/values.yaml
- hack/release-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/977)
> Fix the analytics jobs in the YAMLs (remove duplicates)

- hack/release-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/978)
> Fix release script failed to generate yaml for nonhelm installation

- fission/package.go
Fixes #938
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/995)
> Package info error should warn user if package does not exist

- .travis.yml
- hack/travis-kube-setup.sh
- mqtrigger/messageQueue/kafka.go
- mqtrigger/messageQueue/nats.go
- redis/redis.go
- router/functionHandler.go
After go version 1.11+, the test scripts failed due to the formatting error. This PR is base on PR #945 .
All credits belong to @HaraldNordgren
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/999)
> Update formatting directive logic to unbreak tests

- mqtrigger/messageQueue/nats.go
Fix #1000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1002)
> Fix MQ trigger (NATS) wrongly sends error message to response topic

- fission/function.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/996)
> Added warning to fix #946

- executor/newdeploy/newdeploy.go
- executor/newdeploy/newdeploymgr.go
Fix #955
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/976)
> Pre-create kubernetes resources for function with minScale=0

- charts/README.md
- Makes it easy to find the `values.yaml` of `fission-all` chart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1023)
> Add link to values.yaml in charts' README.md

- buildermgr/envwatcher.go
- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
- common.go
- executor/newdeploy/newdeploy.go
- executor/newdeploy/newdeploymgr.go
- executor/poolmgr/gp.go
Fix problem introduced in PR #793
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1033)
> Fix builder not using latest image during CI build

- environments/python/server.py
- Fixes PEP8 errors for `environments/python/server.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1034)
> [python-env] PEP8 Fixes for server.py

- environments/dotnet/README.md
- environments/dotnet/build.sh
- environments/dotnet20/README.md
- environments/dotnet20/build.sh
- environments/perl/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1035)
> Update dotnet and perl environment docs for rebuilding env images

- router/functionHandler.go
- router/svcAddrUpdateLock.go
Refactor RoundTrip function into multiple small functions for better code reading and understanding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/991)
> Refactor RoundTrip function for code reading

- environments/go/server.go
Currently, go env panic when failed at loading plugin. It makes harder for people to debug with.
This PR addresses the panic problem by returning the error instead.
Now, when testing a function the CLI returns logs like following
```
$ fission fn test --name h4
Error calling function h4: 500 [h4] Error creating service for function: Internal error - error specializing 
function: error loading plugin: plugin.Open("/userfunc/cc9a00e1-036b-11e9-b67e-
080027fb9776/hello-go-kcyg-l7bl8g-1rou5x"): plugin was built with a different version of package internal/cpu
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1031)
> Fix go env panic when trying to load plugin and failed

- fission/function.go
- fission/package.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1036)
> Fix cli create archive with nonexistent file

- README.md
Update README to include all currently supported trigger types with links to documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1043)
> Include All Currently Supported Trigger Types

- charts/fission-all/templates/deployment.yaml
Fixes #1044
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1045)
> Makes router URL for Kafka trigger configurable

- Documentation/wip/annotations_design.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/992)
> Draft proposal for annotations

- Documentation/docs-site/content/contributing/compiling.en.md
More details in [https://github.com/kubernetes/client-go/blob/master/INSTALL.md#glide](url)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1048)
> solve kubernetes/client-go nested vendor

- executor/newdeploy/newdeploy.go
- executor/newdeploy/newdeploymgr.go
Fixes #1004
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1040)
> New deploy should clean up objects it created if there are errors

- canaryconfigmgr/canaryConfigMgr.go
- canaryconfigmgr/prometheusClient.go
- controller/api.go
- controller/canaryConfigApi.go
- controller/config.go
- controller/controller.go
- featureconfig/types.go
- fission/canaryconfig.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/990)
> Send the error message to user when enabling canary feature fails.

- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1059)
> Bumped up default CPU for fetcher, fixes #1058

- charts/README.md
- That makes it easy to link at different places
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1062)
> Make extra configuration a sub heading

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/fluentd.yaml
- charts/fission-all/templates/nonhelm-install-job.yaml
- charts/fission-all/templates/post-install-job.yaml
- charts/fission-all/templates/post-upgrade-job.yaml
- charts/fission-all/templates/secrets.yaml
- charts/fission-all/templates/svc.yaml
- charts/fission-core/templates/nonhelm-install-job.yaml
- charts/fission-core/templates/post-install-job.yaml
- charts/fission-core/templates/post-upgrade-job.yaml
- charts/fission-core/templates/svc.yaml
Some meaningless blank line and `---` is rendered by helm.
This PR is aimed to eliminate them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1065)
> Fix helm charts blank line

- fission/spec.go
Spec archive has issues with single files (Will file issue in a bit) and can be optimized to use the Glob method already available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1068)
> Spec archive optimisation

- logger/fluentd/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1076)
> Fix fluentd plugin version to prevent version incompatible problem

- charts/README.md
- charts/fission-all/values.yaml
- charts/fission-core/values.yaml
The README for helm charts is out-of-date. Update it based on `fission-all/values.yaml` and `fission-core/values.yaml`.
An undocumented variable `persistence.existingClaim` is also added in both values.yaml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1064)
> Update helm charts README

- common.go
- executor/poolmgr/gp.go
- This makes sure if the Pod is in Running state
- https://godoc.org/k8s.io/api/core/v1#PodPhase
- Checks if an IP address is allocated to the Pod
- https://github.com/fission/fission/issues/1054#issuecomment-457817792 
~~Probably Fixe s #1054~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1080)
> Consider Pod Phase in IsReadyPod

- buildermgr/common.go
- buildermgr/envwatcher.go
- buildermgr/pkgwatcher.go
- charts/fission-all/requirements.yaml
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
- environments/fetcher/client/client.go
- environments/fetcher/cmd/main.go
- environments/fetcher/fetcher.go
- executor/api.go
- executor/client/client.go
- executor/executor.go
- executor/executor_test.go
- executor/newdeploy/newdeploy.go
- executor/newdeploy/newdeploymgr.go
- executor/poolmgr/gp.go
- executor/poolmgr/gpm.go
- fission-bundle/main.go
- fission/package.go
- fission/spec.go
- fission/upgrade.go
- glide.lock
- glide.yaml
- router/functionHandler.go
- router/router.go
- storagesvc/client/client.go
- storagesvc/client/storagesvc_test.go
- storagesvc/storagesvc.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1079)
> OpenTracing for Fission

- Documentation/wip/ci-cd-proposal.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1084)
> Added draft proposal for CI/CD

- examples/python/README.md
This adds a simple README with (1) an description of the examples in this directory, and (2) the minimal steps to getting started. 
Since this page is the top result when people search "Fission Python", this README should help recurring users to quickly find what they are looking for and point new users to the official docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1103)
> Python examples: Added a minimal 'getting started'

- canaryconfigmgr/canaryConfigMgr.go
If no valid prometheus server url provided in configmap, controller will try to retrieve related information from environment variables.
Due to  controller uses only host address without proper protocol scheme/port for prometheus client to connect with and makes canary config manager failed to start.
To fix this, this PR adds extra lines to get necessary information and append those infos into prometheus service url.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1105)
> Fix canary config manager creation error in controller

- charts/fission-core/templates/deployment.yaml
Fixes #1096
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1098)
> Adding annotations for prometheus scraping to fission-core

- fission/environment.go
Fixes https://github.com/fission/fission/issues/1104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1121)
> Configurable zero pool size in case of newdeploy function

- mqtrigger/messageQueue/nats.go
Fix #950 
Currently, MessageQueue has no such interface to expose the status of underlying messaging service, hence MessageQueueTriggerManager has no way to detect and handle such situation properly. It takes some time to redesign interface of MessageQueue. For now, we simply fatal here.
Following is log when mqtrigger detect connection failure problem.
```
{"level":"fatal","ts":1552900715.6082451,"caller":"messageQueue/nats.go:52","msg":"Connection lost","error":"stan: connection lost due to PING failure","stacktrace":"github.com/fission/fission/mqtrigger/messageQueue.makeNatsMessageQueue.func1\n\t/Users/taching/Dropbox/goWorkspace/src/github.com/fission/fission/mqtrigger/messageQueue/nats.go:52"}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Add connection lost handler for NATS-streaming

- commonrbacutil.go
- executor/newdeploy/newdeploymgr.go
- executor/poolmgr/packagewatcher.go
- executor/reaper/reaper.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1163)
> Change log level in executor for better log reading/troubleshooting

- charts/fission-all/templates/deployment.yaml
- charts/fission-core/templates/deployment.yaml
- router/analytics.go
- router/metrics.go
- router/router.go
This change reports total function call count to an analytics url once a day.
It's done behind the existing analytics flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1167)
> Add simple anonymous usage metrics

- environments/fetcher/config/config.go
- environments/fetcher/fetcher.go
- test/tests/test_secret_cfgmap/cfgmap.py.template
- test/tests/test_secret_cfgmap/empty.py
Solution for #1176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1177)
> Fixes broken config path for functions

- router/analytics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1180)
> router analytics -- close http response body

- .gitignore
- hack/runtests.sh
- hack/travis-kube-setup.sh
- test/cluster/main.tf
- test/cluster/versions.tf
I upgrade the CI cluster 1.11.8-gke.6 -> 1.13.6-gke.0
I also write a terraform configuration to manage the cluster resources.
Use `terraform plan` to review the changes and use `terraform apply` to apply the changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1194)
> Add Terraform configuration and upgrade helm version

- pkg/fission-cli/spec.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1193)
> Show warning message if spec alters poolsize while env version < 3

- pkg/router/analytics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1195)
> Analytics bugfix

- charts/fission-all/templates/deployment.yaml
https://github.com/tree/1ce767705f3a16654fe0b7d34f4b11eb71499426#monitoring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1199)
> Add readiness/liveness probes to nat-streaming

- .gitignore
- .travis.yml
- test/test_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1200)
> Check fission CLI & server git commit SHA before test

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/requirements.lock
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
- hack/release-build.sh
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1202)
> Fission v1.3.0

- pkg/fission-cli/util/util.go
A user reported there is an error while trying to use fission CLI
```
$ fission env create --name nodejs --image fission/node-env:1.2.1
Fatal error: Could not get the current users directory: user: Current not implemented on darwin/amd64
```
This problem may be related to the cross-compilation problem as described in comments. So in PR tries to get home directory path from env as fallback method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1203)
> Fallback to get user home directory from env

- pkg/fission-cli/logdb/influxdb.go
…er with prefix router
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1201)
> [bugfix] Fix CLI drops controller URL path when querying logs

- pkg/executor/newdeploy/newdeploymgr.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1211)
> Fix executor panic problem when specialization timeout

- environments/jvm/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1207)
> Reuse docker maven build cache in JVM environment build process

- pkg/publisher/webhookPublisher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1206)
> modify code to make log collection comprehensive

- cmd/builder/Dockerfile.fission-builder
- cmd/fetcher/Dockerfile.fission-fetcher
- cmd/fission-bundle/Dockerfile.fission-bundle
- cmd/preupgradechecks/Dockerfile.fission-preupgradechecks
- environments/go/Dockerfile
- environments/go/Dockerfile-1.11.4
- environments/jvm/builder/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1218)
> Reuse go docker build cache

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
- cmd/fission-bundle/main.go
- pkg/utils/rbacutils.go
- test/test_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1217)
> Allow to set log level through environment variable

- pkg/controller/client/client.go
- pkg/fission-cli/util/version.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1223)
> Fix nil pointer when CLI unable to get server version

- pkg/fetcher/fetcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1227)
> Replace localhost with 127.0.0.1 to prevent DNS resolving problem

- test/test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1237)
> Fix build failed due to script unable to find configmap

- pkg/fetcher/client/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1238)
> Fix fetcher client doesn't handle error properly

- cmd/fission-bundle/main.go
- pkg/buildermgr/envwatcher.go
- pkg/canaryconfigmgr/canaryConfigMgr.go
- pkg/controller/api.go
- pkg/controller/controller.go
- pkg/executor/api.go
- pkg/executor/executor.go
- pkg/executor/newdeploy/newdeploymgr.go
- pkg/executor/poolmgr/funcwatcher.go
- pkg/executor/poolmgr/gp.go
- pkg/executor/poolmgr/gpm.go
- pkg/executor/reaper/reaper.go
- pkg/kubewatcher/kubewatcher.go
- pkg/mqtrigger/messageQueue/kafka.go
- pkg/mqtrigger/messageQueue/messageQueue.go
- pkg/mqtrigger/messageQueue/nats.go
- pkg/router/functionHandler.go
- pkg/router/httpTriggers.go
- pkg/router/ingress.go
- pkg/router/router.go
- pkg/storagesvc/archivePruner.go
- pkg/storagesvc/storagesvc.go
- pkg/utils/utils.go
This PR removes not so useful logs and changes most of Info level
log to Debug/Error level in hot path while preserving some of them
that are helpful for troubleshooting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1231)
> Change log-level for better performance and less annoying logs

- environments/python/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1243)
> Update flask version to resolve CVE alert

- test/test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1246)
> Fix CI unable to start test due to the same travis build ID

- charts/fission-all/templates/deployment.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1247)
> Analytics env fix in chart

- pkg/crd/crd_test.go
- pkg/fission-cli/spec.go
Fix #1251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1254)
> Fix wrongly replace spec api version

- examples/tensorflow-serving/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1256)
> Update tensorflow serving image name in env README

- hack/release-build.sh
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1257)
> Fix release script tags wrong image name

- charts/fission-all/templates/fluentbit.yaml
Added correct imagePullPolicy in fluentbit.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1263)
> Added correct imagePullPolicy

- environments/jvm/builder/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1269)
> Use fuzzy version for openJDK dependency

- pkg/fetcher/fetcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1275)
> Fix typo "specialing" -> "specializing"

- environments/go/builder/build.sh
Fix #1274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1276)
> Fix go 1.9.2 & 1.11.4 shows "go mod not found"

- test/save_cache.sh
- test/test_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1285)
> Improve CI integration test script

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1292)
> Add troubleshooting guide link

- environments/nodejs/server.js
Fix issue mentioned in https://github.com/fission/fission/pull/258#issuecomment-470071420 and part of the changes in PR https://github.com/fission/fission/pull/258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1295)
> Support nodejs function with 0 argument

- pkg/controller/api_test.go
- pkg/controller/controller.go
- pkg/crd/crd_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1297)
> Fix unit tests failure

- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
- hack/Releasing.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1303)
> Fission 1.5.0

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1304)
> Update CHANGELOG for 1.5.0

- pkg/fission-cli/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1305)
> Add specialization timeout default value to CLI

- pkg/executor/cms/cmscontroller.go
Fix #1306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1307)
> Fix executor unable to list secrets/configmaps

- .travis.yml
- hack/runtests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1308)
> Integrate with Codecov

- cmd/preupgradechecks/preupgradechecks.go
- pkg/apis/fission.io/v1/typeDeepcopyFunc.go
- pkg/apis/fission.io/v1/validation.go
- pkg/executor/newdeploy/newdeploy.go
- pkg/executor/newdeploy/newdeploymgr.go
- pkg/executor/poolmgr/gp.go
- pkg/executor/util/merge.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/package.go
- pkg/fission-cli/spec.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1311)
> Fix potential nil pointer problem when using multierror pkg

- pkg/fission-cli/function.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1315)
> Fix failed to update specialization timeout

- pkg/executor/newdeploy/newdeploy.go
- pkg/executor/newdeploy/newdeploymgr.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1316)
> Fix newdeploy doesn't handle error properly

- pkg/executor/newdeploy/newdeploy.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1319)
> Disable revision history for newdeploy

- pkg/executor/newdeploy/newdeploy.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1321)
> Set maxSurge to 20% for safe rolling upgrade

- pkg/fission-cli/httptrigger.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1328)
> Fix empty host value when list http triggers

- pkg/router/httpTriggers.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1336)
> Remove too verbose and unhelpful debug log

- charts/README.md
- charts/fission-all/templates/svc.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/svc.yaml
- charts/fission-core/values.yaml
Fixes #1337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1338)
> Allow to add annotations to router service in helm chart

- environments/jvm/builder/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1340)
> Bump jvm builder JDK version

- environments/go/builder/build.sh
This PR is based on #1324 and all the credits should go to @ti.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1346)
> Support custom private go vendor

- charts/fission-all/templates/redis.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1350)
> Move statefulset to apps/v1

- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1351)
> Fission 1.6.0

- hack/release-build.sh
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1353)
> Fix release script tags wrong image name & sed problem on Linux

- Documentation/Architecture.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1356)
> Update fission architecture doc

- pkg/fission-cli/cmd/environment/get.go
- pkg/fission-cli/cmd/environment/list.go
- pkg/fission-cli/function.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1361)
> Remove UID from CLI output

- pkg/controller/api.go
- pkg/executor/api.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1362)
> Move route creation to function

- pkg/fission-cli/cli.go
- pkg/fission-cli/function.go
this change fixes #1357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1358)
> Provide secrets and configmaps while updating the functions

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1366)
> Update READEME link and add back the basic usage

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- charts/fission-all/Chart.yaml
- charts/fission-core/Chart.yaml
- environments/nodejs/package.json
- examples/nodejs/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1383)
> Update maintainer info

- Makefile
- githooks/README.md
- githooks/pre-push
- hack/verify-govet.sh
- hack/verify-staticcheck.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1382)
> Update Makefile and add git pre-push hook

- pkg/executor/api.go
- pkg/executor/executor.go
- pkg/executor/newdeploy/newdeploy.go
- pkg/executor/newdeploy/newdeploymgr.go
- pkg/executor/poolmgr/gp.go
- pkg/executor/poolmgr/gpm.go
- pkg/router/functionHandler.go
Fix #138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1392)
> Poolmanager wait for function pod to be till specialization timeout

- cmd/fission-cli/main.go
- pkg/fission-cli/cmd/function/command.go
- test/tests/test_specs/test_spec_merge/test_spec_merge.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1393)
> Fix CLI exits with status 0 when error occurs

- cmd/fission-cli/app/app.go
- pkg/apis/fission.io/v1/types.go
- pkg/fission-cli/cmd/canaryconfig/command.go
- pkg/fission-cli/cmd/environment/command.go
- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/cmd/httptrigger/command.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/httptrigger/update.go
- pkg/fission-cli/cmd/kubewatch/command.go
- pkg/fission-cli/cmd/mqtrigger/command.go
- pkg/fission-cli/cmd/package/command.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/spec/command.go
- pkg/fission-cli/cmd/timetrigger/command.go
- pkg/fission-cli/flag/flag.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1394)
> Reorder command flags and add missing flags

- cmd/fission-cli/main.go
- pkg/fission-cli/cliwrapper/driver/cobra/helptemplate/templates.go
- pkg/fission-cli/cmd/spec/apply.go
- pkg/fission-cli/cmd/support/resources/crd.go
- pkg/fission-cli/cmd/support/resources/kubernetes.go
- pkg/fission-cli/cmd/support/resources/resource.go
- pkg/fission-cli/console/log.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1396)
> Prettify console output message

- cmd/preupgradechecks/preupgradechecks.go
The helm pre-upgrade check failed due to the program tries to
check whether a multierr is a nil pointer instead of errors it contains.
This PR changes the way the program checks multierr in order not to block the upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1397)
> Fix helm pre-upgrade check failure problem

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/fluentbit.yaml
- charts/fission-all/templates/pre-upgrade-job.yaml
- charts/fission-all/templates/router.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/templates/pre-upgrade-job.yaml
- charts/fission-core/templates/router.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1398)
> Replace deprecated serviceAccount with serviceAccountName

- pkg/controller/client/canaryconfig.go
- pkg/controller/client/client.go
- pkg/controller/client/core.go
- pkg/controller/client/environment.go
- pkg/controller/client/function.go
- pkg/controller/client/httptrigger.go
- pkg/controller/client/kuberneteswatchtrigger.go
- pkg/controller/client/mqtrigger.go
- pkg/controller/client/package.go
- pkg/controller/client/recorder.go
- pkg/controller/client/replayer.go
- pkg/controller/client/timetrigger.go
The function implementations of controller client package are
inconsistent. This PR lets functions reuse the functions
that already implemented and be able to set additional headers to
the request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1402)
> Refactor controller client package

- charts/README.md
- charts/fission-all/requirements.lock
- charts/fission-all/requirements.yaml
- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/values.yaml
- charts/fission-core/requirements.lock
- charts/fission-core/requirements.yaml
- charts/fission-core/templates/_helpers.tpl
- charts/fission-core/values.yaml
- pkg/canaryconfigmgr/canaryConfigMgr.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1389)
> Update prometheus version and disable it from the default installation

- pkg/fission-cli/cmd/spec/command.go
- pkg/fission-cli/flag/flag.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1412)
> Fix wrong command and flag usage description

- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/cmd/package/command.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1411)
> Add --spec to package command

- pkg/fission-cli/cmd/spec/spec.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1414)
> Add resource info to output message when saving spec file

- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/kubewatch/create.go
- pkg/fission-cli/cmd/mqtrigger/create.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/cmd/timetrigger/create.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1415)
> Show warning when referencing nonexistent resources in spec

- hack/Releasing.txt
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1416)
> Support semantic version tags

- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1417)
> Fix failed to find init_tools.sh

- hack/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1418)
> Update release-builder go and helm version

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/requirements.lock
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/requirements.lock
- charts/fission-core/templates/NOTES.txt
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1419)
> Fission 1.7.0-rc.1

- cmd/fission-cli/app/app.go
- pkg/fission-cli/cliwrapper/driver/cobra/cobra.go
- pkg/fission-cli/cliwrapper/driver/cobra/helptemplate/templates.go
- pkg/fission-cli/cmd/function/test.go
- pkg/fission-cli/flag/flag.go
Fix #1423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1425)
> Fix verbosity flag not found in subcommand

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/fluentbit.yaml
- charts/fission-all/values.yaml
- hack/release-build.sh
Fix #107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1424)
> Improve compatibility with Openshift

- pkg/apis/fission.io/v1/types.go
- pkg/executor/newdeploy/newdeploy.go
- pkg/executor/newdeploy/newdeploymgr.go
- pkg/executor/poolmgr/gp.go
- pkg/executor/util/util.go
- pkg/fission-cli/cmd/environment/command.go
- pkg/fission-cli/cmd/environment/create.go
- pkg/fission-cli/cmd/environment/update.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1429)
> Support to set imagePullSecret when creating environment

- pkg/fetcher/fetcher.go
- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/cmd/package/command.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/package/update.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/utils/utils.go
- test/test_utils.sh
- test/tests/test_package_checksum.sh
- test/utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1430)
> Add checksum and insecure flag for user to skip checksum generation

- pkg/buildermgr/envwatcher.go
- pkg/executor/newdeploy/newdeploy.go
- pkg/executor/poolmgr/gp.go
- pkg/executor/util/util.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1431)
> Ability to pull builder image from private registry

- pkg/executor/poolmgr/gpm.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1432)
> Fix poolmanager crashes when failed to list environment

- pkg/executor/api.go
- pkg/executor/client/client.go
- pkg/executor/executor.go
- pkg/router/functionHandler.go
- pkg/router/functionHandler_test.go
- pkg/router/functionReferenceResolver.go
- pkg/router/httpTriggers.go
- pkg/router/router_test.go
The router taps function service one by one which is inefficient and 
increases the burden of executor. This PR aggregates all requests into
one to solve the problem mentioned above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1434)
> Allow to tap multiple function services at one time

- pkg/executor/client/client.go
- pkg/router/functionHandler.go
- pkg/router/functionHandler_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1433)
> Collect function metrics after finishing request

- pkg/fetcher/fetcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1436)
> Return error when specialization failed

- test/test_utils.sh
- test/tests/test_huge_response/generated.json
- test/tests/test_huge_response/hello.go
- test/tests/test_huge_response/test_huge_response.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1437)
> Add huge response body test

- pkg/executor/executor.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/fetcher/client/client.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/function_test.go
- pkg/fission-cli/cmd/function/update.go
- test/tests/test_specs/test_spec_merge/test_spec_merge.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1439)
> Fix poolmanager sets 0 timeout for function specialization

- pkg/router/ingress.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1440)
> Fix router tries to update ingress when createIngress is false

- test/tests/test_canary.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1441)
> Try to fix flaky canary test

- test/tests/test_canary.sh
Reverts fission/fission#1441
Looks like there are some problems when running the test against GKE, revert it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1442)
> Revert "Try to fix flaky canary test"

- hack/Releasing.txt
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1444)
> Push extra tag to fit go module semver tag format

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1445)
> Fission 1.7.0-rc.2

- pkg/fission-cli/cmd/spec/init.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1449)
> Fix spec init overrides existing deploymentconfig

- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/spec/apply.go
- pkg/utils/utils.go
- test/test_utils.sh
- test/tests/test_specs/test_ignore_hidden_file.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1450)
> Ignore hidden file when creating archive file

- pkg/controller/client/function.go
- pkg/controller/functionApi.go
- pkg/fission-cli/cmd/function/test.go
- pkg/fission-cli/console/log.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1451)
> Fix CLI unable to get pod logs from controller

- charts/README.md
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
- pkg/executor/executor.go
- pkg/executor/executortype/executortype.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gpm.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1453)
> Make AdoptExistingResources optional

- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1456)
> Fix release script not uploads OpenShift deploy YAML file

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1457)
> Fission 1.7.0

- pkg/buildermgr/envwatcher.go
Fix #1459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1460)
> Fix name conflict when buildermanager merges podspec

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
1.7.1 is a bug fix release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1461)
> Fission 1.7.1

- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1477)
> Push php-builder to dockerhub

- charts/fission-all/templates/nonhelm-install-job.yaml
- charts/fission-all/templates/post-install-job.yaml
- charts/fission-all/templates/post-upgrade-job.yaml
- charts/fission-all/templates/router.yaml
- charts/fission-core/templates/nonhelm-install-job.yaml
- charts/fission-core/templates/post-install-job.yaml
- charts/fission-core/templates/post-upgrade-job.yaml
- charts/fission-core/templates/router.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1490)
> Update analytics URL

- charts/README.md
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
- pkg/executor/executortype/poolmgr/packagewatcher.go
- pkg/executor/reaper/reaper.go
- pkg/fetcher/config/config.go
- skaffold.yaml
- test/test_utils.sh
- test/upgrade/fission_upgrade_test.sh
This PR adds fetcher resource requests&limits chart setting and remove unreasonable limits value from the charts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1489)
> Add config for fetcher resource requests&limits

- pkg/controller/api_test.go
- pkg/crd/crd_test.go
- test/build.sh
- test/test_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1502)
> Let unit tests run in different namespaces to avoid resource conflict

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1499)
> Add sponsor logos

- pkg/fission-cli/cmd/environment/command.go
- pkg/fission-cli/cmd/environment/create.go
- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/httptrigger/command.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/kubewatch/command.go
- pkg/fission-cli/cmd/kubewatch/create.go
- pkg/fission-cli/cmd/mqtrigger/command.go
- pkg/fission-cli/cmd/mqtrigger/create.go
- pkg/fission-cli/cmd/package/command.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/package/update.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/cmd/timetrigger/command.go
- pkg/fission-cli/cmd/timetrigger/create.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
Continue the work of PR #1483
Resolves #895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1504)
> Add --dry option to view the generated spec without saving

- pkg/apis/core/v1/types.go
- pkg/fission-cli/cmd/spec/apply.go
- pkg/fission-cli/cmd/spec/list.go
- pkg/fission-cli/cmd/spec/validate.go
- pkg/fission-cli/console/log.go
Resolves #1410
continue the work of #1484
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1506)
> Add resource exists error on spec validate

- pkg/executor/executortype/poolmgr/gp.go
Use "Patch" to update pod metadata instead of "Update" to avoid dropping fields that the client-go doesn't support.
Fix #719
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1509)
> Use patch for robust pod metadata update in poolmgr

- charts/fission-core/values.yaml
Fix #1510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1513)
> Set prometheus.enabled=false in core chart

- pkg/fission-cli/cliwrapper/driver/cobra/helptemplate/templater.go
- pkg/fission-cli/cliwrapper/driver/cobra/helptemplate/templates.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1516)
> Show global options in usage

- pkg/executor/reaper/reaper.go
Executor wrongly deletes role bindings if the user
creates environment in the reserved namespaces. This
PR is a quick fix to solve the problem by checking if
an environment is under reserved namespaces.
Fix #1488 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1517)
> Fix executor wrongly deletes rolebindings

- environments/jvm/pom.xml
Adds XML support for Spring Rest Controller; for Java environment.
Addresses https://github.com/fission/fission/issues/1505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1512)
> Java env: Add XML dependency

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1521)
> Update slack invitation link

- pkg/fission-cli/flag/flag.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1524)
> Update TerminationGracePeriod usage text

- test/build.sh
- test/test_utils.sh
This reverts commit 36876025084a5cb7ffadea0d157f1afe2c2d0bd5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1525)
> Revert "Temporarily disable building JVM image during CI builds"

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
- hack/release-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1526)
> Release 1.8.0

- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1527)
> Fix github_changelog_generator error

- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/poolmgr/gp.go
Solve #1528
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1530)
> Append Environment labels to function pod labels

- pkg/fetcher/config/config.go
In some cases (#1384), users may want to access the file in the directory of deploy archive, however, we use the function UID name as the directory name and make it difficult for users to use as they don't know the real path of directory.
This PR use the fix name "deployarchive" to make things easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1529)
> Place package deploy archive to fix path

- cmd/fission-bundle/main.go
- cmd/fission-bundle/mqtrigger/mqtrigger.go
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq.go
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq_test.go
- pkg/mqtrigger/messageQueue/kafka/kafka.go
- pkg/mqtrigger/messageQueue/messagequeue.go
- pkg/mqtrigger/messageQueue/nats/nats.go
- pkg/mqtrigger/mqtmanager.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1531)
> Reorganize message queue trigger directory structure

- pkg/fission-cli/cmd/function/test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1539)
> Fix function test timeout doesnt works

- pkg/fetcher/fetcher.go
In some cases, creating a package and querying the package info
immediately the Kubernetes API server will return "not found"
error. So retry the query again after some time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1540)
> Retry querying package info when "not found"

- cmd/fission-bundle/mqtrigger/mqtrigger.go
- cmd/fission-cli/app/app.go
- pkg/apis/core/v1/validation.go
- pkg/fission-cli/cmd/mqtrigger/create.go
- pkg/fission-cli/flag/flag.go
- pkg/mqtrigger/factory/factory.go
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq.go
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq_test.go
- pkg/mqtrigger/messageQueue/kafka/kafka.go
- pkg/mqtrigger/messageQueue/nats/nats.go
- pkg/mqtrigger/mqtmanager.go
- pkg/mqtrigger/validator/validator.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1537)
> Add message queue service factory

- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/zz_generated.deepcopy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/update.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
This PR allows users to specify the idle timeout setting at Function-level.
Fix #1050
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1538)
> Support Function-level idle timeout setting

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1563)
> Adding community meeting link and document

- environments/python/Dockerfile
For fixing https://github.com/fission/fission/issues/1571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1572)
> Python Env Build issue due to gevent

- skaffold.yaml
Changing values being passed to Helm as per Skaffold's upstream change for fixing #1562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1567)
> [WIP] Skaffold Fix 

- skaffold.yaml
Skaffold now allows the repo to be configured in Skaffold local config and does not need change to Skaffold file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1575)
> Skaffold Default Repo

- pkg/fission-cli/cliwrapper/driver/cobra/cobra.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1580)
> Show short flag on CLI usage

- kind.yaml
Added WIP Kind Config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1587)
> Kind config 

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/requirements.lock
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/requirements.lock
- charts/fission-core/values.yaml
- environments/python/Dockerfile-2.7
- hack/release-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1597)
> Release 1.9.0

- cmd/fission-cli/app/app.go
- pkg/fission-cli/cmd/function/log.go
- pkg/fission-cli/cmd/function/test.go
- pkg/fission-cli/cmd/support/dump.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/fission-cli/util/portforward.go
- pkg/fission-cli/util/util.go
#1102 Added support of flag kube-context, to specify kubernetes context
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1595)
> Added support for kube-context flag, to specify kubernetes context

- pkg/executor/util/merge.go
Fixes https://github.com/fission/fission/issues/1599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1601)
> Make mergePodSpec pick up enableServiceLinks

- skaffold.yaml
Keeping this PR open till Skaffold default-repo issue is resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1617)
> Skaffold registry

- environments/python/Dockerfile
- environments/python/Dockerfile-2.7
- environments/python/builder/Dockerfile
Reference to Issue : https://github.com/fission/fission/issues/1632
Made Changes to install pip3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1633)
> Python env changes for pip3

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1658)
> Release 1.10.0

- charts/fission-all/config/fluentbit.conf
- charts/fission-all/values.yaml
Fixed the issue associated with breaking change Link: https://docs.fluentbit.io/manual/installation/upgrade-notes#fluent-bit-v-1-1 
#1634
Before Changes:
```
➜ ~ kubectl set image daemonset/logger -n fission fluentbit=fluent/fluent-bit:1.5.1
➜ ~ kubectl delete pod -n fission -l svc=influxdb
pod "influxdb-6769d89744-dq9tw" deleted
➜ ~ fission fn test --name consumer --body "{\"message_number\": 1, \"time_stamp\": 2020-07-23 06:48:00.329654703\"\"}" 
{"message_number":1,"time_stamp":"2020-07-23 06:48:00.329654703"}
➜ ~ fission function log --name=consumer
➜ ~
➜ ~
```
After applying changes:
```
➜ ~ kubectl set image daemonset/logger -n fission fluentbit=fluent/fluent-bit:1.5.1
➜ ~ kubectl delete pod -n fission -l svc=influxdb
pod "influxdb-6769d89744-swjck" deleted
➜ ~ fission fn test …
```
> Added prefix tag in fluentbit filter stanza

- environments/python/requirements.txt
- environments/python/server.py
resolve https://github.com/fission/fission/issues/1665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1669)
> 1665: instegration sentry

- skaffold.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1709)
> Skaffold: Typo in Helm values for Prometheus

- hack/travis-kube-setup.sh
- test/test_utils.sh
- test/tests/test_env_vars.sh
- test/upgrade/fission_upgrade_test.sh
- test/upgrade/fixture_tests.sh
Signed-off-by: Vishal Biyani <vrbiyani@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1715)
> Bumping up release of Helm for release script

- CONTRIBUTING.md
- README.md
Signed-off-by: Vishal Biyani <vrbiyani@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1726)
> Improving contributing docs

- pkg/crd/crdvalidations.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1727)
> Added concurrency field to schema validation

- pkg/executor/fscache/functionServiceCache.go
- pkg/newcache/poolcache.go
- pkg/newcache/poolcache_test.go
#1722 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1724)
> Added code to prevent deletion of active fn pod

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1731)
> [skip ci] fix contributing.md link on readme

- README.md
> Let me know the required changes to be done in this. Open to any ideas. Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1742)
> fix(docs): Update Readme

- charts/fission-all/templates/router.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/router.yaml
- charts/fission-core/values.yaml
- pkg/router/functionHandler.go
- pkg/router/httpTriggers.go
- pkg/router/router.go
1. Added flag for unTapService
2. Moved unTapservice to a goroutine to improve performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1784)
> Added flag and moved unTapservice to goroutine

- pkg/crd/crdvalidations.go
- test/test_utils.sh
This fix addresses #1805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1818)
> Added field to preserve fields during CRD validation

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- pkg/mqtrigger/messageQueue/kafka/kafka.go
Addresses #1730
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1829)
> Added flag for insecureSkipVerfiy

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
- hack/Dockerfile
- hack/release-build.sh
- hack/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1838)
> Release 1.11.1

- pkg/crd/crdvalidations.go
- pkg/fission-cli/cmd/environment/command.go
- pkg/fission-cli/cmd/environment/update.go
Addresses #1721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1833)
> Fix env resources getting pruned due to CRD Validation

- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1843)
> Release 1.11.2

- pkg/publisher/publisher.go
- pkg/publisher/webhookPublisher.go
As part of #58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1822)
> Fix golint warnings for publisher package

- pkg/fission-cli/cmd/canaryconfig/command.go
- pkg/fission-cli/cmd/support/command.go
- pkg/router/analytics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1799)
> in-progress golint warning fixes

- pkg/mqtrigger/scalermanager_test.go
Line 11 and line 12 is same package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1897)
> Remove unnecessary import package.

- go.mod
- pkg/fission-cli/cmd/spec/buildwatch.go
Fixes https://github.com/fission/fission/issues/1881
> Exit with status code 1 on failed package builds

- charts/fission-all/values.yaml
- charts/fission-core/values.yaml
> Updated tags of connector images

- pkg/executor/util/merge.go
> Add fields to pod spec

- pkg/apis/core/v1/types.go
- pkg/crd/crdvalidations.go
- pkg/executor/api.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/flag/flag.go
> Increase default concurrency

- examples/nodejs/hello.js
- test/tests/test_kubectl/spec-yaml/function-go.yaml
- test/tests/test_package_checksum.sh
Signed-off-by: Vishal Biyani <vrbiyani@gmail.com>
> Restoring one example as it is used in many places including Helm charts

- cmd/preupgradechecks/main.go
- cmd/preupgradechecks/preupgradechecks.go
This PR adds a preupgrade check for the newer field RPP . A similar pattern can be followed whenever a new field is added
> Add preupgrade check for RPP

- hack/delete-crds.sh
> Cleanup and remove hardcoding from delete-crds script

- go.mod
- go.sum
- pkg/fission-cli/cmd/spec/apply.go
> Add a warning if spec is applied on a dirty worktree

- cmd/preupgradechecks/preupgradechecks.go
- crds/v1/fission.io_httptriggers.yaml
- crds/v1/fission.io_kuberneteswatchtriggers.yaml
- crds/v1/fission.io_messagequeuetriggers.yaml
- crds/v1/fission.io_timetriggers.yaml
- go.sum
- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/zz_generated.deepcopy.go
- pkg/mqtrigger/scalermanager.go
Adding Pod Spec to MQT 
**NOTE**
Requires users to update their fission cli .
> Keda podspec

- Makefile
> Add make targets for CRDs 

- test/tests/test_specs/test_spec_merge/test_spec_merge.sh
- test/tests/test_specs/test_spec_multifile.sh
> Wait for small time to avoid timeout in specs tests

- test/tests/test_archive_pruner.sh
- test/tests/test_environments/test_go_env.sh
- test/tests/test_environments/test_java_builder.sh
- test/tests/test_environments/test_java_env.sh
- test/tests/test_environments/test_nodejs_env.sh
- test/tests/test_environments/test_python_env.sh
- test/tests/test_environments/test_tensorflow_serving_env.sh
- test/tests/test_huge_response/test_huge_response.sh
- test/tests/test_ingress.sh
- test/tests/test_internal_routes.sh
- test/tests/test_kubectl/test_kubectl.sh
- test/tests/test_specs/test_spec_merge/test_spec_merge.sh
> Capture timestamp whenever cleanup is triggered in tests

- .github/workflows/push_pr.yaml
- Makefile
> Collect fission dump if CI tests fails & enable manual trigger

- pkg/executor/reaper/reaper.go
- pkg/utils/rbacutils.go
Fixes https://github.com/fission/fission/issues/2057
> Move RBAC v1beta1 to v1

- pkg/fission-cli/cmd/environment/create.go
- pkg/fission-cli/cmd/environment/update.go
Addresses #1720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fission/fission/1837)
> Pool size warning

- Makefile
- hack/buildx.sh
> Correct docker platforms and optimize make commands

- cmd/builder/Dockerfile.fission-builder
- crds/v1/fission.io_httptriggers.yaml
- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/validation.go
- pkg/apis/core/v1/zz_generated.deepcopy.go
- pkg/canaryconfigmgr/canaryConfigMgr.go
- pkg/canaryconfigmgr/prometheusClient.go
- pkg/controller/api_test.go
- pkg/controller/httpTriggerApi.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/test.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/httptrigger/get.go
- pkg/fission-cli/cmd/httptrigger/update.go
- pkg/fission-cli/cmd/spec/list.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/flag/flag.go
- pkg/router/httpTriggers.go
> Support for multiple HTTP verbs in routes/HTTPTrigger

- cmd/builder/main.go
- cmd/fetcher/app/server.go
- cmd/fetcher/main.go
- cmd/fission-bundle/main.go
- cmd/preupgradechecks/main.go
- cmd/reporter/app/cmd_event.go
- cmd/reporter/main.go
- crds/v1/fission.io_httptriggers.yaml
- demos/declarative-specs/hello.go
- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/validation.go
- pkg/crd/crd.go
- pkg/executor/util/merge.go
- pkg/mqtrigger/scalermanager.go
- pkg/mqtrigger/scalermanager_test.go
- pkg/poolcache/poolcache_test.go
- pkg/router/functionHandler.go
- test/tests/mqtrigger/nats/stan-sub/main.go
- test/tests/test_huge_response/hello.go
> Fix golang lint errors

- .github/workflows/codeql.yaml
> Use codeql for code scanning

- .github/workflows/codeql.yaml
- CHANGELOG.md
- hack/release.sh
- test/kind_CI.sh
> Correct release name in release script for non helm install

- .github/workflows/upgrade_test.yaml
- .golangci.yaml
- cmd/builder/main.go
- cmd/fetcher/main.go
- cmd/fission-bundle/main.go
- cmd/preupgradechecks/main.go
- demos/declarative-specs/hello.go
- pkg/controller/client/v1/canaryconfig.go
- pkg/controller/client/v1/environment.go
- pkg/controller/client/v1/fake/fake_misc.go
- pkg/controller/client/v1/httptrigger.go
- pkg/controller/client/v1/mqtrigger.go
- pkg/controller/client/v1/package.go
- pkg/controller/client/v1/timetrigger.go
- pkg/fission-cli/cmd/timetrigger/create.go
- pkg/generator/encoder/encoder.go
- test/tests/test_huge_response/hello.go
Added golang CI lint
Reference issue: https://github.com/uber-go/zap/issues/880
> Ignore errors from zap logger Sync

- .github/workflows/codeql.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
- .gitignore
- CHANGELOG.md
- charts/README.md
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
- hack/release.sh
> Changes for 1.13.1 release

- .github/workflows/codeql.yaml
- .github/workflows/lint.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
> Add a separate lint and unit test flow

- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
- Makefile
- test/upgrade_test/fission_objects.sh
> Use latest release for upgrade tests

- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
- kind.yaml
- test/tests/test_kubectl/test_kubectl.sh
> Increase timeout for kubectl test

- cmd/fetcher/app/server.go
> Fix race condition in fetcher readiness check

- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/pkgwatcher.go
- pkg/logger/logger.go
- pkg/mqtrigger/scalermanager.go
This PR replaces remaining controllers in builder manager, logger and mqtrigger scalar manager with shared index informer.
> Replace controller with generated SharedIndexerInformers

- pkg/executor/executor.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/fscache/functionServiceCache.go
> Covert maps to sync maps in executor fscache to avoid dirty reads

- charts/fission-all/values.yaml
- charts/fission-core/values.yaml
> Update keda connectors version to latest

- Documentation/wip/profiling.md
- charts/fission-all/templates/deployment.yaml
- charts/fission-all/templates/router.yaml
- charts/fission-all/values.yaml
- cmd/builder/main.go
- cmd/fetcher/main.go
- cmd/fission-bundle/main.go
- pkg/utils/profile/profile.go
- skaffold.yaml
> Add go pprof support across fission components

- pkg/router/functionHandler.go
This PR helps to debug the request/response cycle in case of trivial issues. Also ensures we are capturing function and namespace data in all messages.
> Support to dump request/response in router when debug mode enabled

- crds/README.md
> Add CRDs link for easy references

- pkg/router/functionHandler.go
- pkg/router/router.go
> Avoid dumping request headers in router

- hack/runtests.sh
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq.go
- pkg/mqtrigger/messageQueue/azurequeuestorage/asq_test.go
> Enable race detector for unit tests

- pkg/router/ingress.go
- pkg/router/util/util.go
- pkg/router/util/util_test.go
> Change Ingress version from v1beta1 to v1 for K8s 1.22+ compatibility

- go.mod
- go.sum
> Update runc to v1.0.1

- crds/v1/fission.io_httptriggers.yaml
- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/zz_generated.swagger_doc_generated.go
- pkg/fission-cli/cmd/httptrigger/command.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/httptrigger/update.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/router/functionHandler.go
Used in example https://github.com/fission/examples/pull/35
README https://github.com/fission/examples/tree/container-functions/container-functions/next-app#readme
> Option to keep or remove prefix when router triggers prefix based function

- pkg/fission-cli/cmd/timetrigger/test.go
Fixes: #2131 
```
➜ fission timer showschedule --cron "0 30 * * * *" --round 5
Current Server Time: 	2021-07-29T12:18:51Z
Next 1 invocation: 	2021-07-29T12:30:00Z
Next 2 invocation: 	2021-07-29T13:30:00Z
Next 3 invocation: 	2021-07-29T14:30:00Z
Next 4 invocation: 	2021-07-29T15:30:00Z
Next 5 invocation: 	2021-07-29T16:30:00Z
```
> Reading right flag key for rounds

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
> Update chart version to 1.14.0

- CHANGELOG.md
> Update changelog for 1.14.0

- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
> Fixed service name generation for function name < 17 chars

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
> Update chart version to 1.14.1

- CHANGELOG.md
> Update changelog for 1.14.1

- test/kind_CI.sh
- test/run_test.sh
> Reduce logs in image pull for tests

- pkg/executor/executortype/poolmgr/common.go
- pkg/executor/executortype/poolmgr/funchandlers.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/packagehandlers.go
Patch adds few improvements in pool manager and adds better
function composibility by reorganizing code.
1. Added created status in getPool call
2. Improved logging in certain areas and having logger per component
3. Separated deployment specific code in diff file for extensibility
> Organize pool manager code and few improvements

- test/tests/test_specs/test_spec_archive/specs/env-node.yaml
- test/tests/websocket/specs/env-nodejs.yaml
> Use latest env in spec-archive test

- pkg/executor/api.go
- pkg/executor/cms/cmhandler.go
- pkg/executor/cms/cmscontroller.go
- pkg/executor/cms/secrethandler.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/common.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/container/deployment.go
- pkg/executor/executortype/container/funchandlers.go
- pkg/executor/executortype/executortype.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>
> Add context for traces in executor

- skaffold.yaml
> Kind profile with opentelemetry local setup

- pkg/executor/cms/cmscontroller.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gpm.go
Generally using typed informers is more standard practise
than using SharedIndexInformer(SII) implicity. SII also lack
listers provided by informer factory and few other high level
abstractions.
> Add typed informers instead of generic SharedIndexInformers

- pkg/fission-cli/util/portforward.go
> Fix pod name in port forwarding log

- pkg/router/httpTriggers.go
With addition of prefix based routes in 1.13.1, we have turned
all internal routes prefix based. This is causing wrong responses
in functions names with common prefixes such as `hello-world` and
`hello-world-consumer`. This patch fixes it where we add a fix route
for function name and prefix path for function name with `/`.
We improve overall prefix path handing with fix and prevent breakage
for existing flow.
> Functions with common prefix path handling with internal routes

- charts/fission-all/templates/deployment.yaml
- charts/fission-all/values.yaml
- charts/fission-core/templates/deployment.yaml
- charts/fission-core/values.yaml
Completed the RedisList keda connector and tested it.
> Added redis keda connector

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- charts/fission-core/Chart.yaml
- charts/fission-core/values.yaml
> Prerelease v1.15.0-rc1

- .github/ISSUE_TEMPLATE/bug_report.md
- .goreleaser.yml
- CONTRIBUTING.md
- Documentation/README.md
- README.md
- cmd/fission-cli/app/app.go
- hack/Releasing.md
- hack/notes.md
> Update docs link to fission.io/docs

- go.mod
- go.sum
- pkg/controller/api_test.go
- pkg/fetcher/fetcher.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/kubewatch/create.go
- pkg/fission-cli/cmd/mqtrigger/create.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/package/util/util.go
- pkg/fission-cli/cmd/spec/init.go
- pkg/fission-cli/cmd/timetrigger/create.go
- pkg/storagesvc/localstorage.go
- pkg/storagesvc/s3storage.go
- pkg/storagesvc/storagesvc.go
- pkg/storagesvc/stowClient.go
- pkg/tracker/tracker.go
- pkg/utils/utils.go
Ref: https://artifacthub.io/packages/helm/fission/fission-core?modal=security-report
> security: Update go-uuid and mholt/archiver to recommended version

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart version to v1.15.0-rc2

- charts/fission-all/values.yaml
Updated the kafka version to 0.9.
> Changed kafka version to v0.9

- Makefile
- cmd/fission-cli/app/app.go
- go.sum
- pkg/fission-cli/flag/flag.go
- tools/cmd-docs/main.go
> Add command to generate Fission CLI docs

- charts/fission-all/README.md
> Add 1.15.x upgrade notes in chart README

- crds/v1/fission.io_environments.yaml
- crds/v1/fission.io_functions.yaml
- crds/v1/fission.io_messagequeuetriggers.yaml
- pkg/generated/clientset/versioned/fake/clientset_generated.go
> Run all generators with upstream 1.22 code-generator

- .github/workflows/push_pr.yaml
> Export kind logs from CI for pod restart debugging

- .goreleaser.yml
> Goreleaser Update docker manifests to publish latest images

- charts/fission-all/templates/analytics/post-install-job.yaml
- charts/fission-all/templates/analytics/post-upgrade-job.yaml
- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/controller/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/kubewatcher/deployment.yaml
- charts/fission-all/templates/mqt-fission-azurestoragequeue/deployment.yaml
- charts/fission-all/templates/mqt-fission-kafka/deployment.yaml
- charts/fission-all/templates/mqt-fission-nats/deployment.yaml
- charts/fission-all/templates/mqt-keda/deployment.yaml
- charts/fission-all/templates/pre-upgrade-checks/pre-upgrade-job.yaml
- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/templates/storagesvc/deployment.yaml
- charts/fission-all/templates/timer/deployment.yaml
- charts/fission-all/values.yaml
- skaffold.yaml
> Add termination policy customization in helm chart 

- pkg/controller/environmentApi.go
- pkg/controller/functionApi.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/fscache/functionServiceCache.go
- pkg/executor/fscache/functionServiceCache_test.go
- pkg/poolcache/poolcache.go
- pkg/poolcache/poolcache_test.go
- pkg/utils/otel/attributes.go
> Pass context to functionCache functions and debug messages in pool cache

- cmd/fission-bundle/main.go
Currently when any of fission component exists, we fail to sync
log as logger.Sync is not called before exiting.
Restructured code so that we can logger.Sync before existing from
the fission bundle component execution.
> Capture fission-bundle exit logs with sync

- CHANGELOG.md
> Update changelog with v1.15.0-rc2 release

- charts/fission-all/Chart.yaml
> Update chart logo with svg image

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update release version to 1.15.0 in charts

- CHANGELOG.md
> Update changelog for v1.15.0 release

- pkg/executor/executortype/poolmgr/gp.go
- pkg/utils/podutils.go
Trying fix for the issue reported in thread https://fissionio.slack.com/archives/C3LUX6BBP/p1638892288057800
> Retry pod choose if we get terminated or deleted pod from ready pod controller

- go.mod
- go.sum
> chore: Update dependency opencontainers/runc v1.0.3

- pkg/executor/executortype/container/deployment.go
Reorders a function to facilitate early exists and reduce conditional blocks.
This change sets the order of operations from:
- Check if no errors, and runs non-error flow (updating a deployment)
- Check if the error is a non-existing deployment (creates a new deployment)
- Returns errors all other errors
To
- Checks if errors exist and error is not missing deployment, returns early
- Checks if error is deployment does not exist (creates a new deployment)
- Runs non-error glow
Running tests on this branch.
> Simplify if logic in executor function

- go.mod
- go.sum
- pkg/mqtrigger/messageQueue/kafka/kafka.go
Fixes https://github.com/fission/fission/issues/2209
Local image: tripples/fission-bundle:sanket-dev
Verified locally with example https://github.com/fission/examples/tree/master/samples/kafka-mqt-fission
> MQT Kafka: Use Sarama Group Consumer instead of bsm/sarama-cluster library

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update release version to v1.15.1

- cmd/fetcher/app/server.go
- pkg/apis/core/v1/validation.go
- pkg/buildermgr/pkgwatcher.go
- pkg/canaryconfigmgr/canaryConfigMgr.go
- pkg/controller/watchApi.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/container/deployment.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/fscache/functionServiceCache.go
- pkg/fetcher/config/config.go
- pkg/fetcher/types.go
- pkg/fission-cli/flag/flag.go
- pkg/poolcache/poolcache.go
- pkg/router/functionHandler.go
- pkg/storagesvc/stowClient.go
- pkg/utils/rbacutils.go
- test/tests/test_obj_create_in_diff_ns.sh
- tools/cmd-docs/main.go
Spell fixes across Fission code to improve CLI documentation.
> Spell fixes across code

- CHANGELOG.md
> Update changelog for 1.15.1 release

- Makefile
- tools/cmd-docs/main.go
> Change URL structure for CLI docs with reference

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update version to v1.16.0-rc1 in chart

- CHANGELOG.md
> Update changelog for 1.16.0-rc1

- pkg/controller/configmapApi.go
- pkg/controller/secretApi.go
- pkg/router/functionHandler.go
- pkg/storagesvc/storagesvc.go
- pkg/storagesvc/stowClient.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Added a function to sanitize strings to fix security issues
> Added function to sanitize strings

- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/controller/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/kubewatcher/deployment.yaml
- charts/fission-all/templates/mqt-fission-azurestoragequeue/deployment.yaml
- charts/fission-all/templates/mqt-fission-kafka/deployment.yaml
- charts/fission-all/templates/mqt-fission-nats/deployment.yaml
- charts/fission-all/templates/mqt-keda/deployment.yaml
- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/templates/storagesvc/deployment.yaml
- charts/fission-all/templates/timer/deployment.yaml
- charts/fission-all/values.yaml
Added imagepullsecrets to helm.
Fixes #2336 
Tested it by adding the docker image to private repo and installing it using helm.
To pass secret to helm:
```
kubectl create secret docker-registry pullsecret --docker-username $USER --docker-password $PASS --docker-email $EMAIL --dry-run=client -oyaml > secret.yaml
kubectl create -f secret.yaml -n fission
helm install fission . --namespace fission --set "imagePullSecrets[0].name=pullsecret" --set "image=blackfly19/fission-bundle" --set "imageTag=latest"
```
> Added imagepullsecrets to helm

- go.mod
- go.sum
> Update prometheus client go to v1.12.1

- go.mod
- go.sum
- pkg/fetcher/fetcher.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/spec/apply.go
- pkg/utils/utils.go
Upgraded archiver package version to v3.5.1 and made changes accordingly.
Fixes #2376
> Upgraded archiver

- cmd/builder/Dockerfile.fission-builder
- cmd/fetcher/Dockerfile.fission-fetcher
- cmd/fission-bundle/Dockerfile.fission-bundle
- cmd/preupgradechecks/Dockerfile.fission-preupgradechecks
- cmd/reporter/Dockerfile.reporter
Upgraded alpine version to 3.15
Fixes #
> Upgraded alpine version

- pkg/fission-cli/util/portforward.go
Currently we dial on localport and wait until, port forwarding
is done. Using channel instead from forwarder to wait explicitly.
Fixes #
> Optimize port forward in fission CLI by waiting on ready channel

- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
Pinning goreleaser version so that workflows don't cause errors when goreleaser is upgraded.
Fixes #
> Fixing goreleaser version

- pkg/poolcache/poolcache.go
> Check active request before decrease in functionCache

- go.mod
- go.sum
- pkg/executor/client/client.go
- pkg/router/functionHandler.go
> Add http retries in executor client with go-retryablehttp

- pkg/controller/api.go
- pkg/executor/api.go
- pkg/featureconfig/config.go
- pkg/router/auth.go
- pkg/router/auth_test.go
- pkg/router/httpTriggers.go
- pkg/router/mutablemux_test.go
- pkg/router/router.go
- pkg/storagesvc/storagesvc.go
- pkg/utils/metrics/http_metrics.go
- test/tests/test_environments/test_go_env.sh
- test/tests/test_environments/test_java_builder.sh
- test/tests/test_environments/test_tensorflow_serving_env.sh
Moved authMiddleware and authLoginHandler function to auth.go in router package.
Fixes #
> Created separate file for authmiddleware fn

- .github/workflows/lint.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
- Makefile
- skaffold.yaml
- test/upgrade_test/fission_objects.sh
> Use latest goreleaser with GOAMD64 support

- .mergify.yml
> Update .mergify.yml by removing commit_message field

- pkg/fission-cli/cmd/environment/command.go
- pkg/fission-cli/cmd/environment/update.go
> feat: 🎸 add runtime-env flags to the env update cmd

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update helm version to 1.16.0-rc2

- CHANGELOG.md
> Update changelog for 1.16.0-rc2

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update helm chart version to v1.16.0

- CHANGELOG.md
> Add changelog for 1.16.0 release

- pkg/executor/metrics/metrics.go
We don't use `function_uid` as a label now. Instead we use `function_namespace`.
Fixes #
> Fixed help for ColdStarts metric in executor according to new labels

- cmd/fission-cli/app/app.go
Signed-off-by: Shubham Nazare <shubham4443@gmail.com>
This PR fixes the issue where user sees error while executing `fission check --pre` without having fission installed.
Fixes #2436
> Fix pre-check failure during new fission installation

- Makefile
- crds/v1/fission.io_canaryconfigs.yaml
- crds/v1/fission.io_environments.yaml
- crds/v1/fission.io_functions.yaml
- crds/v1/fission.io_httptriggers.yaml
- crds/v1/fission.io_kuberneteswatchtriggers.yaml
- crds/v1/fission.io_messagequeuetriggers.yaml
- crds/v1/fission.io_packages.yaml
- crds/v1/fission.io_timetriggers.yaml
> Update controller-tools to v0.9.2

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update release version v1.17.0-rc1

- CHANGELOG.md
> Update changelog for 1.17.0-rc1

- cmd/builder/Dockerfile.fission-builder
- cmd/fetcher/Dockerfile.fission-fetcher
- cmd/fission-bundle/Dockerfile.fission-bundle
- cmd/preupgradechecks/Dockerfile.fission-preupgradechecks
- cmd/reporter/Dockerfile.reporter
- pkg/fission-cli/util/portforward.go
upgraded alpine version from 3.15 to 3.16
Fixes #
> Upgrade alpine version from 3.15 to 3.16

- go.mod
- go.sum
- pkg/featureconfig/config.go
- pkg/fission-cli/cmd/spec/init.go
- pkg/fission-cli/cmd/spec/spec.go
- pkg/fission-cli/cmd/support/resources/resource.go
- pkg/fission-cli/cmd/version/version.go
- pkg/generator/encoder/encoder.go
> Use sig.k8s.io/yaml instead of ghodss/yaml

- go.mod
- go.sum
- pkg/mqtrigger/messageQueue/kafka/consumer.go
- pkg/mqtrigger/messageQueue/kafka/kafka.go
- pkg/mqtrigger/mqtmanager.go
> Reestablish kakfa consumer group session on disconnection

- .github/workflows/release.yaml
- .goreleaser.yml
- hack/release.sh
We want to automate releases based on tags using GitHub Actions
This PR adds a release workflow that triggers on a tag being pushed.
> Add Github actions release CI

- .github/workflows/release.yaml
Fixes Github actions build failure for v1.16.1
> Remove CRD generation from release workflow

- .github/workflows/codeql.yaml
- .github/workflows/lint.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
- .mergify.yml
- README.md
- hack/Releasing.md
- hack/notes.md
- hack/release.sh
> Change default branch to main across repository

- .gitignore
- Makefile
- examples/nodejs/hello.js
- plugins.yaml
- tools/crd-ref-docs/config.yaml
> Remove usused files and refactor crd ref docs generation

- charts/fission-all/values.yaml
Added description of endPoint s3 property for storage type s3.
> Add endPoint property description

- pkg/utils/otel/provider_test.go
Fix typo in test error message
> Propagators test error

- charts/fission-all/templates/mqt-keda/deployment.yaml
- charts/fission-all/values.yaml
- pkg/fission-cli/flag/flag.go
- pkg/mqtrigger/validator/validator.go
added supported for KEDA Jetstream Connector
Fixes #
> add values for jetstream connector

- pkg/canaryconfigmgr/canaryConfigMgr.go
- pkg/canaryconfigmgr/prometheusClient.go
- pkg/controller/functionApi.go
> Propogate context for prometheus queries via canaryconfig ops

- pkg/fission-cli/cmd/function/getmeta.go
`fission function getmeta` was only showing name and environment of the function. This change adds Annotations and Labels.
Fixes #
- [X ] I have done manual verification of my changes, changes working as expected.
> Dump labels and annotations for function via getmeta cli

- .github/workflows/lint-dashboards.yaml
- hack/lint-dashboards.sh
> Add Grafana dashboard linting workflow

- .github/workflows/codeql.yaml
- .github/workflows/lint-dashboards.yaml
- .github/workflows/lint.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/release.yaml
- .github/workflows/upgrade_test.yaml
- cmd/builder/main.go
> Optimize Github action workflows for Go version identification

- charts/fission-all/dashboards/.lint
- charts/fission-all/dashboards/fission-admin-dashboard.json
- charts/fission-all/dashboards/fission-user-dashboard.json
- charts/fission-all/templates/dashboards/dashboards.yaml
- charts/fission-all/values.yaml
- hack/lint-dashboards.sh
> Add grafana dashboards and configmap creation for auto provisioning

- charts/fission-all/templates/buildermgr/podmonitor.yaml
- charts/fission-all/templates/controller/servicemonitor.yaml
- charts/fission-all/templates/executor/servicemonitor.yaml
- charts/fission-all/templates/mqt-fission-kafka/deployment.yaml
- charts/fission-all/templates/mqt-fission-kafka/podmonitor.yaml
- charts/fission-all/templates/router/servicemonitor.yaml
- charts/fission-all/templates/storagesvc/servicemonitor.yaml
- charts/fission-all/values.yaml
New PR based on changes in #2536 
Fixes #2535
> Add ServiceMonitor additional labels and PodMonitor

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart and app version for 1.17.0-rc2

- charts/fission-all/templates/dashboards/dashboards.yaml
> Fix helm chart dashboard configmap template

- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yml
The changes were tested by running the full workflow multiple times on my fork https://github.com/kanuahs/fission/actions/workflows/release.yaml
> Add cosign binary and image signing to release workflow.

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart version for v1.17.0

- .golangci.yaml
- charts/fission-all/dashboards/.lint
- charts/fission-all/dashboards/fission-admin-dashboard.json
- pkg/storagesvc/metrics.go
> Enable promlinter and enhance exposed metrics.

- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/utils/maps/map.go
copy the fnMeta.Annotations to the newdeploy
Fixes #2553
> feat: add copy the fn annotations to the deploy annotations

- charts/fission-all/templates/buildermgr/clusterrole.yaml
- charts/fission-all/templates/controller/clusterrole.yaml
- charts/fission-all/templates/executor/clusterrole.yaml
- charts/fission-all/templates/kubewatcher/clusterrole.yaml
- charts/fission-all/templates/mqt-fission-kafka/clusterrole.yaml
- charts/fission-all/templates/mqt-keda/clusterrole.yaml
- charts/fission-all/templates/pre-upgrade-checks/clusterrole.yaml
- charts/fission-all/templates/router/clusterrole.yaml
- charts/fission-all/templates/timer/clusterrole.yaml
> Grant CustomResourcedefintion read permission to specific components

- .github/workflows/codeql.yaml
- .github/workflows/lint-dashboards.yaml
- .github/workflows/lint.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
- pkg/utils/utils.go
> Skip CI jobs if label added to PR

- charts/fission-all/templates/_function-access-role.tpl
- charts/fission-all/templates/misc-functions/role.yaml
- charts/fission-all/templates/misc-functions/rolebinding.yaml
Role and RoleBinding for fission-fetcher and fission-builder can be created in additional namespaces
Roles and RoleBindings will be created for each namespace mentioned in the `additionalFissionNamespace` list in `values.yaml`
> Role and RoleBinding for fission-fetcher and fission-builder for user configured namespaces

- Makefile
- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- pkg/fission-cli/cmd/environment/delete.go
- pkg/fission-cli/flag/flag.go
- pkg/utils/gitrepo/gitrepo.go
- pkg/utils/utils_test.go
> Update chart version to v1.18.0-rc1

- pkg/timer/main.go
- pkg/timer/timer.go
- pkg/timer/timerSync.go
> Use informer for time trigger handling with multiple namespace support

- pkg/fission-cli/cmd/kubewatch/command.go
- pkg/kubewatcher/kubewatcher.go
- pkg/kubewatcher/main.go
- pkg/kubewatcher/watchSync.go
> Use informer for kube watcher handling with multiple namespace support

- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/envwatcher.go
> Use informer for environment handling in buildermanager with multiple namespaces

- charts/fission-all/templates/_certs.tpl
- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/webhook-server/cert.yaml
- charts/fission-all/templates/webhook-server/webhooks.yaml
- charts/fission-all/values.yaml
> Add self signed cert generation in helm chart for webhooks

- charts/fission-all/templates/_certs.tpl
- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/webhook-server/webhooks.yaml
> Service name and caBundle fixes

- pkg/fission-cli/cmd/function/command.go
- pkg/fission-cli/cmd/function/log.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/flag/key/key.go
- pkg/fission-cli/logdb/influxdb.go
- pkg/fission-cli/logdb/kubernetes_log.go
- pkg/fission-cli/logdb/logdb.go
- test/tests/test_logging/test_function_logs.sh
Added functionality to fetch logs from pods using k8s APIs.
Fixes #
Run command 
`fission fn log --name <fn_name>`
sample output:
> Get logs from Pods using Kubernetes API for function log command

- pkg/storagesvc/storagesvc.go
> Capture trace_id in storage service logs

- pkg/builder/builder.go
> Capture trace_id in builder logs

- pkg/buildermgr/pkgwatcher.go
- We had duplicate builds getting triggered for the builder manager.  This fix removes cache checks from the go routine.
So that we check the cache first and then only trigger the build.
- Also added namespace in cache key so that no possible collision if package name and resource version is same.
Please check below testing section below where we see a build with the same resource version twice.
Fixes #
```
$ ack "starting build for package" | grep -oh "\"package_name\"\:\".*\"\,\"resource_version\"\:\".*\"" | sort
"package_name":"11590","resource_version":"5145"
"package_name":"11590","resource_version":"5145"
"package_name":"11886","resource_version":"6362"
"package_name":"11886","resource_version":"6362" …
```
> Move build cache key operation from goroutine

- .github/workflows/lint.yaml
- .golangci.yaml
> Update golangci-lint version to v1.50.1

- pkg/router/auth_test.go
wait exponentially in test case until the server starts
Fixes #
> wait in testcase until server starts

- pkg/executor/cms/cmscontroller.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr_test.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/executortype/poolmgr/poolpodcontroller_test.go
- pkg/utils/informer.go
Consider specific namespaces mentioned by the user in building informers in executor
- Confimaps
- Secrets
- Deployments
- Services
- Pods
- Replicasets
Fixes #
> K8s informer to work with specific namespaces for executor

- .github/workflows/push_pr.yaml
- pkg/fission-cli/cmd/canaryconfig/create.go
- skaffold.yaml
> Upgrade skaffold to v2 manifest

- pkg/executor/executortype/poolmgr/gpm.go
- pkg/utils/informer.go
> Check pods events via infomer in user configured namespaces

- pkg/utils/namespace.go
- pkg/utils/namespace_test.go
> Fix namespace resolution with DEFAULT_NAMESPACE and other parameters set

- .github/workflows/push_pr.yaml
> Change archive location for integration-test-old job

- hack/dump-analyzer
- hack/dump-analyzer.md
> Pass prometheus dump path and port to analyzer script

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart version 1.18.0-rc2

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart version to 1.18.0

- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/fission-cli/flag/flag.go
Signed-off-by: Nikhl Sharma <nikhilsharma230303@gmail.com>
This PR allows users to set the value of the `environment grace period` to any non-negative integer.
Fixes #2686
> allow users to set envGracePeriod to 0

- cmd/builder/Dockerfile
- cmd/fetcher/Dockerfile
- cmd/fission-bundle/Dockerfile
- cmd/preupgradechecks/Dockerfile
- cmd/reporter/Dockerfile
This PR include changes to upgrade alpine image version from 3.16 to 3.17.
> Security upgrade alpine from 3.16 to 3.17

- .github/workflows/lint-dashboards.yaml
- .github/workflows/lint.yaml
- go.mod
- pkg/executor/executor_test.go
- pkg/router/functionHandler.go
> Update Go version 1.20

- pkg/executor/executortype/poolmgr/gp.go
> End retry loop when the request cancelled for the choosePod

- pkg/kubewatcher/kubewatcher.go
- pkg/publisher/publisher.go
- pkg/publisher/publisher_test.go
- pkg/publisher/webhookPublisher.go
- pkg/timer/timer.go
add trace and timeout support for the timer
Fixes #2751
> feat: add trace and timeout support for the timer

- pkg/builder/client/client.go
The old retry policy is too simple, we can use the pkg retryablehttp to replace it
Fixes #2749
> refactor: update the client retry by the pkg retryablehttp

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart version to v1.19.0-rc1

- pkg/executor/executortype/newdeploy/newdeploymgr_test.go
- pkg/utils/namespace.go
- pkg/utils/namespace_test.go
> style: typo for the BuilderNamespace

- pkg/utils/profile/profile.go
error listen port for the pprof server
Fixes #
> Fix error port for the pprof server

- pkg/builder/client/client.go
> fix: panic for the builder/client

- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/metrics/metrics.go
The cold start failure of poolmgr function is not counted in metric.
Fixes #2754
> fix: lose cold start error counter for the poolmgr functions

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart version to v1.19.0-rc2

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart version to v1.19.0

- test/upgrade_test/fission_objects.sh
> fix: Environment typo

- .github/workflows/push_pr.yaml
- .github/workflows/release.yaml
- .github/workflows/upgrade_test.yaml
- .mergify.yml
- pkg/fission-cli/util/util.go
Change CI versions
- "v1.23.17"
- "v1.25.11"
-  "v1.27.3"
Fixes #
> Update kubernetes versions in CI verification

- go.mod
- go.sum
- pkg/executor/executortype/newdeploy/newdeploymgr_test.go
- pkg/fetcher/fetcher.go
- pkg/fission-cli/cmd/function/create.go
- pkg/fission-cli/cmd/function/create_test.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/kubewatch/create.go
- pkg/fission-cli/cmd/mqtrigger/create.go
- pkg/fission-cli/cmd/package/create.go
- pkg/fission-cli/cmd/package/package.go
- pkg/fission-cli/cmd/package/util/util.go
- pkg/fission-cli/cmd/spec/init.go
- pkg/fission-cli/cmd/timetrigger/create.go
- pkg/storagesvc/localstorage.go
- pkg/storagesvc/s3storage.go
- pkg/tracker/tracker.go
- pkg/utils/serviceaccount.go
- pkg/utils/utils.go
- pkg/utils/uuid/uuid.go
Switch uuid from `satori/go.uuid` to `google/uuid` as we use uuid v4.
`google/uuid` is more maintained and used in kubernetes as well.
Fixes #
> Switch to google/uuid from satori/go.uuid

- charts/fission-all/Chart.yaml
- charts/fission-all/README.md
- charts/fission-all/templates/NOTES.txt
- charts/fission-all/values.yaml
- Update kubernets version 1.23+
- Update post chart install notes with namespace info
- Update upgrade notes in chart
Fixes #
> Update chart version 1.20.0-rc1

- cmd/preupgradechecks/checks.go
- pkg/apis/core/v1/validation.go
- pkg/buildermgr/buildermgr.go
- pkg/canaryconfigmgr/config.go
- pkg/crd/key.go
- pkg/executor/api.go
- pkg/executor/cms/cmscontroller.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/common.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/container/deployment.go
- pkg/executor/executortype/newdeploy/newdeploy.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/fscache/poolcache.go
- pkg/executor/util/merge.go
- pkg/executor/util/util.go
- pkg/featureconfig/config.go
- pkg/fission-cli/cmd/function/test.go
- pkg/router/httpTriggers.go
- test/e2e/cli/cli_test.go
- test/e2e/framework/services/services.go
Added more tests with envtest for httptrigger and container/newdeploy
Fixes #
> Test for httptrigger and functions container/newdeploy

- pkg/executor/executor.go
- pkg/executor/reaper/reaper.go
- pkg/fission-cli/cmd/function/test.go
- pkg/publisher/webhookPublisher.go
- pkg/router/functionHandler.go
- pkg/router/httpTriggers.go
- pkg/tracker/tracker.go
> Add cause for all context timeouts

- Makefile
- cmd/fission-bundle/main.go
- cmd/fission-bundle/mqtrigger/mqtrigger.go
- pkg/builder/client/client.go
- pkg/buildermgr/buildermgr.go
- pkg/crd/client.go
- pkg/executor/client/client.go
- pkg/executor/executor.go
- pkg/fetcher/client/client.go
- pkg/kubewatcher/main.go
- pkg/mqtrigger/scalermanager.go
- pkg/router/functionHandler.go
- pkg/router/httpTriggers.go
- pkg/router/router.go
- pkg/storagesvc/client/client.go
- pkg/timer/main.go
- test/e2e/framework/services/services.go
- Making all fission contained http clients internal and adding interfaces for them
- This would help in testing services individually and test them with mocks
Fixes #
> Add interfaces for executor/fetcher/storagesvc clients

- cmd/fetcher/app/server.go
- cmd/fission-bundle/main.go
- pkg/buildermgr/buildermgr.go
- pkg/buildermgr/envwatcher.go
- pkg/buildermgr/pkgwatcher.go
- pkg/canaryconfigmgr/canaryConfigMgr.go
- pkg/canaryconfigmgr/config.go
- pkg/executor/executor.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/executortype.go
- pkg/executor/executortype/newdeploy/newdeploymgr.go
- pkg/executor/executortype/newdeploy/newdeploymgr_test.go
- pkg/executor/executortype/poolmgr/gpm.go
- pkg/executor/executortype/poolmgr/poolpodcontroller.go
- pkg/executor/executortype/poolmgr/poolpodcontroller_test.go
- pkg/kubewatcher/main.go
- pkg/kubewatcher/watchSync.go
- pkg/mqtrigger/mqtmanager.go
- pkg/mqtrigger/scalermanager.go
- pkg/router/httpTriggers.go
- pkg/router/router.go
- pkg/storagesvc/archivePruner.go
- pkg/storagesvc/storagesvc.go
- pkg/timer/main.go
- pkg/timer/timerSync.go
- pkg/utils/manager/manager.go
- pkg/utils/manager/manager_test.go
- pkg/utils/serviceaccount.go
- pkg/utils/serviceaccount_test.go
In continuation to the PR: https://github.com/fission/fission/pull/2869, this PR adds manager in more places.
This PR also adds one more function : AddInformers to manager, so that informers can also be managed by it.
Fixes #
> Add informers and internal go routines in manager

- pkg/executor/executortype/poolmgr/gp.go
- pkg/fission-cli/cmd/function/log.go
- pkg/fission-cli/cmd/function/test.go
- pkg/fission-cli/logdb/kubernetes_log.go
- pkg/fission-cli/util/util.go
- pkg/router/functionHandler.go
- test/e2e/cli/cli_test.go
- test/e2e/framework/services/services.go
Enable function CLI test for coverage. Ignoring errors as of now.
Fixes #
> Add function test CLI tests

- .codecov.yml
- .github/workflows/lint.yaml
- cmd/fission-bundle/main.go
- cmd/fission-cli/app/app.go
- go.mod
- pkg/crd/client.go
- pkg/executor/executor.go
- pkg/fission-cli/cmd/function/test.go
- pkg/fission-cli/cmd/token/create.go
- pkg/fission-cli/flag/flag.go
- pkg/fission-cli/util/util.go
- pkg/webhook/admission-webhook.go
- test/e2e/cli/cli_test.go
- test/e2e/framework/framework.go
- test/e2e/framework/services/services.go
- test/e2e/framework/webhook-manifest.yaml
> Add webhook server to tests

- .codecov.yml
- cmd/preupgradechecks/checks.go
- cmd/preupgradechecks/checks_test.go
- cmd/preupgradechecks/main.go
- pkg/fission-cli/cliwrapper/cli/cli.go
- pkg/fission-cli/cliwrapper/driver/cobra/cobra.go
- pkg/fission-cli/cliwrapper/driver/dummy/dummy.go
- pkg/fission-cli/cmd/archive/delete.go
- pkg/fission-cli/cmd/archive/geturl.go
- pkg/fission-cli/cmd/archive/upload.go
- pkg/fission-cli/cmd/httptrigger/create.go
- pkg/fission-cli/cmd/package/util/util.go
- pkg/fission-cli/util/util.go
- test/e2e/cli/cli_test.go
- test/e2e/framework/cli/cli.go
- test/e2e/framework/framework.go
- test/e2e/framework/services/services.go
- test/tests/test_archive_cli.sh
> Add tests for preupgradchecks and spec/archive CLI

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- test/upgrade_test/fission_objects.sh
Update fission version v1.20.0-rc2
Fixes #
> Update fission version v1.20.0-rc2

- charts/fission-all/values.yaml
- Updated keda connectors images to ghcr.io 
- Updated images via https://github.com/fission/keda-connectors/pull/158
```
connector_images:
kafka:
image: ghcr.io/fission/keda-kafka-http-connector
tag: v0.13
rabbitmq:
image: ghcr.io/fission/keda-rabbitmq-http-connector
tag: v0.11
awskinesis:
image: ghcr.io/fission/keda-aws-kinesis-http-connector
tag: v0.11
aws_sqs:
image: ghcr.io/fission/keda-aws-sqs-http-connector
tag: v0.12
nats_steaming:
image: ghcr.io/fission/keda-nats-streaming-http-connector
tag: v0.14
nats_jetstream:
image: ghcr.io/fission/keda-nats-jetstream-http-connector
tag: v0.5
gcp_pubsub:
image: ghcr.io/fission/keda-gcp-pubsub-http-connector
tag: v0.7
redis:
image: ghcr.io/fission/keda-redis-http-connector
tag: v0.4
```
Fixes #
> Update keda connectors images to latest

- cmd/builder/Dockerfile
- cmd/fetcher/Dockerfile
- cmd/fission-bundle/Dockerfile
- cmd/preupgradechecks/Dockerfile
- cmd/reporter/Dockerfile
- pkg/apis/core/v1/validation.go
- pkg/buildermgr/envwatcher.go
- pkg/buildermgr/pkgwatcher.go
- pkg/executor/executortype/container/containermgr.go
- pkg/executor/executortype/poolmgr/gp_deployment.go
- pkg/executor/fscache/functionServiceCache.go
- pkg/executor/fscache/functionServiceCache_test.go
- pkg/executor/reaper/reaper.go
- pkg/executor/util/merge.go
- pkg/fetcher/fetcher.go
- pkg/fission-cli/cliwrapper/cli/cli.go
- pkg/fission-cli/cmd/function/log.go
- pkg/fission-cli/cmd/spec/apply.go
- pkg/fission-cli/logdb/influxdb.go
- pkg/storagesvc/stowClient.go
- test/e2e/framework/services/services.go
- test/tests/test_archive_cli.sh
- test/upgrade_test/fission_objects.sh
Changing the base image to cgr.dev/chainguard/static for secure base image
Fixes #
> Change container base image to cgr.dev/chainguard/static

- .goreleaser.yml
Draft release failed, need to handle cosign approval https://github.com/fission/fission/actions/runs/6983171371
Fixes #
> Update goreleaser cosign prompt approval

- .goreleaser.yml
Fix release build to sign docker builds. Verified in personal fork.
https://github.com/sanketsudake/fission/actions/runs/7002035203/job/19045061819
Fixes #
> Auto-approve goreleaser docker builds with cosign

- charts/fission-all/templates/_fission-kubernetes-roles.tpl
Created separate permissions for events in keda and executor linked roles to remove delete permissions.
This PR fixes issue - Remove event.delete permission #2884
Fixes #2884
> Separated events permission in keda and executor linked roles 

- charts/fission-all/Chart.yaml
> added annotation for signing

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/canary-config/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/kubewatcher/deployment.yaml
- charts/fission-all/templates/mqt-keda/deployment.yaml
- charts/fission-all/templates/pre-upgrade-checks/pre-upgrade-job.yaml
- charts/fission-all/templates/router/deployment.yaml
- charts/fission-all/templates/storagesvc/deployment.yaml
- charts/fission-all/templates/timer/deployment.yaml
- charts/fission-all/values.yaml
- pkg/crd/client.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Added configurable kubernetes client limits burst and QPS
Default QPS 200 and burst 500.
Fixes #
> Add kubernetes QPS and Burst limit configuration

- charts/fission-all/Chart.yaml
…hart
- Update kubernetes version constraint > 1.23.0
- Update fission version to 1.20.1
Fixes #
> Add kubernetes version constraint and update version 1.20.1 in helm chart

- charts/fission-all/values.yaml
This pull request is being raised for adding correct image tag in values.yaml
> Update chart image tag to 1.20.1

- pkg/fission-cli/cmd/package/util/util.go
> fix: close tmp file in fission CLI `WriteArchiveToFile`

- .github/workflows/push_pr.yaml
- .github/workflows/release.yaml
- .github/workflows/upgrade_test.yaml
- pkg/fission-cli/cmd/check/check.go
```
Upgraded kind version to github workflow push_pr.yaml
Upgraded kind version to github workflow release.yaml
Upgraded kind version to github workflow upgrade_test.yaml
```
Fixes #
> Upgrade kind version to v0.23.0

- pkg/crd/key.go
- pkg/executor/fscache/poolcache.go
- pkg/fission-cli/cmd/function/create.go
> Fixing code comments

- go.mod
- go.sum
- test/tests/websocket/go.mod
- test/tests/websocket/go.sum
Upgrade `golang.org/x/net` from 0.17.0 to 0.25.0
Upgrade `github.com/gorilla/websocket` from v1.5.0 to v1.5.1
Fixes #
> Upgrade libs and go version in test/tests/websocket

- .goreleaser.yml
- Failed to run `make skaffold-prebuild` command.
```
$ make skaffold-prebuild 
• starting build...
⨯ build failed after 0s                    error=yaml: unmarshal errors:
line 15: field variables not found in type config.Project
make: *** [Makefile:115: skaffold-prebuild] Error 1
```
- Issue was introduced in this [PR](https://github.com/fission/fission/pull/2952) when we used `variables` field in `.goreleaser.yml` for adding description to fission components.
- `variables` field is supported in Goreleaser Pro. https://goreleaser.com/customization/templates/#custom-variables
Fixes #
```
$ make skaffold-prebuild 
• starting build...
• loading                                          path=.goreleaser.yml
• skipping validate...
• loading environment variables
• getting and validating git …
```
> Fix: Remove `variables` field from `.goreleaser.yml`

- charts/fission-all/values.yaml
Updated `charts/fission-all/values.yaml` with latest keda-connectors image tags.
Fixes #
> Update Keda connectors image tags

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
> Update chart version to v1.20.3

- charts/fission-all/templates/fluentbit/fluentbit.yaml
- charts/fission-all/values.yaml
- This PR add supports to configure user ID for logger container's securityContext using helm `values.yaml` file.
Fixes #
> Configure user ID for logger container's securityContext using helm values.yaml

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- Update chart version to v1.20.4
- Update fission version to v1.20.4
Fixes #
> Update chart version and app version to v1.20.4

- pkg/fetcher/config/config.go
> Fix slice init length in fetcher pod spec addition

- .github/workflows/codeql.yaml
Updated codeql action version to 3.26.9
Fixes #
> Update codeql action version to 3.26.9

- .github/workflows/lint.yaml
- go.mod
- pkg/executor/executortype/poolmgr/gp.go
- pkg/mqtrigger/messageQueue/kafka/consumer.go
> Upgraded to Go latest version 1.23.1

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
- Update chart version to v1.20.5.
- Update fission version to v1.20.5.
Fixes #
> Updated app version and chart version to v1.20.5

- Makefile
- hack/runtests.sh
- pkg/fission-cli/cmd/check/check.go
> Update K8s version for envtest to 1.30.x

- pkg/fission-cli/cmd/package/info.go
- pkg/fission-cli/cmd/package/rebuild.go
- Remove unreachable code from `fission pkg info` and `fission pkg rebuild` command code.
Fixes #
```
$ fission pkg info --name test
Options:
--name=''   Package name
Global Options:
--verbosity=1 (-v)   CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)
--kube-context=''    Kubernetes context to be used for the execution of Fission commands
--namespace='' (-n)  If present, the namespace scope for this CLI request
Usage:
fission package info [options]
Error: error finding package test: packages.fission.io "test" not found
$ fission pkg rebuild --name test
Options:
--name=''   Package name
Global Options:
--verbosity=1 (-v)   CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)
--kube-context=''    Kubernetes context to be used for the execution of Fission commands …
```
> Remove unreachable code

- pkg/builder/builder.go
- pkg/executor/executortype/poolmgr/gp.go
- pkg/fetcher/fetcher.go
- pkg/utils/serviceaccount.go
- pkg/utils/utils.go
- test/tests/test_huge_response/hello.go
> Add path safety fixes

- .github/workflows/scorecard.yml
Adding OpenSSF Scorecard action
> Add OpenSSF Scorecard action

- .github/workflows/codeql.yaml
- README.md
> Add OpenSSF scorecard badge

- .github/dependabot.yml
- .github/workflows/codeql.yaml
- .github/workflows/dependency-review.yml
- .github/workflows/lint-dashboards.yaml
- .github/workflows/lint.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecard.yml
- .github/workflows/upgrade_test.yaml
- .pre-commit-config.yaml
- cmd/builder/Dockerfile
- cmd/fetcher/Dockerfile
- cmd/fission-bundle/Dockerfile
- cmd/fission-bundle/main.go
- cmd/preupgradechecks/Dockerfile
- cmd/reporter/Dockerfile
- Pinned base docker images
- Github workflow permissions
- Dependency Reviews
Fixes #
> Apply best security practices for OpenSSF

- .github/workflows/codeql.yaml
- .github/workflows/lint-dashboards.yaml
- .github/workflows/lint.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/upgrade_test.yaml
> Skip CI for dependabot PR and remove manual dispatch

- .github/workflows/codeql.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/release.yaml
- .github/workflows/upgrade_test.yaml
- .goreleaser.yml
- Add provenance for fission binaries checksums etc.
- Enable SBOM with goreleaser
Fixes #
> Add provenance steps for release

- .github/dependabot.yml
Grouping dependabot PRs for dockerfiles and github actions version updates.
> Grouped dependabot updates for dockerfile and github-actions

- .github/dependabot.yml
Grouped dependabot dependencies
Fixes #
> Update dependabot.yml grouping

- charts/fission-all/templates/webhook-server/deployment.yaml
Fixes https://github.com/fission/fission-charts/issues/96
Deploy (or run `helm template`) with and without a resource applied. Followed the style of the other template files
> fix: apply kubernetes resources to the webhook-server

- pkg/fission-cli/cmd/environment/create.go
If the users on the cluster are namespace scoped they will not have permission to list environments from other namespaces. As you removed the Namespace variable from createEnvironmentFromCmd the m.Namespace will always be the default. This will not allow users to use fission cli to create environments
Fixes #
> Update create.go to handle namespace isolation

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
Update chart version v1.21.0-rc1
Fixes #
> Update chart version v1.21.0-rc1

- charts/fission-all/templates/_helpers.tpl
- charts/fission-all/templates/buildermgr/deployment.yaml
- charts/fission-all/templates/executor/deployment.yaml
- charts/fission-all/templates/pre-upgrade-checks/pre-upgrade-job.yaml
- charts/fission-all/values.yaml
- pkg/fetcher/config/config.go
- Added imagewithTag template which helps in figuring right image path.
- Using same for fission-bundle, preupgradecheck, reporter and fetcher image.
Fixes #
Before changes
```
helm template  charts/fission-all | grep "fission/"  | grep -v ghcr
value: "fission/fetcher:v1.21.0-rc1"
value: "fission/fetcher:v1.21.0-rc1"
image: fission/pre-upgrade-checks:v1.21.0-rc1
```
After changes,
```
helm template  charts/fission-all | grep "fission/"
image: "ghcr.io/fission/fission-bundle:v1.21.0-rc1"
value: "ghcr.io/fission/fetcher:v1.21.0-rc1"
image: "ghcr.io/fission/fission-bundle:v1.21.0-rc1"
value: "ghcr.io/fission/fetcher:v1.21.0-rc1"
image: "ghcr.io/fission/fission-bundle:v1.21.0-rc1"
image: "ghcr.io/fission/fission-bundle:v1.21.0-rc1"
value: "ghcr.io/fission/keda-kafka-http-connector:v0.17" …
```
> Use GHCR repo for fetcher image by default

- charts/fission-all/Chart.yaml
- charts/fission-all/values.yaml
Update chart version v1.21.0-rc2
Fixes #
> Update chart version v1.21.0-rc2

- .golangci.yaml
fixes #3219
Fixes #3219
(with the caveat that the update lint config results in many lint rule validations that need to be fixed)
> use golangci-lint migrate to eliminate error
